# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Error(BaseModel):
    code: str = Field(..., description='Machine-readable error code')
    message: str = Field(..., description='Human-readable error message')


class ErrorResponse(BaseModel):
    error: Error


class HealthResponse(BaseModel):
    status: str


class Metadata(BaseModel):
    pass
    model_config = ConfigDict(
        extra='allow',
    )


class Kind(Enum):
    """
    Channel type
    """

    dm = 'dm'
    channel = 'channel'


class Channel(BaseModel):
    id: str
    name: str = Field(..., description='Channel slug (unique within namespace)')
    display_name: str = Field(..., description='Human-facing display name')
    topic: str | None = Field(None, description='Channel topic or description')
    kind: Kind = Field(..., description='Channel type')
    private: bool = Field(..., description='Whether the channel is private')
    created_by: str = Field(..., description='ID of the user who created the channel')
    archived_at: datetime | None = Field(
        None, description='Timestamp when the channel was archived'
    )
    created_at: datetime
    updated_at: datetime


class ChannelDataResponse(BaseModel):
    data: Channel


class ChannelListResponse(BaseModel):
    data: list[Channel]
    has_more: bool | None = None
    next_cursor: str | None = None


class Role(Enum):
    """
    Member's role in the channel
    """

    member = 'member'
    admin = 'admin'


class ChannelMember(BaseModel):
    id: str
    channel_id: str
    user_id: str
    role: Role = Field(..., description="Member's role in the channel")
    last_read_message_id: str | None = Field(
        None, description='Last message read by this member'
    )
    muted: bool | None = Field(None, description='Whether notifications are muted')
    starred: bool | None = Field(
        None, description='Whether the member has starred this channel'
    )
    joined_at: datetime


class ChannelMemberDataResponse(BaseModel):
    data: ChannelMember


class ChannelMemberListResponse(BaseModel):
    data: list[ChannelMember]
    has_more: bool | None = None
    next_cursor: str | None = None


class Display(Enum):
    """
    Rendering layout mode
    """

    message = 'message'
    notice = 'notice'
    card = 'card'


class ChannelMessage(BaseModel):
    id: str
    channel_id: str
    sender_id: str = Field(..., description='ID of the message sender (user or agent)')
    display: Display | None = Field(None, description='Rendering layout mode')
    type: str = Field(
        ..., description='Dot-namespaced message type (e.g. user.message, ai.response)'
    )
    content: str = Field(..., description='Message content (markdown)')
    reply_to: str | None = Field(
        None, description='ID of the message this is a reply to (threading)'
    )
    metadata: Metadata | None = None
    pinned: bool | None = Field(None, description='Whether this message is pinned')
    pinned_by: str | None = Field(
        None, description='ID of user who pinned this message'
    )
    edited_at: datetime | None = Field(
        None, description='When the message was last edited'
    )
    created_at: datetime


class ChannelMessageDataResponse(BaseModel):
    data: ChannelMessage


class ChannelMessageListResponse(BaseModel):
    data: list[ChannelMessage]
    has_more: bool | None = None
    next_cursor: str | None = None


class CreateChannelRequest(BaseModel):
    name: str = Field(..., description='Channel slug (unique, immutable)')
    display_name: str = Field(..., description='Human-facing display name')
    topic: str | None = Field(None, description='Channel topic or description')
    kind: Kind = Field(..., description='Channel type')
    private: bool | None = Field(
        False, description='Whether the channel is private (invite-only)'
    )
    member_ids: list[str] | None = Field(
        None, description='Initial member IDs to add to the channel'
    )


class UpdateChannelRequest(BaseModel):
    display_name: str | None = None
    topic: str | None = None
    private: bool | None = None


class Role1(Enum):
    member = 'member'
    admin = 'admin'


class AddChannelMemberRequest(BaseModel):
    user_id: str = Field(..., description='User or agent ID to add')
    role: Role1 | None = 'member'


class SendChannelMessageRequest(BaseModel):
    content: str = Field(..., description='Message content (markdown)')
    display: Display | None = Field('message', description='Rendering layout mode')
    type: str | None = Field('user.message', description='Dot-namespaced message type')
    reply_to: str | None = Field(None, description='Parent message ID for threading')
    metadata: Metadata | None = None


class UpdateChannelMessageRequest(BaseModel):
    content: str | None = Field(None, description='Updated message content (markdown)')
    metadata: Metadata | None = None
    pinned: bool | None = Field(None, description='Whether this message is pinned')


class Action(Enum):
    """
    Type of action performed
    """

    create = 'create'
    update = 'update'
    delete = 'delete'


class AuditLogEntry(BaseModel):
    id: str = Field(..., description='Unique audit log entry ID')
    user_id: str | None = Field(
        None,
        description='ID of the user who performed the action, when a human user is attributable',
    )
    actor_type: str | None = Field(
        None, description='Durable actor type that performed the action'
    )
    actor_id: str | None = Field(
        None, description='Durable actor ID that performed the action'
    )
    credential_id: str | None = Field(
        None, description='Credential ID used for the request, when applicable'
    )
    action: Action = Field(..., description='Type of action performed')
    resource_type: str = Field(
        ..., description='Type of resource affected (e.g., task, channel, document)'
    )
    resource_id: str = Field(..., description='ID of the affected resource')
    resource_name: str | None = Field(
        None, description='Human-readable name of the affected resource'
    )
    changes: dict[str, Any] | None = Field(
        None, description='Object containing before/after changes for update actions'
    )
    ip_address: str | None = Field(None, description='IP address of the request')
    user_agent: str | None = Field(None, description='User agent of the request')
    created_at: datetime = Field(
        ..., description='Timestamp when the action was performed'
    )


class AuditLogListResponse(BaseModel):
    data: list[AuditLogEntry]
    next_cursor: str | None = Field(
        None, description='Cursor for fetching next page of results'
    )
    has_more: bool = Field(..., description='Whether more results are available')


class Scope(Enum):
    org = 'org'
    system = 'system'


class APIKey(BaseModel):
    id: str
    name: str
    key_prefix: str = Field(
        ..., description='First 8 characters of the key for identification'
    )
    scope: Scope
    permissions: list[str] | None = None
    service_account_id: str | None = None
    expires_at: datetime | None = None
    last_used_at: datetime | None = None
    created_at: datetime
    updated_at: datetime


class APIKeyDataResponse(BaseModel):
    data: APIKey


class APIKeyCreateResult(BaseModel):
    id: str
    name: str
    key_prefix: str = Field(
        ..., description='First 8 characters of the key for identification'
    )
    scope: Scope
    permissions: list[str] | None = None
    service_account_id: str | None = None
    expires_at: datetime | None = None
    last_used_at: datetime | None = None
    created_at: datetime
    updated_at: datetime
    key: str = Field(..., description='The raw API key (shown only once)')


class APIKeyCreateResultDataResponse(BaseModel):
    data: APIKeyCreateResult


class APIKeyListResponse(BaseModel):
    data: list[APIKey]


class CreateAPIKeyRequest(BaseModel):
    name: str
    scope: Scope | None = 'org'
    permissions: list[str] | None = None
    service_account_id: str | None = None
    expires_at: datetime | None = None


class ConfirmDeviceCodeRequest(BaseModel):
    user_code: str
    label: str | None = None


class ConfirmDeviceCodeResult(BaseModel):
    confirmed: bool


class CLICredentialStatus(Enum):
    active = 'active'
    revoked = 'revoked'


class CLICredential(BaseModel):
    id: str
    org_id: str
    user_id: str
    label: str
    token_prefix: str
    status: CLICredentialStatus
    created_at: datetime
    updated_at: datetime
    last_used_at: datetime | None = None
    expires_at: datetime | None = None


class CLICredentialListResponse(BaseModel):
    data: list[CLICredential]


class WorkflowInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    type: str
    description: str | None = None
    default: Any | None = Field(None, description='Optional default value.')


class WorkflowOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    variable: str
    branch: str | None = Field(None, description='Defaults to `main` when omitted.')
    description: str | None = None


class WorkflowActionKind(Enum):
    """
    Execution mode for `action` steps.
    Omit for the current default of `worker`.

    """

    worker = 'worker'
    server = 'server'


class WorkflowEdgeMatchingStrategy(Enum):
    all = 'all'
    first = 'first'


class WorkflowEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step: str
    condition: str | None = None
    branch: str | None = None


class WorkflowEach(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Any = Field(
        ..., description='Expression or literal collection to iterate over.'
    )
    as_: str | None = Field(None, alias='as')


class JitterStrategy(Enum):
    NONE = 'NONE'
    FULL = 'FULL'


class WorkflowRetry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error_equals: list[str] | None = None
    max_retries: int | None = Field(None, ge=0)
    base_delay: str | None = Field(None, description='Go duration string.')
    max_delay: str | None = Field(None, description='Go duration string.')
    backoff_rate: float | None = None
    jitter_strategy: JitterStrategy | None = None
    timeout: str | None = Field(None, description='Go duration string.')


class WorkflowCatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error_equals: list[str]
    next: str
    store: str | None = None


class WorkflowJoinConfig(BaseModel):
    branches: list[str] | None = None
    count: int | None = Field(None, ge=0)
    branch_mappings: dict[str, str] | None = None


class WorkflowWaitSignalConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    topic: str
    timeout: str = Field(..., description='Go duration string.')
    store: str | None = None
    on_timeout: str | None = None


class WorkflowSleepConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    duration: str = Field(..., description='Go duration string.')


class WorkflowPauseConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: str | None = None


class Type(Enum):
    approval = 'approval'
    review = 'review'
    input = 'input'


class Mode(Enum):
    confirm = 'confirm'
    select = 'select'
    multi_select = 'multi_select'
    input = 'input'


class WorkflowInteractionOption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: str
    label: str
    description: str | None = None


class Type1(Enum):
    user = 'user'
    group = 'group'


class WorkflowInteractionTarget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type1
    id: str
    require_all: bool | None = None


class WorkflowRunStatus(Enum):
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    suspended = 'suspended'


class WorkflowRun(BaseModel):
    id: str
    namespace_id: str | None = None
    queue: str | None = None
    parent_run_id: str | None = None
    definition_id: str
    definition_version_id: str
    definition_version: int
    workflow_name: str
    status: WorkflowRunStatus
    attempt: int
    inputs: dict[str, Any] | None = None
    metadata: dict[str, str] | None = None
    error_message: str | None = None
    actor_type: str | None = None
    actor_id: str | None = None
    initiated_by: str | None = None
    external_id: str | None = None
    group: str | None = None
    callback_url: str | None = Field(
        None,
        description='Outbound customer callback URL intended for terminal run\nnotifications. The value is persisted on the run, but callback\ndelivery is not yet active.\n',
    )
    created_at: datetime
    started_at: datetime | None = None
    completed_at: datetime | None = None
    updated_at: datetime


class WorkflowRunDataResponse(BaseModel):
    data: WorkflowRun


class WorkflowRunListResponse(BaseModel):
    data: list[WorkflowRun]
    has_more: bool = Field(..., description='True when more pages are available.')
    next_cursor: str | None = Field(
        None,
        description='Opaque cursor for fetching the next page. Present only when\nhas_more is true.\n',
    )


class StartRunRequest(BaseModel):
    namespace_id: str | None = None
    queue: str | None = Field(
        None,
        description='Queue name to enqueue the run on. Defaults to the\nworkflow definition\'s queue, then "default".\n',
    )
    callback_url: str | None = Field(
        None,
        description='Outbound customer callback URL intended for terminal run\nnotifications. If set, Mobius stores this value on the run for\nfuture callback delivery, but terminal-status callback delivery is\nnot yet active.\n',
    )
    inputs: dict[str, Any] | None = None
    metadata: dict[str, str] | None = None
    external_id: str | None = None
    group: str | None = None


class ActionLogEntry(BaseModel):
    id: str
    action: str
    step_name: str
    branch_id: str
    parameters: dict[str, Any] | None = None
    result: dict[str, Any] | None = None
    error: str | None = None
    started_at: datetime
    duration_ms: int


class ActionLogListResponse(BaseModel):
    data: list[ActionLogEntry]


class Job(BaseModel):
    id: str
    namespace_id: str
    run_id: str
    parent_job_id: str | None = None
    path_id: str | None = None
    step_name: str
    action: str
    queue: str
    parameters: dict[str, Any] | None = None
    status: str
    claimed_by: str | None = None
    claimed_at: datetime | None = None
    heartbeat_at: datetime | None = None
    attempt: int
    max_attempts: int
    scheduled_at: datetime
    last_error: str | None = None
    created_at: datetime
    updated_at: datetime


class JobListResponse(BaseModel):
    data: list[Job]


class SendRunSignalRequest(BaseModel):
    name: str = Field(..., description='Signal topic (e.g. "approval", "webhook").')
    payload: dict[str, Any] | None = None


class RunSignal(BaseModel):
    id: str
    run_id: str
    name: str


class RunSignalDataResponse(BaseModel):
    data: RunSignal


class BulkRunRequest(BaseModel):
    run_ids: list[str]


class BulkRunResult(BaseModel):
    succeeded: list[str]
    failures: dict[str, str] | None = Field(
        None, description='Map of run_id -> error message for per-run failures.'
    )


class BulkRunDataResponse(BaseModel):
    data: BulkRunResult


class ActionAnnotations(BaseModel):
    idempotent: bool | None = None
    destructive: bool | None = None
    read_only: bool | None = None


class CreateActionRequest(BaseModel):
    name: str
    title: str | None = None
    description: str | None = None
    endpoint_url: AnyUrl
    input_schema: dict[str, Any] | None = None
    output_schema: dict[str, Any] | None = None
    annotations: ActionAnnotations | None = None


class UpdateActionRequest(BaseModel):
    title: str | None = None
    description: str | None = None
    endpoint_url: AnyUrl | None = None
    input_schema: dict[str, Any] | None = None
    output_schema: dict[str, Any] | None = None
    annotations: ActionAnnotations | None = None


class Action1(BaseModel):
    id: str
    org_id: str
    namespace_id: str
    name: str
    title: str | None = None
    description: str | None = None
    endpoint_url: AnyUrl
    input_schema: dict[str, Any] | None = None
    output_schema: dict[str, Any] | None = None
    annotations: ActionAnnotations | None = None
    signing_secret: str | None = None
    created_at: datetime
    updated_at: datetime


class ActionDataResponse(BaseModel):
    data: Action1


class ActionListResponse(BaseModel):
    data: list[Action1]
    next_cursor: str | None = None
    has_more: bool


class RotateSecretResult(BaseModel):
    signing_secret: str


class RotateSecretDataResponse(BaseModel):
    data: RotateSecretResult


class ActionCatalogEntry(BaseModel):
    name: str
    title: str | None = None
    description: str | None = None
    integration: str | None = None
    source: str
    available: bool
    annotations: ActionAnnotations | None = None
    input_schema: dict[str, Any] | None = None
    output_schema: dict[str, Any] | None = None
    endpoint_url: AnyUrl | None = None


class ActionCatalogDataResponse(BaseModel):
    data: ActionCatalogEntry


class ActionCatalogListResponse(BaseModel):
    data: list[ActionCatalogEntry]


class ActionAuditLogEntry(BaseModel):
    id: str
    run_id: str | None = None
    step_name: str | None = None
    action_name: str
    source: str
    parameters: dict[str, Any] | None = None
    output_summary: dict[str, Any] | None = None
    status: str
    retry_count: int
    started_at: datetime
    finished_at: datetime
    error_type: str | None = None
    error_message: str | None = None


class ActionAuditLogListResponse(BaseModel):
    data: list[ActionAuditLogEntry]
    next_cursor: str | None = None
    has_more: bool


class JobClaimRequest(BaseModel):
    worker_id: str
    worker_name: str | None = None
    worker_version: str | None = None
    queues: list[str] | None = Field(
        None,
        description='Queue names the worker subscribes to. When empty the\nworker claims from any queue in the org. Runs default\nto the "default" queue when not specified.\n',
    )
    actions: list[str] | None = Field(
        None, description='Action names this worker can execute.'
    )
    wait_seconds: int | None = Field(
        None,
        description='How long to hold the request open waiting for a job to\nsurface. 0 returns immediately.\n',
        ge=0,
        le=30,
    )


class JobClaim(BaseModel):
    job_id: str
    run_id: str
    namespace_id: str
    workflow_name: str
    step_name: str
    action: str
    parameters: dict[str, Any]
    attempt: int
    queue: str
    heartbeat_interval_seconds: int | None = None


class JobHeartbeatDirectives(BaseModel):
    should_cancel: bool | None = Field(
        False,
        description='When true the worker must stop processing and complete with status failed.',
    )


class JobHeartbeat(BaseModel):
    ok: bool
    directives: JobHeartbeatDirectives


class JobClaimDataResponse(BaseModel):
    data: JobClaim


class JobFenceRequest(BaseModel):
    worker_id: str
    attempt: int


class JobHeartbeatDataResponse(BaseModel):
    data: JobHeartbeat


class Status(Enum):
    completed = 'completed'
    failed = 'failed'


class JobCompleteRequest(BaseModel):
    worker_id: str
    attempt: int
    status: Status
    result_b64: str | None = None
    error_type: str | None = None
    error_message: str | None = None


class RunActionRequest(BaseModel):
    parameters: dict[str, Any] | None = None
    timeout_seconds: int | None = Field(None, ge=0)
    dry_run: bool | None = None


class RunActionResult(BaseModel):
    output: dict[str, Any] | list | str | float | int | bool


class RunActionResultDataResponse(BaseModel):
    data: RunActionResult


class Type2(Enum):
    member = 'member'
    agent = 'agent'
    group = 'group'


class ActorRef(BaseModel):
    type: Type2
    id: str = Field(
        ...,
        description='User ID for member; queue name for agent; group ID/slug for group',
    )


class InteractionType(Enum):
    approval = 'approval'
    review = 'review'
    input = 'input'


class InteractionSpecMode(Enum):
    """
    Declarative UI/input primitive for collecting the response. This is a
    portable rendering contract, not executable code.

    """

    confirm = 'confirm'
    select = 'select'
    multi_select = 'multi_select'
    input = 'input'


class InteractionOption(BaseModel):
    """
    Selectable option for `select` and `multi_select` modes.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: str
    label: str
    description: str | None = None


class InteractionSpec(BaseModel):
    """
    Declarative dialog contract for rendering and validating an interaction.
    `type` defines the semantic intent; `mode` defines the input affordance.
    Compatibility rules are enforced server-side:
    - `approval` requires `mode = confirm`
    - `review` requires `mode = select`
    - `input` supports `input`, `select`, or `multi_select`

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    mode: InteractionSpecMode
    options: list[InteractionOption] | None = Field(
        None, description='Required for `select` and `multi_select` modes.'
    )
    default_value: str | None = Field(
        None, description='Default selected option for `select` mode.'
    )
    default_values: list[str] | None = Field(
        None, description='Default selected options for `multi_select` mode.'
    )
    default_text: str | None = Field(
        None, description='Initial text value for `input` mode.'
    )
    default_confirmed: bool | None = Field(
        None, description='Initial yes/no value for `confirm` mode.'
    )
    placeholder: str | None = Field(
        None, description='Hint text shown for `input` mode.'
    )
    multiline: bool | None = Field(
        None, description='When true, render `input` mode as a multiline text area.'
    )


class CreateJobInteractionRequest(BaseModel):
    """
    Creates an interaction from a claimed job context. The server derives
    the owning run from the job and may derive the topic when omitted.

    """

    target_actor: ActorRef
    type: InteractionType
    message: str
    topic: str | None = Field(
        None,
        description='Optional signal topic override. When omitted, the server derives\nthe topic from step_name or falls back to a default interaction topic.\n',
    )
    step_name: str | None = Field(
        None, description='Optional workflow step label for UI/debugging context'
    )
    context: dict[str, Any] | None = None
    spec: InteractionSpec | None = None
    require_all: bool | None = Field(
        False,
        description='When target_actor.type is "group", setting require_all=true\nmeans all snapshotted group members must respond before the\ninteraction is considered complete. Ignored for non-group targets.\n',
    )
    timeout: str | None = Field(
        None,
        description='Optional duration string (e.g. "24h", "30m") specifying how long\nthe interaction should remain open before expiring. When absent\nthe caller is responsible for setting expires_at directly.\n',
    )
    expires_at: datetime | None = None


class InteractionValue(RootModel[dict[str, Any] | list | str | float | int | bool]):
    root: dict[str, Any] | list | str | float | int | bool = Field(
        ..., description='Free-form JSON payload supplied by the responder.'
    )


class InteractionResponse(BaseModel):
    value: InteractionValue
    comment: str | None = None
    at: datetime = Field(..., description='When the response was submitted')


class InteractionPartialResponse(BaseModel):
    user_id: str
    value: InteractionValue
    comment: str | None = None
    responded_at: datetime


class Status1(Enum):
    pending = 'pending'
    completed = 'completed'
    expired = 'expired'


class RoutingPolicySnapshot(Enum):
    """
    Group routing policy captured at creation time
    """

    first_responder = 'first_responder'
    all_members = 'all_members'


class Interaction(BaseModel):
    id: str
    org_id: str
    run_id: str | None = Field(
        None, description='Originating workflow run when the interaction is run-backed.'
    )
    topic: str | None = Field(
        None,
        description='Signal topic used to resume the originating run when run-backed.',
    )
    type: InteractionType
    status: Status1
    message: str | None = Field(
        None, description='Human-readable message shown to the responder'
    )
    context: dict[str, Any] | None = None
    spec: InteractionSpec | None = None
    target_actor: ActorRef
    responder_actor: ActorRef | None = None
    response: InteractionResponse | None = None
    expires_at: datetime | None = None
    completed_at: datetime | None = None
    created_at: datetime
    updated_at: datetime
    target_group_id: str | None = Field(
        None, description='Resolved group ID (set when target_actor.type = group)'
    )
    target_member_snapshot: list[str] | None = Field(
        None, description='User IDs of group members at the time of creation'
    )
    routing_policy_snapshot: RoutingPolicySnapshot | None = Field(
        None, description='Group routing policy captured at creation time'
    )
    require_all: bool | None = Field(
        None,
        description='When true, all snapshotted members must respond before completion',
    )
    claimed_by: str | None = Field(
        None,
        description='User ID of the member who claimed this interaction (first_responder only)',
    )
    claimed_at: datetime | None = None
    partial_responses: list[InteractionPartialResponse] | None = Field(
        None, description='Per-member responses for all_members routing'
    )


class InteractionDataResponse(BaseModel):
    data: Interaction


class TriggerKind(Enum):
    schedule = 'schedule'
    webhook = 'webhook'
    event = 'event'


class ConcurrencyPolicy(Enum):
    allow = 'allow'
    forbid = 'forbid'
    replace = 'replace'


class TriggerFireStatus(Enum):
    success = 'success'
    failed = 'failed'
    skipped = 'skipped'


class TriggerTarget(BaseModel):
    workflow_id: str
    condition: str | None = None
    input_mapping: dict[str, str] | None = None


class Trigger(BaseModel):
    id: str
    org_id: str
    namespace_id: str
    name: str
    kind: TriggerKind
    source_config: dict[str, Any] | None = None
    filter_config: dict[str, Any] | None = None
    targets: list[TriggerTarget] | None = None
    concurrency_policy: ConcurrencyPolicy
    enabled: bool
    last_fire_at: datetime | None = None
    next_fire_at: datetime | None = None
    created_by: str | None = None
    created_at: datetime
    updated_at: datetime


class TriggerDataResponse(BaseModel):
    data: Trigger


class TriggerListResponse(BaseModel):
    data: list[Trigger]
    next_cursor: str | None = None
    has_more: bool


class TriggerFire(BaseModel):
    id: str
    org_id: str
    trigger_id: str
    scheduled_at: datetime | None = None
    fired_at: datetime
    run_id: str | None = None
    status: TriggerFireStatus
    error: str | None = None
    dedup_key: str | None = None
    created_at: datetime


class TriggerFireListResponse(BaseModel):
    data: list[TriggerFire]
    next_cursor: str | None = None
    has_more: bool


class CreateTriggerRequest(BaseModel):
    name: str
    kind: TriggerKind
    source_config: dict[str, Any] | None = None
    filter_config: dict[str, Any] | None = None
    targets: list[TriggerTarget] | None = None
    concurrency_policy: ConcurrencyPolicy | None = None
    enabled: bool | None = None


class UpdateTriggerRequest(BaseModel):
    name: str | None = None
    source_config: dict[str, Any] | None = None
    filter_config: dict[str, Any] | None = None
    targets: list[TriggerTarget] | None = None
    concurrency_policy: ConcurrencyPolicy | None = None
    enabled: bool | None = None


class Worker(BaseModel):
    worker_id: str
    name: str | None = None
    version: str | None = None
    last_seen_at: datetime | None = None
    capabilities: list[str] | None = None
    stale: bool


class WorkerListResponse(BaseModel):
    data: list[Worker]


class Namespace(BaseModel):
    id: str
    name: str
    slug: str
    description: str | None = None
    created_by: str | None = None
    created_at: datetime
    updated_at: datetime


class NamespaceDataResponse(BaseModel):
    data: Namespace


class NamespaceListResponse(BaseModel):
    data: list[Namespace]


class CreateNamespaceRequest(BaseModel):
    name: str
    slug: str | None = None
    description: str | None = None


class UpdateNamespaceRequest(BaseModel):
    name: str | None = None
    description: str | None = None


class WebhookEventStatus(Enum):
    pending = 'pending'
    acknowledged = 'acknowledged'
    failed = 'failed'
    expired = 'expired'


class Webhook(BaseModel):
    """
    A managed inbound webhook endpoint hosted by Mobius.

    """

    id: str
    org_id: str
    namespace_id: str
    name: str
    slug: str = Field(
        ..., description='Immutable URL-safe identifier used in the receive endpoint'
    )
    receive_url: str = Field(
        ...,
        description='Full URL that external systems POST to when sending inbound webhook events to Mobius.',
    )
    enabled: bool
    created_by: str | None = None
    created_at: datetime
    updated_at: datetime


class WebhookDataResponse(BaseModel):
    data: Webhook


class WebhookListResponse(BaseModel):
    data: list[Webhook]
    next_cursor: str | None = None
    has_more: bool


class WebhookEvent(BaseModel):
    """
    One inbound HTTP request received by a managed webhook endpoint.

    """

    id: str
    org_id: str
    webhook_id: str
    payload: dict[str, Any] | None = None
    status: WebhookEventStatus
    received_at: datetime
    acknowledged_at: datetime | None = None
    expires_at: datetime | None = None


class WebhookEventListResponse(BaseModel):
    data: list[WebhookEvent]
    next_cursor: str | None = None
    has_more: bool


class CreateWebhookRequest(BaseModel):
    name: str
    slug: str | None = Field(
        None, description='URL-safe slug; auto-generated from name if omitted'
    )
    secret: str | None = Field(
        None,
        description='Shared secret associated with the webhook. Stored as a hash and not returned after creation.',
    )
    enabled: bool | None = None


class UpdateWebhookRequest(BaseModel):
    name: str | None = None
    secret: str | None = Field(
        None, description="Replace or clear the webhook's shared secret"
    )
    enabled: bool | None = None


class IntegrationStatus(Enum):
    active = 'active'
    inactive = 'inactive'
    expired = 'expired'


class Integration(BaseModel):
    id: str
    org_id: str
    name: str
    provider: str
    config: dict[str, Any] | None = None
    status: IntegrationStatus
    created_by: str | None = None
    created_at: datetime
    updated_at: datetime


class IntegrationDataResponse(BaseModel):
    data: Integration


class IntegrationListResponse(BaseModel):
    data: list[Integration]
    next_cursor: str | None = None
    has_more: bool


class CreateIntegrationRequest(BaseModel):
    name: str
    provider: str
    config: dict[str, Any] | None = None


class UpdateIntegrationRequest(BaseModel):
    name: str | None = None
    config: dict[str, Any] | None = None
    status: IntegrationStatus | None = None


class BillingSubscription(BaseModel):
    id: str
    org_id: str
    plan_type: str
    status: str
    seat_count: int
    current_period_start: datetime
    current_period_end: datetime
    trial_ends_at: datetime | None = None
    grace_ends_at: datetime | None = None
    trial_days_remaining: int
    trial_warning: bool
    monthly_credit_cap: int
    per_run_step_cap: int
    alert_thresholds_percent: list[int]
    cancel_at_period_end: bool
    created_at: datetime
    updated_at: datetime


class BillingSubscriptionDataResponse(BaseModel):
    data: BillingSubscription


class BillingPlan(BaseModel):
    plan_type: str
    price_cents: int
    included_credits: int
    seat_limit: int
    default_monthly_credit_cap: int
    default_per_run_step_cap: int
    max_alert_thresholds: int
    trial_days: int
    credit_card_required: bool


class BillingPlanListResponse(BaseModel):
    data: list[BillingPlan]


class BillingUsageKeySummary(BaseModel):
    api_key_id: str
    count: int


class BillingUsageSummary(BaseModel):
    current_period_start: datetime
    current_period_end: datetime
    current_usage: int
    included_limit: int
    overage_calls: int
    overage_cost: int
    by_category: dict[str, int]
    by_api_key: list[BillingUsageKeySummary]


class BillingUsageDataResponse(BaseModel):
    data: BillingUsageSummary


class Invoice(BaseModel):
    id: str
    status: str
    currency: str
    amount_due: int
    amount_paid: int
    hosted_invoice_url: AnyUrl | None = None
    invoice_pdf: AnyUrl | None = None
    created_at: datetime


class InvoiceListResponse(BaseModel):
    data: list[Invoice]


class CreateCheckoutRequest(BaseModel):
    success_url: AnyUrl
    cancel_url: AnyUrl


class CreatePortalRequest(BaseModel):
    return_url: AnyUrl


class BillingURLResult(BaseModel):
    url: AnyUrl


class BillingURLResultDataResponse(BaseModel):
    data: BillingURLResult


class UpdateBillingLimitsRequest(BaseModel):
    monthly_credit_cap: int | None = None
    per_run_step_cap: int | None = None
    alert_thresholds_percent: list[int] | None = None


class OnboardingStatus(BaseModel):
    completed: bool = Field(
        ..., description='Whether the user has completed onboarding and has an org'
    )
    org_id: str | None = Field(
        None, description="The user's org ID (present only when completed is true)"
    )
    org_name: str | None = Field(
        None,
        description="The user's org display name (present only when completed is true)",
    )


class OnboardingStatusDataResponse(BaseModel):
    data: OnboardingStatus


class OnboardingResult(BaseModel):
    org_id: str = Field(..., description='ID of the newly created (or existing) org')
    org_name: str = Field(..., description='Display name of the org')


class OnboardingResultDataResponse(BaseModel):
    data: OnboardingResult


class AdminMetrics(BaseModel):
    generated_at: datetime
    window_minutes: int
    runs_per_minute: float
    total_runs_window: int
    failure_rate: float
    avg_run_seconds: float
    p95_step_seconds: float
    queue_depth: int
    running_count: int
    active_workers: int
    stale_workers: int
    status_breakdown: dict[str, int]
    live_subscribers: int


class AdminMetricsDataResponse(BaseModel):
    data: AdminMetrics


class AdminWorker(BaseModel):
    worker_id: str
    name: str | None = None
    version: str | None = None
    last_seen_at: datetime | None = None
    capabilities: list[str] | None = None
    stale: bool


class AdminWorkerListResponse(BaseModel):
    data: list[AdminWorker]


class AuthContext(BaseModel):
    user_id: str
    org_id: str | None = None
    role: str | None = Field(
        None,
        description='Org member role (owner, admin, member) — empty for API-key auth',
    )
    auth_type: str = Field(
        ..., description='How the caller authenticated (clerk, api_key, cli_token)'
    )
    is_admin: bool


class AuthContextDataResponse(BaseModel):
    data: AuthContext


class PreviewPermissionsRequest(BaseModel):
    service_account_default_role: str | None = Field(
        None,
        description='Role name to assign by default to service accounts without existing assignments.',
    )


class ActorType(Enum):
    user = 'user'
    service_account = 'service_account'


class PermissionsAssignmentInput(BaseModel):
    actor_type: ActorType
    actor_id: str
    role_id: str | None = None
    role_name: str | None = None
    namespace_id: str | None = None


class PermissionsAssignmentProposal(BaseModel):
    actor_type: ActorType
    actor_id: str
    role_id: str
    role_name: str
    namespace_id: str | None = None


class PermissionsPlan(BaseModel):
    permissions_enabled: bool
    assignments: list[PermissionsAssignmentProposal]


class PermissionsPlanDataResponse(BaseModel):
    data: PermissionsPlan


class PermissionsState(BaseModel):
    permissions_enabled: bool


class PermissionsStateDataResponse(BaseModel):
    data: PermissionsState


class Role2(BaseModel):
    id: str
    org_id: str | None = None
    name: str
    description: str
    permissions: list[str]
    system_defined: bool
    created_at: datetime
    updated_at: datetime


class RoleAssignment(BaseModel):
    id: str
    org_id: str
    actor_type: ActorType
    actor_id: str
    role_id: str
    role_name: str
    namespace_id: str | None = None
    granted_by_actor_type: str | None = None
    granted_by_actor_id: str | None = None
    created_at: datetime


class RoleDataResponse(BaseModel):
    data: Role2


class RoleListResponse(BaseModel):
    data: list[Role2]


class RoleAssignmentDataResponse(BaseModel):
    data: RoleAssignment


class RoleAssignmentListResponse(BaseModel):
    data: list[RoleAssignment]


class CreateRoleRequest(BaseModel):
    name: str
    description: str | None = None
    permissions: list[str]


class UpdateRoleRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    permissions: list[str] | None = None


class CreateRoleAssignmentRequest(BaseModel):
    actor_type: ActorType
    actor_id: str
    role_id: str | None = None
    role_name: str | None = None
    namespace_id: str | None = None


class User(BaseModel):
    id: str
    email: str
    first_name: str | None = None
    last_name: str | None = None
    avatar_url: str | None = None
    created_at: datetime
    updated_at: datetime


class UserDataResponse(BaseModel):
    data: User


class Org(BaseModel):
    id: str
    name: str
    slug: str
    metadata: dict[str, Any] | None = None
    created_at: datetime
    updated_at: datetime


class OrgDataResponse(BaseModel):
    data: Org


class OrgListResponse(BaseModel):
    data: list[Org]
    has_more: bool | None = None
    next_cursor: str | None = None


class CreateOrgRequest(BaseModel):
    name: str
    slug: str
    metadata: dict[str, Any] | None = None


class UpdateOrgRequest(BaseModel):
    name: str | None = None
    slug: str | None = None
    metadata: dict[str, Any] | None = None


class Role3(Enum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class OrgMember(BaseModel):
    id: str
    org_id: str
    user_id: str
    role: Role3
    created_at: datetime
    updated_at: datetime
    user: User | None = None


class OrgMemberDataResponse(BaseModel):
    data: OrgMember


class OrgMemberListResponse(BaseModel):
    data: list[OrgMember]
    has_more: bool | None = None
    next_cursor: str | None = None


class AddOrgMemberRequest(BaseModel):
    user_id: str
    role: Role3


class UpdateOrgMemberRoleRequest(BaseModel):
    role: Role3


class InteractionListResponse(BaseModel):
    data: list[Interaction]


class CreateInteractionRequest(BaseModel):
    """
    Creates an interaction directly. When `run_id` is provided, `topic` is
    also required and the interaction is linked to that run. When both are
    omitted, the interaction is standalone and completes with no workflow
    resume side effect. For worker/job usage, prefer the job-scoped route
    so the server can derive the owning run from the claimed job context.

    """

    run_id: str | None = None
    topic: str | None = Field(
        None,
        description='Signal topic the interaction will complete against when run-backed.',
    )
    target_actor: ActorRef
    type: InteractionType
    message: str
    context: dict[str, Any] | None = None
    spec: InteractionSpec | None = None
    require_all: bool | None = Field(
        False,
        description='When target_actor.type is "group", setting require_all=true\nmeans all snapshotted group members must respond before the\ninteraction is considered complete. Ignored for non-group targets.\n',
    )
    expires_at: datetime | None = None


class RespondToInteractionRequest(BaseModel):
    value: InteractionValue | None = None
    comment: str | None = None


class SlackInstall(BaseModel):
    authorize_url: str = Field(
        ..., description='The Slack OAuth authorize URL to redirect the user to.'
    )


class SlackInstallDataResponse(BaseModel):
    data: SlackInstall


class RoutingPolicy(Enum):
    """
    How interactions are dispatched to members
    """

    first_responder = 'first_responder'
    all_members = 'all_members'


class Group(BaseModel):
    id: str
    org_id: str
    slug: str = Field(..., description='URL-safe identifier, unique within the org')
    name: str = Field(..., description='Human-readable display name')
    description: str | None = None
    routing_policy: RoutingPolicy = Field(
        ..., description='How interactions are dispatched to members'
    )
    created_at: datetime
    updated_at: datetime


class GroupDataResponse(BaseModel):
    data: Group


class GroupListResponse(BaseModel):
    data: list[Group]


class GroupWithCount(Group):
    member_count: int = Field(..., description='Current number of members')


class GroupWithCountDataResponse(BaseModel):
    data: GroupWithCount


class GroupWithCountListResponse(BaseModel):
    data: list[GroupWithCount]
    has_more: bool | None = None
    next_cursor: str | None = None


class GroupMember(BaseModel):
    id: str
    group_id: str
    org_id: str
    user_id: str
    added_by: str | None = None
    added_at: datetime


class GroupMemberDataResponse(BaseModel):
    data: GroupMember


class GroupMemberListResponse(BaseModel):
    data: list[GroupMember]
    has_more: bool | None = None
    next_cursor: str | None = None


class RoutingPolicy1(Enum):
    first_responder = 'first_responder'
    all_members = 'all_members'


class CreateGroupRequest(BaseModel):
    slug: str | None = Field(
        None, description='URL-safe slug. Auto-derived from name if omitted.'
    )
    name: str = Field(..., description='Display name (1-64 chars)')
    description: str | None = None
    routing_policy: RoutingPolicy1 | None = 'first_responder'


class UpdateGroupRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    routing_policy: RoutingPolicy1 | None = 'first_responder'


class AddGroupMemberRequest(BaseModel):
    user_id: str = Field(..., description='Org member user ID to add')


class AgentStatus(Enum):
    active = 'active'
    inactive = 'inactive'


class AgentPresence(Enum):
    online = 'online'
    offline = 'offline'
    stale = 'stale'


class AgentSessionStatus(Enum):
    connected = 'connected'
    disconnected = 'disconnected'
    stale = 'stale'


class Agent(BaseModel):
    id: str
    org_id: str
    namespace_id: str
    service_account_id: str
    name: str
    display_name: str
    description: str | None = None
    kind: str | None = None
    capabilities: dict[str, Any] | None = None
    config: dict[str, Any] | None = None
    status: AgentStatus
    presence: AgentPresence
    created_at: datetime
    updated_at: datetime


class AgentSession(BaseModel):
    id: str
    org_id: str
    namespace_id: str
    agent_id: str
    status: AgentSessionStatus
    transport: str
    metadata: dict[str, Any] | None = None
    connected_at: datetime | None = None
    last_seen_at: datetime | None = None
    disconnected_at: datetime | None = None
    created_at: datetime
    updated_at: datetime


class AgentDataResponse(BaseModel):
    data: Agent


class AgentListResponse(BaseModel):
    data: list[Agent]


class AgentSessionDataResponse(BaseModel):
    data: AgentSession


class AgentSessionListResponse(BaseModel):
    data: list[AgentSession]


class CreateAgentRequest(BaseModel):
    service_account_id: str
    name: str
    display_name: str | None = None
    description: str | None = None
    kind: str | None = None
    capabilities: dict[str, Any] | None = None
    config: dict[str, Any] | None = None


class UpdateAgentRequest(BaseModel):
    display_name: str | None = None
    description: str | None = None
    kind: str | None = None
    capabilities: dict[str, Any] | None = None
    config: dict[str, Any] | None = None
    status: AgentStatus | None = None


class CreateAgentSessionRequest(BaseModel):
    transport: str
    metadata: dict[str, Any] | None = None


class ServiceAccountStatus(Enum):
    active = 'active'
    disabled = 'disabled'


class ServiceAccount(BaseModel):
    id: str
    org_id: str
    name: str
    display_name: str
    description: str | None = None
    status: ServiceAccountStatus
    owner_user_id: str | None = None
    metadata: dict[str, Any] | None = None
    created_at: datetime
    updated_at: datetime


class ServiceAccountDataResponse(BaseModel):
    data: ServiceAccount


class ServiceAccountListResponse(BaseModel):
    data: list[ServiceAccount]


class CreateServiceAccountRequest(BaseModel):
    name: str
    display_name: str | None = None
    description: str | None = None
    owner_user_id: str | None = None
    metadata: dict[str, Any] | None = None
    role_id: str | None = None
    role_name: str | None = None
    namespace_id: str | None = None


class UpdateServiceAccountRequest(BaseModel):
    display_name: str | None = None
    description: str | None = None
    status: ServiceAccountStatus | None = None
    owner_user_id: str | None = None
    metadata: dict[str, Any] | None = None


class ToolDefinition(BaseModel):
    name: str = Field(
        ...,
        description='Tool name (workflow slug). Stable across publish/unpublish cycles.',
    )
    description: str = Field(
        ..., description='Human-readable description of what the tool does.'
    )
    input_schema: dict[str, Any] = Field(
        ..., description='JSON Schema Draft 7 object describing the tool inputs.'
    )


class ToolDefinitionListResponse(BaseModel):
    data: list[ToolDefinition]


class ToolRunRequest(BaseModel):
    input: dict[str, Any] | None = Field(
        None, description="Input values matching the tool's input_schema."
    )
    timeout_seconds: int | None = Field(
        None,
        description='How long (in seconds) to wait for synchronous completion.\nDefault 30, max 120. If the run does not complete within this\nwindow the response is 202 with status pending.\n',
        ge=1,
        le=120,
    )


class Status2(Enum):
    """
    Run status — "pending", "running", "completed", or "failed".
    """

    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    suspended = 'suspended'


class ToolRun(BaseModel):
    run_id: str = Field(..., description='Unique run identifier for polling.')
    status: Status2 = Field(
        ..., description='Run status — "pending", "running", "completed", or "failed".'
    )
    output: dict[str, Any] | None = Field(
        None, description='Run output. Present when status is "completed".'
    )
    error: str | None = Field(
        None, description='Error message. Present when status is "failed".'
    )


class ToolRunDataResponse(BaseModel):
    data: ToolRun


class WorkflowStepBase(BaseModel):
    name: str
    description: str | None = None
    next: list[WorkflowEdge] | None = None
    edge_matching_strategy: WorkflowEdgeMatchingStrategy | None = None
    each: WorkflowEach | None = None


class WorkflowExecutableStep(WorkflowStepBase):
    action: str = Field(
        ...,
        description='Canonical executable-step field.\nWhen `action_kind` is omitted, the engine treats this as a worker action.\nUse `action_kind: server` for Mobius-managed server actions.\n',
    )
    action_kind: WorkflowActionKind | None = None
    store: str | None = None
    parameters: dict[str, Any] | None = None
    retry: list[WorkflowRetry] | None = None
    catch: list[WorkflowCatch] | None = None


class WorkflowJoinStep(WorkflowStepBase):
    join: WorkflowJoinConfig


class WorkflowWaitSignalStep(WorkflowStepBase):
    wait_signal: WorkflowWaitSignalConfig


class WorkflowSleepStep(WorkflowStepBase):
    sleep: WorkflowSleepConfig


class WorkflowPauseStep(WorkflowStepBase):
    pause: WorkflowPauseConfig


class WorkflowInteractionSpec(BaseModel):
    """
    Declarative interaction UI contract embedded in a workflow definition.
    This mirrors the persisted interaction spec used at runtime and is
    intentionally portable across web, email, and agent experiences.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Mode
    options: list[WorkflowInteractionOption] | None = Field(
        None, description='Required for `select` and `multi_select` modes.'
    )
    default_value: str | None = Field(
        None, description='Default selected option for `select` mode.'
    )
    default_values: list[str] | None = Field(
        None, description='Default selected options for `multi_select` mode.'
    )
    default_text: str | None = Field(
        None, description='Initial text value for `input` mode.'
    )
    default_confirmed: bool | None = Field(
        None, description='Initial yes/no value for `confirm` mode.'
    )
    placeholder: str | None = Field(
        None, description='Hint text shown for `input` mode.'
    )
    multiline: bool | None = Field(
        None, description='When true, render `input` mode as a multiline text area.'
    )


class WorkflowRunDetail(WorkflowRun):
    result_b64: str | None = Field(
        None, description='Base64-encoded terminal result blob'
    )
    jobs: list[Job] | None = None


class WorkflowRunDetailDataResponse(BaseModel):
    data: WorkflowRunDetail


class EnablePermissionsRequest(BaseModel):
    service_account_default_role: str | None = Field(
        None,
        description='Fallback role name for service accounts when assignments are omitted.',
    )
    assignments: list[PermissionsAssignmentInput] | None = None


class WorkflowInteractionConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    message: str
    context: dict[str, Any] | None = None
    spec: WorkflowInteractionSpec | None = None
    timeout: str = Field(..., description='Go duration string.')
    target: WorkflowInteractionTarget


class WorkflowInteractionStep(WorkflowStepBase):
    interaction: WorkflowInteractionConfig


class WorkflowStep(
    RootModel[
        WorkflowExecutableStep
        | WorkflowJoinStep
        | WorkflowWaitSignalStep
        | WorkflowSleepStep
        | WorkflowPauseStep
        | WorkflowInteractionStep
    ]
):
    root: (
        WorkflowExecutableStep
        | WorkflowJoinStep
        | WorkflowWaitSignalStep
        | WorkflowSleepStep
        | WorkflowPauseStep
        | WorkflowInteractionStep
    ) = Field(
        ..., description='A workflow step. Exactly one step shape should be used.\n'
    )


class WorkflowSpec(BaseModel):
    """
    Workflow definition shaped like `workflow.Options`.

    Authoring rule: `action` is the canonical field for executable steps.
    When `action_kind` is omitted, `action` uses worker/job semantics.
    Use `action_kind: "server"` for Mobius-managed server actions such as
    platform integrations or custom HTTP-backed actions.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Workflow name.')
    description: str | None = None
    start_at: str | None = Field(
        None,
        description='Step name to start execution from. Defaults to the first step.',
    )
    inputs: list[WorkflowInput] | None = None
    outputs: list[WorkflowOutput] | None = None
    state: dict[str, Any] | None = Field(None, description='Initial workflow state.')
    steps: list[WorkflowStep]


class WorkflowDefinition(BaseModel):
    id: str
    namespace_id: str | None = None
    queue: str | None = Field(
        None, description='Default queue name for runs of this workflow.'
    )
    name: str
    slug: str
    description: str | None = None
    latest_version: int
    published_as_tool: bool | None = Field(
        None,
        description='When true, this workflow is exposed as a callable tool via /api/tools.',
    )
    spec: WorkflowSpec | None = None
    created_by: str
    created_at: datetime
    updated_at: datetime


class WorkflowDefinitionDataResponse(BaseModel):
    data: WorkflowDefinition


class WorkflowDefinitionListResponse(BaseModel):
    data: list[WorkflowDefinition]
    next_cursor: str | None = None
    has_more: bool


class CreateWorkflowRequest(BaseModel):
    name: str
    slug: str | None = None
    description: str | None = None
    namespace_id: str | None = None
    queue: str | None = Field(
        None,
        description='Default queue for runs of this workflow. Defaults to "default".',
    )
    published_as_tool: bool | None = Field(
        None,
        description='When true, expose this workflow as a callable tool via /api/tools.',
    )
    spec: WorkflowSpec


class UpdateWorkflowRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    queue: str | None = None
    published_as_tool: bool | None = Field(
        None,
        description='When true, expose this workflow as a callable tool via /api/tools.',
    )
    spec: WorkflowSpec | None = None


class WorkflowVersion(BaseModel):
    id: str
    version: int
    spec: WorkflowSpec
    created_by: str
    created_at: datetime


class WorkflowVersionListResponse(BaseModel):
    data: list[WorkflowVersion]
