// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerApiKeysCommands registers every generated subcommand in the "api-keys" group.
func registerApiKeysCommands(app *cli.App) {
	apiKeysGrp := app.Group("api-keys").Description("API keys scoped to a single project")
	apiKeysGrp.Alias("api-key")
	apiKeysGrp.Command("create").
		Description("Create API key").
		Flags(
			cli.String("expires-at", "").Help("Optional hard expiry. Omit for a non-expiring key. Accepts JSON, @file, or @-."),
			cli.String("name", "").Help("[required] Human-readable label, unique within the project."),
			cli.String("principal-id", "").Help("[required] Principal this key authenticates as."),
			cli.String("scope-role-id", "").Help("Optional role whose permissions cap this key below its principal's full grants."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateAPIKeyJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("expires-at") {
				if err := decodeFlagJSON(ctx, "expires-at", ctx.String("expires-at"), &body.ExpiresAt); err != nil {
					return err
				}
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("principal-id") {
				body.PrincipalId = ctx.String("principal-id")
			}
			if ctx.IsSet("scope-role-id") {
				v := ctx.String("scope-role-id")
				body.ScopeRoleId = &v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if body.PrincipalId == "" {
				return fmt.Errorf("--principal-id is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateAPIKeyWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createAPIKey", resp.StatusCode(), resp.Body)
		})

	apiKeysGrp.Command("delete").
		Description("Delete API key").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteAPIKeyWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteAPIKey", resp.StatusCode(), resp.Body)
		})

	apiKeysGrp.Command("get").
		Description("Get API key").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetAPIKeyWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getAPIKey", resp.StatusCode(), resp.Body)
		})

	apiKeysGrp.Command("list").
		Description("List API keys").
		Flags(
			cli.Int("limit", "").Help("Maximum number of items to return"),
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListAPIKeysParams{}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			resp, err := client.ListAPIKeysWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAPIKeys", resp.StatusCode(), resp.Body)
		})

}
