// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerSecretsCommands registers every generated subcommand in the "secrets" group.
func registerSecretsCommands(app *cli.App) {
	secretsGrp := app.Group("secrets").Description("Project secrets and secret versions")
	secretsGrp.Alias("secret")
	secretsGrp.Command("create").
		Description("Create a secret").
		Flags(
			cli.String("description", "").Help("Optional human-readable description."),
			cli.String("name", "").Help("[required] Project-scoped secret name."),
			cli.String("values", "").Help("[required] JSON key/value payload encrypted as a SecretVersion. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateSecretJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("values") {
				if err := decodeFlagJSON(ctx, "values", ctx.String("values"), &body.Values); err != nil {
					return err
				}
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.String("file") == "" && !ctx.IsSet("values") {
				return fmt.Errorf("--values is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "values")
			}
			resp, err := client.CreateSecretWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createSecret", resp.StatusCode(), resp.Body)
		})

	secretsGrp.Command("delete").
		Description("Delete a secret").
		AddArg(&cli.Arg{Name: "secret", Description: "Secret ID or project-scoped secret name.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteSecretWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteSecret", resp.StatusCode(), resp.Body)
		})

	secretsGrp.Command("get").
		Description("Get a secret").
		AddArg(&cli.Arg{Name: "secret", Description: "Secret ID or project-scoped secret name.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetSecretWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getSecret", resp.StatusCode(), resp.Body)
		})

	secretsGrp.Command("get-version").
		Description("Get secret version metadata").
		AddArg(&cli.Arg{Name: "secret", Description: "Secret ID or project-scoped secret name.", Required: true}).
		AddArg(&cli.Arg{Name: "version", Description: "Secret version number or `latest`.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.GetSecretVersionWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getSecretVersion", resp.StatusCode(), resp.Body)
		})

	secretsGrp.Command("list").
		Description("List secrets").
		Flags(
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
			cli.Int("limit", "").Help("Maximum number of items to return"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListSecretsParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListSecretsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listSecrets", resp.StatusCode(), resp.Body)
		})

	secretsGrp.Command("list-versions").
		Description("List secret versions").
		AddArg(&cli.Arg{Name: "secret", Description: "Secret ID or project-scoped secret name.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ListSecretVersionsWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listSecretVersions", resp.StatusCode(), resp.Body)
		})

	secretsGrp.Command("update").
		Description("Update a secret").
		AddArg(&cli.Arg{Name: "secret", Description: "Secret ID or project-scoped secret name.", Required: true}).
		Flags(
			cli.String("description", "").Help("Replacement description."),
			cli.String("values", "").Help("JSON key/value payload encrypted as a SecretVersion. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateSecretJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("values") {
				if err := decodeFlagJSON(ctx, "values", ctx.String("values"), &body.Values); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("description") && !ctx.IsSet("values") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "values")
			}
			resp, err := client.UpdateSecretWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateSecret", resp.StatusCode(), resp.Body)
		})

}
