// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerJobsCommands registers every generated subcommand in the "jobs" group.
func registerJobsCommands(app *cli.App) {
	jobsGrp := app.Group("jobs").Description("Worker runtime — claim, heartbeat, complete")
	jobsGrp.Alias("job")
	jobsGrp.Command("claim").
		Description("Long-poll for the next claimable workflow job").
		Flags(
			cli.Strings("actions", "").Help("Action names this worker can execute. When provided, only jobs whose `spec.kind == \"action\"` and wh…"),
			cli.Int("concurrency-limit", "").Help("[required] Maximum number of concurrent in-flight jobs this worker process intends to hold. Recorded on the wo…"),
			cli.Strings("handlers", "").Help("Code handler IDs this worker has registered. When provided, only jobs whose `spec.kind == \"code\"` a…"),
			cli.Strings("queues", "").Help("Queue names the worker subscribes to. When empty the worker claims from any queue in the project. W…"),
			cli.Int("wait-seconds", "").Help("How long to hold the request open waiting for a job to surface. 0 returns immediately. Capped at 30…"),
			cli.String("worker-instance-id", "").Help("[required] Caller-configured stable identifier for the worker process. The SDK auto-detects this on Cloud Run,…"),
			cli.String("worker-name", "").Help("Optional human-readable name shown in the worker list."),
			cli.String("worker-session-token", "").Help("[required] Per-boot token generated by the SDK on Worker construction. Stamped onto the claimed job and folded…"),
			cli.String("worker-version", "").Help("Optional version string shown in the worker list."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.ClaimJobJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("actions") {
				v := ctx.Strings("actions")
				body.Actions = &v
			}
			if ctx.IsSet("concurrency-limit") {
				body.ConcurrencyLimit = ctx.Int("concurrency-limit")
			}
			if ctx.IsSet("handlers") {
				v := ctx.Strings("handlers")
				body.Handlers = &v
			}
			if ctx.IsSet("queues") {
				v := ctx.Strings("queues")
				body.Queues = &v
			}
			if ctx.IsSet("wait-seconds") {
				v := ctx.Int("wait-seconds")
				body.WaitSeconds = &v
			}
			if ctx.IsSet("worker-instance-id") {
				body.WorkerInstanceId = ctx.String("worker-instance-id")
			}
			if ctx.IsSet("worker-name") {
				v := ctx.String("worker-name")
				body.WorkerName = &v
			}
			if ctx.IsSet("worker-session-token") {
				body.WorkerSessionToken = ctx.String("worker-session-token")
			}
			if ctx.IsSet("worker-version") {
				v := ctx.String("worker-version")
				body.WorkerVersion = &v
			}
			if body.ConcurrencyLimit == 0 {
				return fmt.Errorf("--concurrency-limit is required (or supply it via --file)")
			}
			if body.WorkerInstanceId == "" {
				return fmt.Errorf("--worker-instance-id is required (or supply it via --file)")
			}
			if body.WorkerSessionToken == "" {
				return fmt.Errorf("--worker-session-token is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.ClaimJobWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "claimJob", resp.StatusCode(), resp.Body)
		})

	jobsGrp.Command("create-interaction").
		Description("Create a human-in-the-loop interaction from a claimed workflow job").
		Args("id").
		Flags(
			cli.String("context", "").Help("Additional key-value context surfaced in the UI alongside the message. Accepts JSON, @file, or @-."),
			cli.String("expires-at", "").Help("Timestamp after which this interaction expires. Accepts JSON, @file, or @-."),
			cli.String("kind", "").Help("[required] Protocol kind of the interaction (PRD 077). Each value names a distinct multi-party coordination pr…"),
			cli.String("message", "").Help("[required] Message shown to the responder."),
			cli.String("properties", "").Help("Free-form structured metadata to attach to the interaction. Accepts JSON, @file, or @-."),
			cli.String("references", "").Help("Supporting links and related entities. Accepts JSON, @file, or @-."),
			cli.Bool("require-all", "").Help("When `target_group_id` is set, setting require_all=true means all snapshotted group members must re…"),
			cli.String("resolution-policy", "").Help("Declarative resolution rule attached to an Interaction. Determines how participant responses become… Accepts JSON, @file, or @-."),
			cli.String("signal-name", "").Help("Optional signal name override. When omitted, the server derives the signal name from step_name or f…"),
			cli.String("spec", "").Help("Declarative dialog contract for rendering and validating an interaction. Used at both authoring tim… Accepts JSON, @file, or @-."),
			cli.String("step-name", "").Help("Optional workflow step label for UI/debugging context"),
			cli.String("subject", "").Help("Pointer to the work item, artifact, external ticket, or Mobius entity this interaction is about. Accepts JSON, @file, or @-."),
			cli.String("submission-review-policy", "").Help("Reviewability policy for an interaction artifact (PRD 077 §3.5). Carried as a template on `Interac… Accepts JSON, @file, or @-."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("target", "").Help("[required] Identifies who should receive an interaction request. Humans and agents are both users; agent targe… Accepts JSON, @file, or @-."),
			cli.String("timeout", "").Help("Optional duration string (e.g. \"24h\", \"30m\") specifying how long the interaction should remain open…"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.CreateJobInteractionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("context") {
				if err := decodeFlagJSON(ctx, "context", ctx.String("context"), &body.Context); err != nil {
					return err
				}
			}
			if ctx.IsSet("expires-at") {
				if err := decodeFlagJSON(ctx, "expires-at", ctx.String("expires-at"), &body.ExpiresAt); err != nil {
					return err
				}
			}
			if ctx.IsSet("kind") {
				body.Kind = api.InteractionKind(ctx.String("kind"))
			}
			if ctx.IsSet("message") {
				body.Message = ctx.String("message")
			}
			if ctx.IsSet("properties") {
				if err := decodeFlagJSON(ctx, "properties", ctx.String("properties"), &body.Properties); err != nil {
					return err
				}
			}
			if ctx.IsSet("references") {
				if err := decodeFlagJSON(ctx, "references", ctx.String("references"), &body.References); err != nil {
					return err
				}
			}
			if ctx.IsSet("require-all") {
				v := ctx.Bool("require-all")
				body.RequireAll = &v
			}
			if ctx.IsSet("resolution-policy") {
				if err := decodeFlagJSON(ctx, "resolution-policy", ctx.String("resolution-policy"), &body.ResolutionPolicy); err != nil {
					return err
				}
			}
			if ctx.IsSet("signal-name") {
				v := ctx.String("signal-name")
				body.SignalName = &v
			}
			if ctx.IsSet("spec") {
				if err := decodeFlagJSON(ctx, "spec", ctx.String("spec"), &body.Spec); err != nil {
					return err
				}
			}
			if ctx.IsSet("step-name") {
				v := ctx.String("step-name")
				body.StepName = &v
			}
			if ctx.IsSet("subject") {
				if err := decodeFlagJSON(ctx, "subject", ctx.String("subject"), &body.Subject); err != nil {
					return err
				}
			}
			if ctx.IsSet("submission-review-policy") {
				if err := decodeFlagJSON(ctx, "submission-review-policy", ctx.String("submission-review-policy"), &body.SubmissionReviewPolicy); err != nil {
					return err
				}
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("target") {
				if err := decodeFlagJSON(ctx, "target", ctx.String("target"), &body.Target); err != nil {
					return err
				}
			}
			if ctx.IsSet("timeout") {
				v := ctx.String("timeout")
				body.Timeout = &v
			}
			if body.Kind == "" {
				return fmt.Errorf("--kind is required (or supply it via --file)")
			}
			if body.Message == "" {
				return fmt.Errorf("--message is required (or supply it via --file)")
			}
			if ctx.String("file") == "" && !ctx.IsSet("target") {
				return fmt.Errorf("--target is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateJobInteractionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createJobInteraction", resp.StatusCode(), resp.Body)
		})

	jobsGrp.Command("emit-job-events").
		Description("Emit one or more custom events from a claimed workflow job").
		Args("id").
		Flags(
			cli.String("events", "").Help("[required] The batch of events to publish. All events are validated atomically. Accepts JSON, @file, or @-."),
			cli.String("lease-token", "").Help("[required] Opaque lease fence value from the claim; mismatch returns 409 lease-lost."),
			cli.String("worker-instance-id", "").Help("Echo of the claim's `worker_instance_id`. Audit only."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.EmitJobEventsJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("events") {
				if err := decodeFlagJSON(ctx, "events", ctx.String("events"), &body.Events); err != nil {
					return err
				}
			}
			if ctx.IsSet("lease-token") {
				body.LeaseToken = ctx.String("lease-token")
			}
			if ctx.IsSet("worker-instance-id") {
				v := ctx.String("worker-instance-id")
				body.WorkerInstanceId = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("events") {
				return fmt.Errorf("--events is required (or supply it via --file)")
			}
			if body.LeaseToken == "" {
				return fmt.Errorf("--lease-token is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.EmitJobEventsWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "emitJobEvents", resp.StatusCode(), resp.Body)
		})

	jobsGrp.Command("get").
		Description("Get a workflow job by ID").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetJobWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getJob", resp.StatusCode(), resp.Body)
		})

	jobsGrp.Command("get-history").
		Description("Fetch durable replay history for a code-spec job").
		Args("id").
		Flags(
			cli.String("after", "").Help("Opaque cursor returned by a prior page (or `JobClaim.spec.code.history_cursor`). Omit to fetch from…"),
			cli.Int("limit", "").Help("Maximum number of entries to return per page."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.GetJobHistoryParams{}
			if ctx.IsSet("after") {
				v := ctx.String("after")
				params.After = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			resp, err := client.GetJobHistoryWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getJobHistory", resp.StatusCode(), resp.Body)
		})

	jobsGrp.Command("heartbeat").
		Description("Refresh the lease on a claimed workflow job").
		Args("id").
		Flags(
			cli.String("lease-token", "").Help("[required] Opaque lease fence value from the original claim. Mismatch returns 409 lease-lost."),
			cli.String("worker-instance-id", "").Help("Echo of the `worker_instance_id` from the claim. Logged for audit; not the fence value."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.HeartbeatJobJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("lease-token") {
				body.LeaseToken = ctx.String("lease-token")
			}
			if ctx.IsSet("worker-instance-id") {
				v := ctx.String("worker-instance-id")
				body.WorkerInstanceId = &v
			}
			if body.LeaseToken == "" {
				return fmt.Errorf("--lease-token is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.HeartbeatJobWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "heartbeatJob", resp.StatusCode(), resp.Body)
		})

	jobsGrp.Command("report-job").
		Description("Report progress or the outcome of a workflow job attempt").
		Args("id").
		Flags(
			cli.Bool("partial", "").Help("When `true`, commit durable code progress without terminalizing the job. Only valid for code jobs a…"),
			cli.String("lease-token", "").Help("[required] Opaque fence value from the original claim. Mismatch returns 409 lease-lost; a duplicate report wit…"),
			cli.String("outcomes", "").Help("[required] Ordered list of outcomes. May contain zero or more durable progress entries (`step_done`, `wait_obs… Accepts JSON, @file, or @-."),
			cli.String("worker-instance-id", "").Help("Echo of the claim's `worker_instance_id`. Audit only."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ReportJobParams{}
			if ctx.IsSet("partial") {
				v := ctx.Bool("partial")
				params.Partial = &v
			}
			var body api.ReportJobJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("lease-token") {
				body.LeaseToken = ctx.String("lease-token")
			}
			if ctx.IsSet("outcomes") {
				if err := decodeFlagJSON(ctx, "outcomes", ctx.String("outcomes"), &body.Outcomes); err != nil {
					return err
				}
			}
			if ctx.IsSet("worker-instance-id") {
				v := ctx.String("worker-instance-id")
				body.WorkerInstanceId = &v
			}
			if body.LeaseToken == "" {
				return fmt.Errorf("--lease-token is required (or supply it via --file)")
			}
			if ctx.String("file") == "" && !ctx.IsSet("outcomes") {
				return fmt.Errorf("--outcomes is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.ReportJobWithResponse(ctx.Context(), p0, p1, params, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "reportJob", resp.StatusCode(), resp.Body)
		})

	jobsGrp.Command("run-job-action").
		Description("Execute one server-side action for a claimed workflow job").
		Args("id", "action-name").
		Flags(
			cli.String("parameters", "").Help("Input parameters passed to the action handler. Accepts JSON, @file, or @-."),
			cli.Int("timeout-seconds", "").Help("Override the default action execution timeout."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			var body api.RunJobActionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("parameters") {
				if err := decodeFlagJSON(ctx, "parameters", ctx.String("parameters"), &body.Parameters); err != nil {
					return err
				}
			}
			if ctx.IsSet("timeout-seconds") {
				v := ctx.Int("timeout-seconds")
				body.TimeoutSeconds = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("parameters") && !ctx.IsSet("timeout-seconds") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.RunJobActionWithResponse(ctx.Context(), p0, p1, p2, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "runJobAction", resp.StatusCode(), resp.Body)
		})

}
