// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerGroupsCommands registers every generated subcommand in the "groups" group.
func registerGroupsCommands(app *cli.App) {
	groupsGrp := app.Group("groups").Description("Member groups for routing interactions")
	groupsGrp.Alias("group")
	groupsGrp.Command("add-member").
		Description("Add a member to a group").
		Args("group").
		Flags(
			cli.String("user-id", "").Help("[required] Org member user ID to add. Must be a current org member."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.AddGroupMemberJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("user-id") {
				body.UserId = ctx.String("user-id")
			}
			if body.UserId == "" {
				return fmt.Errorf("--user-id is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.AddGroupMemberWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "addGroupMember", resp.StatusCode(), resp.Body)
		})

	groupsGrp.Command("create").
		Description("Create a group").
		Flags(
			cli.String("description", "").Help("Optional human-readable description."),
			cli.String("handle", "").Help("URL-safe handle, unique within the project. Auto-derived from name if omitted."),
			cli.String("name", "").Help("[required] Display name (1–64 chars)."),
			cli.String("routing-policy", "").Help("How responses are collected from group members: `first_responder` or `all_members`. Defaults to `fi…"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateGroupJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("handle") {
				v := ctx.String("handle")
				body.Handle = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("routing-policy") {
				v := api.CreateGroupRequestRoutingPolicy(ctx.String("routing-policy"))
				body.RoutingPolicy = &v
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateGroupWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createGroup", resp.StatusCode(), resp.Body)
		})

	groupsGrp.Command("delete").
		Description("Delete a group").
		Args("group").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteGroupWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteGroup", resp.StatusCode(), resp.Body)
		})

	groupsGrp.Command("get").
		Description("Get a group").
		Args("group").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetGroupWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getGroup", resp.StatusCode(), resp.Body)
		})

	groupsGrp.Command("list").
		Description("List groups").
		Flags(
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListGroupsParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListGroupsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listGroups", resp.StatusCode(), resp.Body)
		})

	groupsGrp.Command("list-groups").
		Description("List groups a member belongs to").
		Args("user-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ListMemberGroupsWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listMemberGroups", resp.StatusCode(), resp.Body)
		})

	groupsGrp.Command("list-members").
		Description("List members of a group").
		Args("group").
		Flags(
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListGroupMembersParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListGroupMembersWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listGroupMembers", resp.StatusCode(), resp.Body)
		})

	groupsGrp.Command("remove-member").
		Description("Remove a member from a group").
		Args("group", "user-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.RemoveGroupMemberWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "removeGroupMember", resp.StatusCode(), resp.Body)
		})

	groupsGrp.Command("update").
		Description("Update a group").
		Args("group").
		Flags(
			cli.String("description", "").Help("Replacement description."),
			cli.String("name", "").Help("Replacement human-readable name."),
			cli.String("routing-policy", "").Help("Replacement routing policy, either `first_responder` or `all_members`. Affects future interactions …"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateGroupJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("routing-policy") {
				v := api.UpdateGroupRequestRoutingPolicy(ctx.String("routing-policy"))
				body.RoutingPolicy = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("description") && !ctx.IsSet("name") && !ctx.IsSet("routing-policy") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateGroupWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateGroup", resp.StatusCode(), resp.Body)
		})

}
