// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerActorStateCommands registers every generated subcommand in the "actor-state" group.
func registerActorStateCommands(app *cli.App) {
	actorStateGrp := app.Group("actor-state").Description("Reportable actor state and per-target assignments")
	actorStateGrp.Command("get-state").
		Description("Get actor state").
		Args("actor-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetActorStateWithResponse(ctx.Context(), api.ProjectHandleParam(p0), p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getActorState", resp.StatusCode(), resp.Body)
		})

	actorStateGrp.Command("list-assignments").
		Description("List actor assignments").
		Flags(
			cli.String("status", "").Help("status"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListActorAssignmentsParams{}
			if ctx.IsSet("status") {
				v := api.ActorAssignmentStatus(ctx.String("status"))
				params.Status = &v
			}
			resp, err := client.ListActorAssignmentsWithResponse(ctx.Context(), api.ProjectHandleParam(p0), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listActorAssignments", resp.StatusCode(), resp.Body)
		})

	actorStateGrp.Command("list-states").
		Description("List actor state").
		Flags(
			cli.String("actor-kind", "").Help("actor-kind"),
			cli.String("availability", "").Help("availability"),
			cli.String("visibility", "").Help("visibility"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListActorStatesParams{}
			if ctx.IsSet("actor-kind") {
				v := api.ActorStateActorKind(ctx.String("actor-kind"))
				params.ActorKind = &v
			}
			if ctx.IsSet("availability") {
				v := api.ActorAvailability(ctx.String("availability"))
				params.Availability = &v
			}
			if ctx.IsSet("visibility") {
				v := api.ActorStateVisibility(ctx.String("visibility"))
				params.Visibility = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListActorStatesWithResponse(ctx.Context(), api.ProjectHandleParam(p0), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listActorStates", resp.StatusCode(), resp.Body)
		})

	actorStateGrp.Command("upsert-actor-state").
		Description("Upsert actor state").
		Args("actor-id").
		Flags(
			cli.String("actor-kind", "").Help("[required] actor-kind"),
			cli.String("assignments", "").Help("assignments Accepts JSON, @file, or @-."),
			cli.String("availability", "").Help("[required] availability"),
			cli.String("description", "").Help("description"),
			cli.String("expires-at", "").Help("expires-at Accepts JSON, @file, or @-."),
			cli.String("visibility", "").Help("visibility"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpsertActorStateJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("actor-kind") {
				body.ActorKind = api.ActorStateActorKind(ctx.String("actor-kind"))
			}
			if ctx.IsSet("assignments") {
				if err := decodeFlagJSON(ctx, "assignments", ctx.String("assignments"), &body.Assignments); err != nil {
					return err
				}
			}
			if ctx.IsSet("availability") {
				body.Availability = api.ActorAvailability(ctx.String("availability"))
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("expires-at") {
				if err := decodeFlagJSON(ctx, "expires-at", ctx.String("expires-at"), &body.ExpiresAt); err != nil {
					return err
				}
			}
			if ctx.IsSet("visibility") {
				v := api.ActorStateVisibility(ctx.String("visibility"))
				body.Visibility = &v
			}
			if body.ActorKind == "" {
				return fmt.Errorf("--actor-kind is required (or supply it via --file)")
			}
			if body.Availability == "" {
				return fmt.Errorf("--availability is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpsertActorStateWithResponse(ctx.Context(), api.ProjectHandleParam(p0), p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "upsertActorState", resp.StatusCode(), resp.Body)
		})

}
