// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerSessionsCommands registers every generated subcommand in the "sessions" group.
func registerSessionsCommands(app *cli.App) {
	sessionsGrp := app.Group("sessions").Description("Conversation sessions, transcripts, and invocation")
	sessionsGrp.Alias("session")
	sessionsGrp.Command("append-session-messages").
		Description("Append session messages").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Flags(
			cli.String("messages", "").Help("[required] Messages to append to the session, in order. Accepts JSON, @file, or @-."),
			cli.String("model", "").Help("Model that produced these messages."),
			cli.String("model-provider", "").Help("Provider for the supplied `model`."),
			cli.Int("token-input-total", "").Help("Updated lifetime input-token total for this session."),
			cli.Int("token-output-total", "").Help("Updated lifetime output-token total for this session."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.AppendSessionMessagesJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("messages") {
				if err := decodeFlagJSON(ctx, "messages", ctx.String("messages"), &body.Messages); err != nil {
					return err
				}
			}
			if ctx.IsSet("model") {
				v := ctx.String("model")
				body.Model = &v
			}
			if ctx.IsSet("model-provider") {
				v := ctx.String("model-provider")
				body.ModelProvider = &v
			}
			if ctx.IsSet("token-input-total") {
				v := ctx.Int("token-input-total")
				body.TokenInputTotal = &v
			}
			if ctx.IsSet("token-output-total") {
				v := ctx.Int("token-output-total")
				body.TokenOutputTotal = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("messages") {
				return fmt.Errorf("--messages is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.AppendSessionMessagesWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "appendSessionMessages", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("cancel").
		Description("Cancel the session's active turn").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.CancelSessionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "cancelSession", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("cancel-turn").
		Description("Cancel a session turn").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		AddArg(&cli.Arg{Name: "turn-id", Description: "Identifier of a turn within a session.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.CancelTurnWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "cancelTurn", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("compact").
		Description("Compact the session transcript now").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.CompactSessionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "compactSession", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("create").
		Description("Create or resolve a session").
		Flags(
			cli.String("agent-id", "").Help("[required] Agent that owns the session."),
			cli.String("compaction-policy", "").Help("Controls how a session's transcript is automatically summarized as it grows. On create the supplied fields are merged over the owning… Accepts JSON, @file, or @-."),
			cli.String("metadata", "").Help("Free-form caller metadata for the session. Accepts JSON, @file, or @-."),
			cli.String("mode", "").Help("`continue_or_create` (default) resolves an existing session for the `session_key` or creates one; `new` always creates a fresh session…"),
			cli.String("model", "").Help("Model to record on the session."),
			cli.String("session-key", "").Help("Stable key identifying the conversation within the agent."),
			cli.String("title", "").Help("Human-friendly session title."),
			cli.String("visibility", "").Help("Visibility of the session in project surfaces: `project` or `private`."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateSessionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("agent-id") {
				body.AgentId = ctx.String("agent-id")
			}
			if ctx.IsSet("compaction-policy") {
				if err := decodeFlagJSON(ctx, "compaction-policy", ctx.String("compaction-policy"), &body.CompactionPolicy); err != nil {
					return err
				}
			}
			if ctx.IsSet("metadata") {
				if err := decodeFlagJSON(ctx, "metadata", ctx.String("metadata"), &body.Metadata); err != nil {
					return err
				}
			}
			if ctx.IsSet("mode") {
				v := api.CreateSessionRequestMode(ctx.String("mode"))
				body.Mode = &v
			}
			if ctx.IsSet("model") {
				v := ctx.String("model")
				body.Model = &v
			}
			if ctx.IsSet("session-key") {
				v := ctx.String("session-key")
				body.SessionKey = &v
			}
			if ctx.IsSet("title") {
				v := ctx.String("title")
				body.Title = &v
			}
			if ctx.IsSet("visibility") {
				v := api.SessionVisibility(ctx.String("visibility"))
				body.Visibility = &v
			}
			if body.AgentId == "" {
				return fmt.Errorf("--agent-id is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateSessionWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createSession", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("delete").
		Description("Delete session").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteSessionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteSession", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("get").
		Description("Get session").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetSessionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getSession", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("get-turn").
		Description("Get a session turn").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		AddArg(&cli.Arg{Name: "turn-id", Description: "Identifier of a turn within a session.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.GetSessionTurnWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getSessionTurn", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("get-turn-live").
		Description("Get live session turn snapshot").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		AddArg(&cli.Arg{Name: "turn-id", Description: "Identifier of a turn within a session.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.GetSessionTurnLiveWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getSessionTurnLive", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("invoke-agent").
		Description("Invoke an agent").
		Flags(
			cli.String("agent-ref", "").Help("[required] Reference to an agent in this project. Supply exactly one of `id` (the agent identifier) or `name` (the project-unique agent name). A… Accepts JSON, @file, or @-."),
			cli.String("channel-context", "").Help("Optional messaging provider/channel routing context (Slack, Telegram, …). Persisted on the started turn's input-message metadata under a… Accepts JSON, @file, or @-."),
			cli.String("input", "").Help("[required] The caller input message that starts the agent turn. Accepts JSON, @file, or @-."),
			cli.String("session", "").Help("How to resolve or create the session this invocation runs in. Mirrors the create-session policy: `mode` + `session_key` resolve a durable… Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.InvokeAgentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("agent-ref") {
				if err := decodeFlagJSON(ctx, "agent-ref", ctx.String("agent-ref"), &body.AgentRef); err != nil {
					return err
				}
			}
			if ctx.IsSet("channel-context") {
				if err := decodeFlagJSON(ctx, "channel-context", ctx.String("channel-context"), &body.ChannelContext); err != nil {
					return err
				}
			}
			if ctx.IsSet("input") {
				if err := decodeFlagJSON(ctx, "input", ctx.String("input"), &body.Input); err != nil {
					return err
				}
			}
			if ctx.IsSet("session") {
				if err := decodeFlagJSON(ctx, "session", ctx.String("session"), &body.Session); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("agent-ref") {
				return fmt.Errorf("--agent-ref is required (or supply it via --file)")
			}
			if ctx.String("file") == "" && !ctx.IsSet("input") {
				return fmt.Errorf("--input is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.InvokeAgentWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "invokeAgent", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("list").
		Description("List sessions").
		Flags(
			cli.String("agent-id", "").Help("Filter to sessions owned by this agent."),
			cli.String("session-key", "").Help("Look up the session with this exact routing key — a read-only deterministic lookup that avoids a create-or-resolve round trip, returning…"),
			cli.String("status", "").Help("Filter by session status."),
			cli.String("scope", "").Help("Filter by session scope."),
			cli.String("provider", "").Help("Filter messaging sessions by provider metadata, e.g. `slack` or `telegram`."),
			cli.String("integration-id", "").Help("Filter to sessions created by this integration, e.g. agent sessions started from a connected provider."),
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
			cli.Int("limit", "").Help("Maximum number of items to return"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListSessionsParams{}
			if ctx.IsSet("agent-id") {
				v := ctx.String("agent-id")
				params.AgentId = &v
			}
			if ctx.IsSet("session-key") {
				v := ctx.String("session-key")
				params.SessionKey = &v
			}
			if ctx.IsSet("status") {
				v := api.SessionStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("scope") {
				v := api.SessionScope(ctx.String("scope"))
				params.Scope = &v
			}
			if ctx.IsSet("provider") {
				v := ctx.String("provider")
				params.Provider = &v
			}
			if ctx.IsSet("integration-id") {
				v := ctx.String("integration-id")
				params.IntegrationId = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListSessionsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listSessions", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("list-messages").
		Description("List session messages").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Flags(
			cli.Int("after-sequence", "").Help("Continuation cursor for sequence-ordered lists. Only include rows whose monotonic per-resource sequence is strictly greater than this…"),
			cli.Int("before-sequence", "").Help("Backward continuation cursor for sequence-ordered lists. Only include rows whose monotonic per-resource sequence is strictly less than this…"),
			cli.String("order", "").Help("Scan direction for the page. `asc` (the default) returns oldest-first; `desc` returns newest-first — the way to fetch the latest rows of…"),
			cli.Int("limit", "").Help("Maximum number of items to return"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListSessionMessagesParams{}
			if ctx.IsSet("after-sequence") {
				v := api.AfterSequenceParam(int64(ctx.Int("after-sequence")))
				params.AfterSequence = &v
			}
			if ctx.IsSet("before-sequence") {
				v := api.BeforeSequenceParam(int64(ctx.Int("before-sequence")))
				params.BeforeSequence = &v
			}
			if ctx.IsSet("order") {
				v := api.ListSessionMessagesParamsOrder(ctx.String("order"))
				params.Order = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListSessionMessagesWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listSessionMessages", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("list-turns").
		Description("List session turns").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Flags(
			cli.Strings("ids", "").Help("Return exactly the turns with these ids (the transcript-join primitive). When set, pagination and ordering are ignored and the named turns…"),
			cli.String("order", "").Help("Scan direction for the page. `asc` (the default) returns oldest-first; `desc` returns newest-first — the way to fetch the latest rows of…"),
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
			cli.Int("limit", "").Help("Maximum number of items to return"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListSessionTurnsParams{}
			if ctx.IsSet("ids") {
				v := ctx.Strings("ids")
				params.Ids = &v
			}
			if ctx.IsSet("order") {
				v := api.ListSessionTurnsParamsOrder(ctx.String("order"))
				params.Order = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListSessionTurnsWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listSessionTurns", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("start-turn").
		Description("Start an agent turn").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Flags(
			cli.String("content", "").Help("[required] Ordered content blocks (text, images) for the input message. Accepts JSON, @file, or @-."),
			cli.String("idempotency-key", "").Help("Dedup key scoped to the session. A repeat call with the same key resumes the existing turn and writes nothing new."),
			cli.String("metadata", "").Help("Free-form caller metadata attached to the input message. Accepts JSON, @file, or @-."),
			cli.String("role", "").Help("Role of the input message. A turn carries caller input, so only `user` is accepted; defaults to `user` when omitted."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.StartTurnJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("content") {
				if err := decodeFlagJSON(ctx, "content", ctx.String("content"), &body.Content); err != nil {
					return err
				}
			}
			if ctx.IsSet("idempotency-key") {
				v := ctx.String("idempotency-key")
				body.IdempotencyKey = &v
			}
			if ctx.IsSet("metadata") {
				if err := decodeFlagJSON(ctx, "metadata", ctx.String("metadata"), &body.Metadata); err != nil {
					return err
				}
			}
			if ctx.IsSet("role") {
				v := api.StartTurnRequestRole(ctx.String("role"))
				body.Role = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("content") {
				return fmt.Errorf("--content is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.StartTurnWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "startTurn", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("stream").
		Description("Stream a session's activity").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Flags(
			cli.Int("after-sequence", "").Help("Continuation cursor for sequence-ordered lists. Only include rows whose monotonic per-resource sequence is strictly greater than this…"),
			cli.Int("last-event-id", "").Help("SSE reconnect cursor. The browser EventSource API replays the last event's `id` in this header on automatic reconnect; the server resumes…"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.StreamSessionParams{}
			if ctx.IsSet("after-sequence") {
				v := api.AfterSequenceParam(int64(ctx.Int("after-sequence")))
				params.AfterSequence = &v
			}
			if ctx.IsSet("last-event-id") {
				v := api.LastEventIDParam(int64(ctx.Int("last-event-id")))
				params.LastEventID = &v
			}
			resp, err := client.StreamSessionWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "streamSession", resp.StatusCode(), resp.Body)
		})

	sessionsGrp.Command("update").
		Description("Update session").
		AddArg(&cli.Arg{Name: "session-id", Description: "Identifier of the conversation session.", Required: true}).
		Flags(
			cli.String("compaction-policy", "").Help("Controls how a session's transcript is automatically summarized as it grows. On create the supplied fields are merged over the owning… Accepts JSON, @file, or @-."),
			cli.String("status", "").Help("Durable conversation session status: `active`, `archived`, or `deleted`."),
			cli.String("title", "").Help("Human-readable session title."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateSessionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("compaction-policy") {
				if err := decodeFlagJSON(ctx, "compaction-policy", ctx.String("compaction-policy"), &body.CompactionPolicy); err != nil {
					return err
				}
			}
			if ctx.IsSet("status") {
				v := api.SessionStatus(ctx.String("status"))
				body.Status = &v
			}
			if ctx.IsSet("title") {
				v := ctx.String("title")
				body.Title = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("compaction-policy") && !ctx.IsSet("status") && !ctx.IsSet("title") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateSessionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateSession", resp.StatusCode(), resp.Body)
		})

}
