// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerArtifactsCommands registers every generated subcommand in the "artifacts" group.
func registerArtifactsCommands(app *cli.App) {
	artifactsGrp := app.Group("artifacts").Description("Run output artifacts and storage quota")
	artifactsGrp.Alias("artifact")
	artifactsGrp.Command("create-signed-url").
		Description("Create a signed artifact URL").
		AddArg(&cli.Arg{Name: "id", Description: "TypeID of the artifact (`art_...`)", Required: true}).
		Flags(
			cli.Int("ttl-seconds", "").Help("Requested signed URL TTL. The server caps this at the maximum supported artifact download TTL."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.CreateArtifactSignedUrlParams{}
			if ctx.IsSet("ttl-seconds") {
				v := int64(ctx.Int("ttl-seconds"))
				params.TtlSeconds = &v
			}
			resp, err := client.CreateArtifactSignedUrlWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createArtifactSignedUrl", resp.StatusCode(), resp.Body)
		})

	artifactsGrp.Command("delete").
		Description("Delete an artifact").
		AddArg(&cli.Arg{Name: "id", Description: "TypeID of the artifact (`art_...`)", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteArtifactWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteArtifact", resp.StatusCode(), resp.Body)
		})

	artifactsGrp.Command("get").
		Description("Get an artifact").
		AddArg(&cli.Arg{Name: "id", Description: "TypeID of the artifact (`art_...`)", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetArtifactWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getArtifact", resp.StatusCode(), resp.Body)
		})

	artifactsGrp.Command("get-content").
		Description("Fetch artifact bytes").
		AddArg(&cli.Arg{Name: "id", Description: "TypeID of the artifact (`art_...`)", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetArtifactContentWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getArtifactContent", resp.StatusCode(), resp.Body)
		})

	artifactsGrp.Command("get-storage-quota").
		Description("Get per-org Mobius-managed artifact storage quota usage").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			resp, err := client.GetArtifactStorageQuotaWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getArtifactStorageQuota", resp.StatusCode(), resp.Body)
		})

	artifactsGrp.Command("list").
		Description("List artifacts in a project").
		Flags(
			cli.String("run-id", "").Help("Filter to artifacts produced by this automation run."),
			cli.String("step-id", "").Help("Filter to artifacts produced by this run step."),
			cli.String("mime", "").Help("Mime prefix filter (e.g. `image/`)"),
			cli.String("state", "").Help("Filter by artifact lifecycle state."),
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
			cli.Int("limit", "").Help("Maximum number of items to return"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListArtifactsParams{}
			if ctx.IsSet("run-id") {
				v := ctx.String("run-id")
				params.RunId = &v
			}
			if ctx.IsSet("step-id") {
				v := ctx.String("step-id")
				params.StepId = &v
			}
			if ctx.IsSet("mime") {
				v := ctx.String("mime")
				params.Mime = &v
			}
			if ctx.IsSet("state") {
				v := api.ArtifactState(ctx.String("state"))
				params.State = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListArtifactsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listArtifacts", resp.StatusCode(), resp.Body)
		})

}
