// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerAutomationsCommands registers every generated subcommand in the "automations" group.
func registerAutomationsCommands(app *cli.App) {
	automationsGrp := app.Group("automations").Description("Automation definitions, versions, and runs")
	automationsGrp.Alias("automation")
	automationsGrp.Command("create").
		Description("Create an automation").
		Flags(
			cli.String("default-agent-id", "").Help("Agent used by `agent` steps that do not pin an agent explicitly."),
			cli.String("default-inputs", "").Help("Default values merged into `inputs` when a run is started without overrides. Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Markdown description of the automation's purpose."),
			cli.String("handle", "").Help("[required] Stable per-project automation handle. Immutable after creation."),
			cli.String("name", "").Help("[required] Human-readable display name."),
			cli.String("settings", "").Help("Free-form automation-level settings consumed by the engine. Accepts JSON, @file, or @-."),
			cli.String("tags", "").Help("Free-form label map used to organise automations in listings and search. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateAutomationJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("default-agent-id") {
				v := ctx.String("default-agent-id")
				body.DefaultAgentId = &v
			}
			if ctx.IsSet("default-inputs") {
				if err := decodeFlagJSON(ctx, "default-inputs", ctx.String("default-inputs"), &body.DefaultInputs); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("handle") {
				body.Handle = ctx.String("handle")
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("settings") {
				if err := decodeFlagJSON(ctx, "settings", ctx.String("settings"), &body.Settings); err != nil {
					return err
				}
			}
			if ctx.IsSet("tags") {
				if err := decodeFlagJSON(ctx, "tags", ctx.String("tags"), &body.Tags); err != nil {
					return err
				}
			}
			if body.Handle == "" {
				return fmt.Errorf("--handle is required (or supply it via --file)")
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateAutomationWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createAutomation", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("create-version").
		Description("Create a new draft version").
		AddArg(&cli.Arg{Name: "handle", Description: "Project-unique automation handle.", Required: true}).
		Flags(
			cli.String("compiled-plan", "").Help("Optional precompiled execution plan. The engine will recompile from `spec` if omitted. Accepts JSON, @file, or @-."),
			cli.String("spec", "").Help("[required] Authoring representation of an automation. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.CreateAutomationVersionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("compiled-plan") {
				if err := decodeFlagJSON(ctx, "compiled-plan", ctx.String("compiled-plan"), &body.CompiledPlan); err != nil {
					return err
				}
			}
			if ctx.IsSet("spec") {
				if err := decodeFlagJSON(ctx, "spec", ctx.String("spec"), &body.Spec); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("spec") {
				return fmt.Errorf("--spec is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateAutomationVersionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createAutomationVersion", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("delete").
		Description("Archive an automation").
		AddArg(&cli.Arg{Name: "handle", Description: "Project-unique automation handle.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteAutomationWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteAutomation", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("deliver-http-trigger").
		Description("Deliver an HTTP request payload to a trigger").
		AddArg(&cli.Arg{Name: "http-handle", Description: "Globally unique identifier for the trigger. The endpoint carries no project context, so the handle …", Required: true}).
		Flags(
			cli.String("idempotency-key", "").Help("Optional idempotency key (also accepted via the X-Idempotency-Key header)."),
			cli.String("x-idempotency-key", "").Help("Alternative to the `idempotency_key` query parameter. When both are present the query parameter win…"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			params := &api.DeliverHTTPTriggerParams{}
			if ctx.IsSet("idempotency-key") {
				v := ctx.String("idempotency-key")
				params.IdempotencyKey = &v
			}
			if ctx.IsSet("x-idempotency-key") {
				v := ctx.String("x-idempotency-key")
				params.XIdempotencyKey = &v
			}
			var body api.DeliverHTTPTriggerJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.String("file") == "" {
				return fmt.Errorf("--file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.DeliverHTTPTriggerWithResponse(ctx.Context(), p0, params, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deliverHTTPTrigger", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("get").
		Description("Get an automation").
		AddArg(&cli.Arg{Name: "handle", Description: "Project-unique automation handle.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetAutomationWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getAutomation", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("list").
		Description("List automations in a project").
		Flags(
			cli.String("status", "").Help("Filter by lifecycle status. Omit to return all non-archived automations (the default). Pass a singl…"),
			cli.String("cursor", "").Help("Opaque pagination cursor from a prior response."),
			cli.Int("limit", "").Help("Maximum number of items to return."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListAutomationsParams{}
			if ctx.IsSet("status") {
				v := api.ListAutomationsParamsStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			resp, err := client.ListAutomationsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAutomations", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("list-versions").
		Description("List versions for an automation").
		AddArg(&cli.Arg{Name: "handle", Description: "Project-unique automation handle.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ListAutomationVersionsWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAutomationVersions", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("publish-automation-version").
		Description("Publish a version").
		AddArg(&cli.Arg{Name: "handle", Description: "Project-unique automation handle.", Required: true}).
		AddArg(&cli.Arg{Name: "version", Description: "Version number of the AutomationVersion to publish.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2, err := parseIntArg(ctx.Arg(1), "version")
			if err != nil {
				return err
			}
			resp, err := client.PublishAutomationVersionWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "publishAutomationVersion", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("update").
		Description("Update an automation").
		AddArg(&cli.Arg{Name: "handle", Description: "Project-unique automation handle.", Required: true}).
		Flags(
			cli.String("default-agent-id", "").Help("Agent used by `agent` steps that do not pin an agent explicitly."),
			cli.String("default-inputs", "").Help("Default values merged into `inputs` when a run is started without overrides. Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Markdown description of the automation's purpose."),
			cli.String("name", "").Help("Human-readable display name."),
			cli.String("settings", "").Help("Free-form automation-level settings consumed by the engine. Accepts JSON, @file, or @-."),
			cli.String("status", "").Help("Lifecycle status of an automation."),
			cli.String("tags", "").Help("Free-form label map used to organise automations in listings and search. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateAutomationJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("default-agent-id") {
				v := ctx.String("default-agent-id")
				body.DefaultAgentId = &v
			}
			if ctx.IsSet("default-inputs") {
				if err := decodeFlagJSON(ctx, "default-inputs", ctx.String("default-inputs"), &body.DefaultInputs); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("settings") {
				if err := decodeFlagJSON(ctx, "settings", ctx.String("settings"), &body.Settings); err != nil {
					return err
				}
			}
			if ctx.IsSet("status") {
				v := api.AutomationStatus(ctx.String("status"))
				body.Status = &v
			}
			if ctx.IsSet("tags") {
				if err := decodeFlagJSON(ctx, "tags", ctx.String("tags"), &body.Tags); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("default-agent-id") && !ctx.IsSet("default-inputs") && !ctx.IsSet("description") && !ctx.IsSet("name") && !ctx.IsSet("settings") && !ctx.IsSet("status") && !ctx.IsSet("tags") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateAutomationWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateAutomation", resp.StatusCode(), resp.Body)
		})

}
