// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"
)

// registerPermissionsCommands registers every generated subcommand in the "permissions" group.
func registerPermissionsCommands(app *cli.App) {
	permissionsGrp := app.Group("permissions").Description("Permission catalog for project roles")
	permissionsGrp.Alias("permission")
	permissionsGrp.Command("list").
		Description("List project permissions").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			resp, err := client.ListProjectPermissionsWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listProjectPermissions", resp.StatusCode(), resp.Body)
		})

}
