// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"encoding/json"
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerWebhooksCommands registers every generated subcommand in the "webhooks" group.
func registerWebhooksCommands(app *cli.App) {
	webhooksGrp := app.Group("webhooks").Description("Outgoing webhook subscriptions")
	webhooksGrp.Alias("webhook")
	webhooksGrp.Command("create").
		Description("Create a webhook").
		Flags(
			cli.Bool("enabled", "").Help("Whether the webhook starts enabled. Defaults to true when omitted."),
			cli.Strings("events", "").Help("[required] Event types to subscribe to. Use wildcards for broad subscriptions, e.g. `[\"run.*\"]` for all run events."),
			cli.String("name", "").Help("[required] Human-readable name, unique within the project."),
			cli.String("signing-secret", "").Help("Optional HMAC-SHA256 secret. When set, Mobius signs each POST body and includes `X-Mobius-Signature: sha256=<hex>` in the request headers."),
			cli.String("tags", "").Help("Key/value tag map. Keys 1–128 chars, values 0–256 chars. Keys with the `mobius:` prefix are system-managed and cannot be set by callers. Maximum 8 tags per resource. Use tags to organize resources by environment, team, cost-center, or any other dimension meaningful to your organization; tags can be filtered on most list endpoints. (JSON)"),
			cli.String("url", "").Help("The endpoint Mobius will POST event payloads to. May be left empty at creation time so a candidate URL can be tested via the ping endpoint before it is saved; events do not fire for webhooks with an empty URL."),
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			var body api.CreateWebhookJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("enabled") {
				v := ctx.Bool("enabled")
				body.Enabled = &v
			}
			if ctx.IsSet("events") {
				body.Events = ctx.Strings("events")
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("signing-secret") {
				v := ctx.String("signing-secret")
				body.SigningSecret = &v
			}
			if ctx.IsSet("tags") {
				if err := json.Unmarshal([]byte(ctx.String("tags")), &body.Tags); err != nil {
					return fmt.Errorf("--tags: invalid JSON: %w", err)
				}
			}
			if ctx.IsSet("url") {
				v := ctx.String("url")
				body.Url = &v
			}
			if len(body.Events) == 0 {
				return fmt.Errorf("--events is required (or supply it via --file)")
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			resp, err := client.CreateWebhookWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("delete").
		Description("Delete a webhook").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			resp, err := client.DeleteWebhookWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("get").
		Description("Get a webhook").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			resp, err := client.GetWebhookWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("list").
		Description("List webhooks").
		Flags(
			cli.Bool("enabled", "").Help("Filter by enabled/disabled state."),
			cli.String("cursor", "").Help("Opaque pagination cursor returned from the previous response."),
			cli.Int("limit", "").Help("Maximum number of results to return per page."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			params := &api.ListWebhooksParams{}
			if ctx.IsSet("enabled") {
				v := ctx.Bool("enabled")
				params.Enabled = &v
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			resp, err := client.ListWebhooksWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("list-deliveries").
		Description("List webhook deliveries").
		Args("id").
		Flags(
			cli.String("cursor", "").Help("Opaque pagination cursor returned from the previous response."),
			cli.Int("limit", "").Help("Maximum number of results to return per page."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			params := &api.ListWebhookDeliveriesParams{}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			resp, err := client.ListWebhookDeliveriesWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("ping-webhook").
		Description("Test a webhook URL").
		Args("id").
		Flags(
			cli.String("url", "").Help("URL to test. When supplied, the ping is sent to this URL instead of the webhook's saved URL — use this to validate a candidate URL before saving it. When omitted, the webhook's current saved URL is used."),
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			var body api.PingWebhookJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("url") {
				v := ctx.String("url")
				body.Url = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("url") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			resp, err := client.PingWebhookWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("update").
		Description("Update a webhook").
		Args("id").
		Flags(
			cli.Bool("enabled", "").Help("Set to false to disable delivery without deleting the webhook."),
			cli.Strings("events", "").Help("Replacement event subscriptions. Replaces the entire current list."),
			cli.String("name", "").Help("Replacement human-readable name."),
			cli.String("signing-secret", "").Help("Replace the current signing secret. Set to empty string to disable signing. Omit to leave the current secret unchanged."),
			cli.String("tags", "").Help("Key/value tag map. Keys 1–128 chars, values 0–256 chars. Keys with the `mobius:` prefix are system-managed and cannot be set by callers. Maximum 8 tags per resource. Use tags to organize resources by environment, team, cost-center, or any other dimension meaningful to your organization; tags can be filtered on most list endpoints. (JSON)"),
			cli.String("url", "").Help("Replacement endpoint URL."),
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			var body api.UpdateWebhookJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("enabled") {
				v := ctx.Bool("enabled")
				body.Enabled = &v
			}
			if ctx.IsSet("events") {
				v := ctx.Strings("events")
				body.Events = &v
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("signing-secret") {
				v := ctx.String("signing-secret")
				body.SigningSecret = &v
			}
			if ctx.IsSet("tags") {
				if err := json.Unmarshal([]byte(ctx.String("tags")), &body.Tags); err != nil {
					return fmt.Errorf("--tags: invalid JSON: %w", err)
				}
			}
			if ctx.IsSet("url") {
				v := ctx.String("url")
				body.Url = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("enabled") && !ctx.IsSet("events") && !ctx.IsSet("name") && !ctx.IsSet("signing-secret") && !ctx.IsSet("tags") && !ctx.IsSet("url") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			resp, err := client.UpdateWebhookWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
