// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerEventsCommands registers every generated subcommand in the "events" group.
func registerEventsCommands(app *cli.App) {
	eventsGrp := app.Group("events").Description("Inbound integration events and live SSE streams")
	eventsGrp.Alias("event")
	eventsGrp.Command("get").
		Description("Get a received integration event").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetIntegrationEventWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getIntegrationEvent", resp.StatusCode(), resp.Body)
		})

	eventsGrp.Command("list").
		Description("List received integration events").
		Flags(
			cli.String("provider", "").Help("Filter by provider name, e.g. `github`."),
			cli.String("integration-id", "").Help("Filter by integration row id."),
			cli.String("event-type", "").Help("Filter by exact dotted event type."),
			cli.String("source", "").Help("Filter by event source."),
			cli.String("cursor", "").Help("Opaque pagination cursor returned by the previous page."),
			cli.Int("limit", "").Help("Maximum number of events to return."),
			cli.Bool("include-payload", "").Help("Include redacted payloads in list rows. Defaults to summaries only."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListIntegrationEventsParams{}
			if ctx.IsSet("provider") {
				v := ctx.String("provider")
				params.Provider = &v
			}
			if ctx.IsSet("integration-id") {
				v := ctx.String("integration-id")
				params.IntegrationId = &v
			}
			if ctx.IsSet("event-type") {
				v := ctx.String("event-type")
				params.EventType = &v
			}
			if ctx.IsSet("source") {
				v := api.IntegrationEventSource(ctx.String("source"))
				params.Source = &v
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			if ctx.IsSet("include-payload") {
				v := ctx.Bool("include-payload")
				params.IncludePayload = &v
			}
			resp, err := client.ListIntegrationEventsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listIntegrationEvents", resp.StatusCode(), resp.Body)
		})

	eventsGrp.Command("list-test-samples").
		Description("List synthetic integration event samples").
		Flags(
			cli.String("provider", "").Help("Filter samples by provider name, e.g. `github`."),
			cli.String("event-type", "").Help("Filter samples by exact event type."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListIntegrationEventTestSamplesParams{}
			if ctx.IsSet("provider") {
				v := ctx.String("provider")
				params.Provider = &v
			}
			if ctx.IsSet("event-type") {
				v := ctx.String("event-type")
				params.EventType = &v
			}
			resp, err := client.ListIntegrationEventTestSamplesWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listIntegrationEventTestSamples", resp.StatusCode(), resp.Body)
		})

	eventsGrp.Command("stream-project").
		Description("Subscribe to a project-wide live event stream (SSE)").
		Flags(
			cli.String("since", "").Help("Opaque durable project-stream cursor to replay from. Pass back the exact `id:`/`seq` string previou…"),
			cli.String("run", "").Help("Comma-separated run IDs to filter by."),
			cli.String("channel", "").Help("Comma-separated channel IDs to filter by."),
			cli.String("interaction", "").Help("Comma-separated interaction IDs to filter by."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.StreamProjectEventsParams{}
			if ctx.IsSet("since") {
				v := ctx.String("since")
				params.Since = &v
			}
			if ctx.IsSet("run") {
				v := ctx.String("run")
				params.Run = &v
			}
			if ctx.IsSet("channel") {
				v := ctx.String("channel")
				params.Channel = &v
			}
			if ctx.IsSet("interaction") {
				v := ctx.String("interaction")
				params.Interaction = &v
			}
			resp, err := client.StreamProjectEventsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "streamProjectEvents", resp.StatusCode(), resp.Body)
		})

	eventsGrp.Command("stream-run").
		Description("Subscribe to a stream of events for a single run (SSE)").
		Args("id").
		Flags(
			cli.String("since", "").Help("Run-local `run_events.seq` cursor to replay from, encoded as a string. Do not pass a project-stream…"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.StreamRunEventsParams{}
			if ctx.IsSet("since") {
				v := ctx.String("since")
				params.Since = &v
			}
			resp, err := client.StreamRunEventsWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "streamRunEvents", resp.StatusCode(), resp.Body)
		})

	eventsGrp.Command("test-fire").
		Description("Preview or deliver a synthetic integration event").
		Flags(
			cli.String("dedup-key", "").Help("Optional dedup key for deliver mode. Defaults to the generated synthetic event id."),
			cli.String("event-type", "").Help("Dotted integration event type to fire. Required when sample_id is omitted."),
			cli.String("integration-id", "").Help("Optional integration id metadata. Defaults to `synthetic:<provider>`."),
			cli.String("meta", "").Help("Optional metadata overrides. Reserved event metadata is controlled by the top-level request fields. Accepts JSON, @file, or @-."),
			cli.String("mode", "").Help("`preview` evaluates matches without persistence; `deliver` persists a synthetic integration event a…"),
			cli.String("payload", "").Help("Canonical event payload. When sample_id is set, this replaces the sample payload. Accepts JSON, @file, or @-."),
			cli.String("provider", "").Help("Provider name. Defaults to the sample provider or the event_type prefix."),
			cli.String("sample-id", "").Help("Optional sample id to prefill provider, event_type, payload, and meta."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateIntegrationEventTestFireJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("dedup-key") {
				v := ctx.String("dedup-key")
				body.DedupKey = &v
			}
			if ctx.IsSet("event-type") {
				v := ctx.String("event-type")
				body.EventType = &v
			}
			if ctx.IsSet("integration-id") {
				v := ctx.String("integration-id")
				body.IntegrationId = &v
			}
			if ctx.IsSet("meta") {
				if err := decodeFlagJSON(ctx, "meta", ctx.String("meta"), &body.Meta); err != nil {
					return err
				}
			}
			if ctx.IsSet("mode") {
				v := api.IntegrationEventFireMode(ctx.String("mode"))
				body.Mode = &v
			}
			if ctx.IsSet("payload") {
				if err := decodeFlagJSON(ctx, "payload", ctx.String("payload"), &body.Payload); err != nil {
					return err
				}
			}
			if ctx.IsSet("provider") {
				v := ctx.String("provider")
				body.Provider = &v
			}
			if ctx.IsSet("sample-id") {
				v := ctx.String("sample-id")
				body.SampleId = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("dedup-key") && !ctx.IsSet("event-type") && !ctx.IsSet("integration-id") && !ctx.IsSet("meta") && !ctx.IsSet("mode") && !ctx.IsSet("payload") && !ctx.IsSet("provider") && !ctx.IsSet("sample-id") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateIntegrationEventTestFireWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createIntegrationEventTestFire", resp.StatusCode(), resp.Body)
		})

}
