// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerRolesCommands registers every generated subcommand in the "roles" group.
func registerRolesCommands(app *cli.App) {
	rolesGrp := app.Group("roles")
	rolesGrp.Command("create").
		Description("Create a custom role").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			var body api.CreateRoleJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.CreateRoleWithResponse(ctx.Context(), body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("create-assignment").
		Description("Create a role assignment").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			var body api.CreateRoleAssignmentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.CreateRoleAssignmentWithResponse(ctx.Context(), body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("delete").
		Description("Delete a custom role").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.DeleteRoleWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("delete-assignment").
		Description("Delete a role assignment").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.DeleteRoleAssignmentWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("get").
		Description("Get a role").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.GetRoleWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("list").
		Description("List roles").
		Flags(
			cli.Int("limit", "").Help("limit"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			params := &api.ListRolesParams{}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			resp, err := client.ListRolesWithResponse(ctx.Context(), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("list-assignments").
		Description("List role assignments").
		Flags(
			cli.String("actor-type", "").Help("actor-type"),
			cli.String("actor-id", "").Help("actor-id"),
			cli.String("role-id", "").Help("role-id"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			params := &api.ListRoleAssignmentsParams{}
			if ctx.IsSet("actor-type") {
				v := api.ListRoleAssignmentsParamsActorType(ctx.String("actor-type"))
				params.ActorType = &v
			}
			if ctx.IsSet("actor-id") {
				v := ctx.String("actor-id")
				params.ActorId = &v
			}
			if ctx.IsSet("role-id") {
				v := ctx.String("role-id")
				params.RoleId = &v
			}
			resp, err := client.ListRoleAssignmentsWithResponse(ctx.Context(), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("update").
		Description("Update a custom role").
		Args("id").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			var body api.UpdateRoleJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.UpdateRoleWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
