// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerRolesCommands registers every generated subcommand in the "roles" group.
func registerRolesCommands(app *cli.App) {
	rolesGrp := app.Group("roles").Description("Project roles and assignments")
	rolesGrp.Alias("role")
	rolesGrp.Command("create").
		Description("Create role").
		Flags(
			cli.String("description", "").Help("Optional human-readable description of what this role grants."),
			cli.String("name", "").Help("[required] Unique name within the project."),
			cli.Strings("permissions", "").Help("[required] Permission strings to include. Source allowed values from `GET /v1/projects/{project_handle}/permissions`; legacy IDs or values not present…"),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateRoleJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("permissions") {
				v := ctx.Strings("permissions")
				body.Permissions = v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if len(body.Permissions) == 0 {
				return fmt.Errorf("--permissions is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateRoleWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createRole", resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("create-assignment").
		Description("Create role assignment").
		Flags(
			cli.String("principal-id", "").Help("[required] Principal ID to assign the role to (human or machine)."),
			cli.String("role-id", "").Help("Mutually exclusive with `role_name`."),
			cli.String("role-name", "").Help("Resolved to a role ID server-side. Mutually exclusive with `role_id`."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateRoleAssignmentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("principal-id") {
				body.PrincipalId = ctx.String("principal-id")
			}
			if ctx.IsSet("role-id") {
				v := ctx.String("role-id")
				body.RoleId = &v
			}
			if ctx.IsSet("role-name") {
				v := ctx.String("role-name")
				body.RoleName = &v
			}
			if body.PrincipalId == "" {
				return fmt.Errorf("--principal-id is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateRoleAssignmentWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createRoleAssignment", resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("delete").
		Description("Delete role").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteRoleWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteRole", resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("delete-assignment").
		Description("Delete role assignment").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteRoleAssignmentWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteRoleAssignment", resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("get").
		Description("Get role").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetRoleWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getRole", resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("list").
		Description("List roles").
		Flags(
			cli.Int("limit", "").Help("Maximum number of items to return"),
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListRolesParams{}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			resp, err := client.ListRolesWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listRoles", resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("list-assignments").
		Description("List role assignments").
		Flags(
			cli.String("principal-id", "").Help("Filter to assignments for a specific principal."),
			cli.String("role-id", "").Help("Filter to assignments for a specific role."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListRoleAssignmentsParams{}
			if ctx.IsSet("principal-id") {
				v := ctx.String("principal-id")
				params.PrincipalId = &v
			}
			if ctx.IsSet("role-id") {
				v := ctx.String("role-id")
				params.RoleId = &v
			}
			resp, err := client.ListRoleAssignmentsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listRoleAssignments", resp.StatusCode(), resp.Body)
		})

	rolesGrp.Command("update").
		Description("Update role").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Flags(
			cli.String("description", "").Help("Replacement description."),
			cli.Strings("permissions", "").Help("Replaces the existing permissions array entirely. Source allowed values from `GET /v1/projects/{project_handle}/permissions`; legacy IDs or…"),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateRoleJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("permissions") {
				v := ctx.Strings("permissions")
				body.Permissions = &v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("description") && !ctx.IsSet("permissions") && !ctx.IsSet("tag") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateRoleWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateRole", resp.StatusCode(), resp.Body)
		})

}
