// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"
)

// registerIntegrationCatalogCommands registers every generated subcommand in the "integration-catalog" group.
func registerIntegrationCatalogCommands(app *cli.App) {
	integrationCatalogGrp := app.Group("integration-catalog").Description("Available integration providers and capabilities")
	integrationCatalogGrp.Command("list-providers").
		Description("List available integration providers and their capabilities").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			resp, err := client.ListIntegrationProvidersWithResponse(ctx.Context())
			if err != nil {
				return err
			}
			return printResponse(ctx, "listIntegrationProviders", resp.StatusCode(), resp.Body)
		})

}
