// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerChannelsCommands registers every generated subcommand in the "channels" group.
func registerChannelsCommands(app *cli.App) {
	channelsGrp := app.Group("channels").Description("Chat channels, members, and messages")
	channelsGrp.Alias("channel")
	channelsGrp.Command("add-member").
		Description("Add a member to a channel").
		Args("id").
		Flags(
			cli.String("participant-id", "").Help("[required] User or agent ID to add to the channel."),
			cli.String("role", "").Help("Role to assign the new member, either `member` or `admin`."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.AddChannelMemberJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("participant-id") {
				body.ParticipantId = ctx.String("participant-id")
			}
			if ctx.IsSet("role") {
				v := api.AddChannelMemberRequestRole(ctx.String("role"))
				body.Role = &v
			}
			if body.ParticipantId == "" {
				return fmt.Errorf("--participant-id is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.AddChannelMemberWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "addChannelMember", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("associate-interaction").
		Description("Associate an interaction with a channel").
		Args("id").
		Flags(
			cli.String("interaction-id", "").Help("[required] Existing same-project interaction ID to associate."),
			cli.String("relation", "").Help("Relation between the channel and interaction."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.AssociateChannelInteractionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("interaction-id") {
				body.InteractionId = ctx.String("interaction-id")
			}
			if ctx.IsSet("relation") {
				v := api.AssociateChannelInteractionRequestRelation(ctx.String("relation"))
				body.Relation = &v
			}
			if body.InteractionId == "" {
				return fmt.Errorf("--interaction-id is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.AssociateChannelInteractionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "associateChannelInteraction", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("claim-interaction").
		Description("Claim an interaction from a channel").
		Args("id", "interaction-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.ClaimChannelInteractionWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "claimChannelInteraction", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("create").
		Description("Create a channel").
		Flags(
			cli.Strings("associated-interaction-ids", "").Help("Existing same-project interaction IDs to link as the channel's purpose at creation time. Required w…"),
			cli.String("completion-behavior", "").Help("completion-behavior"),
			cli.String("display-name", "").Help("[required] Human-facing display name shown in the UI."),
			cli.String("kind", "").Help("[required] Channel kind, either `dm` or `channel`. Cannot be changed after creation."),
			cli.Strings("member-ids", "").Help("Optional list of user or agent IDs to add as members at creation time. All receive the `member` rol…"),
			cli.String("name", "").Help("[required] URL-safe handle, unique within the project. Immutable after creation — choose carefully."),
			cli.Bool("private", "").Help("When true, the channel is invite-only."),
			cli.String("purpose", "").Help("Optional purpose for the channel."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("topic", "").Help("Optional channel topic or description."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateChannelJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("associated-interaction-ids") {
				v := ctx.Strings("associated-interaction-ids")
				body.AssociatedInteractionIds = &v
			}
			if ctx.IsSet("completion-behavior") {
				v := api.ChannelCompletionBehavior(ctx.String("completion-behavior"))
				body.CompletionBehavior = &v
			}
			if ctx.IsSet("display-name") {
				body.DisplayName = ctx.String("display-name")
			}
			if ctx.IsSet("kind") {
				body.Kind = api.CreateChannelRequestKind(ctx.String("kind"))
			}
			if ctx.IsSet("member-ids") {
				v := ctx.Strings("member-ids")
				body.MemberIds = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("private") {
				v := ctx.Bool("private")
				body.Private = &v
			}
			if ctx.IsSet("purpose") {
				v := api.CreateChannelRequestPurpose(ctx.String("purpose"))
				body.Purpose = &v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("topic") {
				v := ctx.String("topic")
				body.Topic = &v
			}
			if body.DisplayName == "" {
				return fmt.Errorf("--display-name is required (or supply it via --file)")
			}
			if body.Kind == "" {
				return fmt.Errorf("--kind is required (or supply it via --file)")
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateChannelWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createChannel", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("delete").
		Description("Delete a channel").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteChannelWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteChannel", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("get").
		Description("Get a channel").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetChannelWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getChannel", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("get-block-catalog").
		Description("Get the channel message block catalog").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			resp, err := client.GetChannelBlockCatalogWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getChannelBlockCatalog", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("list").
		Description("List channels").
		Flags(
			cli.String("kind", "").Help("Filter by channel kind."),
			cli.Bool("private", "").Help("Filter by private flag."),
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListChannelsParams{}
			if ctx.IsSet("kind") {
				v := api.ListChannelsParamsKind(ctx.String("kind"))
				params.Kind = &v
			}
			if ctx.IsSet("private") {
				v := ctx.Bool("private")
				params.Private = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListChannelsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listChannels", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("list-interactions").
		Description("List channel interaction links").
		Args("id").
		Flags(
			cli.String("relation", "").Help("Filter by association relation."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListChannelInteractionsParams{}
			if ctx.IsSet("relation") {
				v := api.ListChannelInteractionsParamsRelation(ctx.String("relation"))
				params.Relation = &v
			}
			resp, err := client.ListChannelInteractionsWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listChannelInteractions", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("list-members").
		Description("List channel members").
		Args("id").
		Flags(
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListChannelMembersParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListChannelMembersWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listChannelMembers", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("open-direct-message").
		Description("Open a direct-message channel").
		Flags(
			cli.String("display-name", "").Help("Human-facing display name for the channel. Defaults to the participant's name or ID when omitted. O…"),
			cli.String("participant-id", "").Help("[required] User or agent ID of the other DM participant."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.OpenDirectMessageJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("display-name") {
				v := ctx.String("display-name")
				body.DisplayName = &v
			}
			if ctx.IsSet("participant-id") {
				body.ParticipantId = ctx.String("participant-id")
			}
			if body.ParticipantId == "" {
				return fmt.Errorf("--participant-id is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.OpenDirectMessageWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "openDirectMessage", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("release-interaction").
		Description("Release an interaction claim from a channel").
		Args("id", "interaction-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.ReleaseChannelInteractionWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "releaseChannelInteraction", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("remove-interaction").
		Description("Remove a channel interaction association").
		Args("id", "interaction-id").
		Flags(
			cli.String("relation", "").Help("Relation to remove. Defaults to `purpose`."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			params := &api.RemoveChannelInteractionParams{}
			if ctx.IsSet("relation") {
				v := api.RemoveChannelInteractionParamsRelation(ctx.String("relation"))
				params.Relation = &v
			}
			resp, err := client.RemoveChannelInteractionWithResponse(ctx.Context(), p0, p1, p2, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "removeChannelInteraction", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("remove-member").
		Description("Remove a member from a channel").
		Args("id", "member-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.RemoveChannelMemberWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "removeChannelMember", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("respond-to-interaction").
		Description("Respond to an interaction from a channel").
		Args("id", "interaction-id").
		Flags(
			cli.String("comment", "").Help("Optional human-readable comment to show in channel activity."),
			cli.String("value", "").Help("[required] Free-form JSON payload. Used both for responder-supplied values and for policy-derived values (e.g.… Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			var body api.RespondToChannelInteractionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("comment") {
				v := ctx.String("comment")
				body.Comment = &v
			}
			if ctx.IsSet("value") {
				if err := decodeFlagJSON(ctx, "value", ctx.String("value"), &body.Value); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("value") {
				return fmt.Errorf("--value is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.RespondToChannelInteractionWithResponse(ctx.Context(), p0, p1, p2, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "respondToChannelInteraction", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("share-entity").
		Description("Share an entity in a channel").
		Args("id").
		Flags(
			cli.String("content", "").Help("Optional Markdown fallback body. If omitted, the server derives a short label from the reference."),
			cli.String("display", "").Help("Rendering hint for the created channel message."),
			cli.String("metadata", "").Help("Free-form JSON object for caller-defined metadata. Accepts JSON, @file, or @-."),
			cli.String("reference", "").Help("[required] Experimental typed link from a channel message to another Mobius entity. Clients use references to … Accepts JSON, @file, or @-."),
			cli.String("type", "").Help("Optional dot-namespaced message type. If omitted, the server derives one from the entity type."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.ShareChannelEntityJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("content") {
				v := ctx.String("content")
				body.Content = &v
			}
			if ctx.IsSet("display") {
				v := api.ShareChannelEntityRequestDisplay(ctx.String("display"))
				body.Display = &v
			}
			if ctx.IsSet("metadata") {
				if err := decodeFlagJSON(ctx, "metadata", ctx.String("metadata"), &body.Metadata); err != nil {
					return err
				}
			}
			if ctx.IsSet("reference") {
				if err := decodeFlagJSON(ctx, "reference", ctx.String("reference"), &body.Reference); err != nil {
					return err
				}
			}
			if ctx.IsSet("type") {
				v := ctx.String("type")
				body.Type = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("reference") {
				return fmt.Errorf("--reference is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.ShareChannelEntityWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "shareChannelEntity", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("update").
		Description("Update a channel").
		Args("id").
		Flags(
			cli.String("completion-behavior", "").Help("Behavior to apply when every purpose-linked interaction is terminal."),
			cli.String("display-name", "").Help("Updated display name."),
			cli.Bool("private", "").Help("Toggle invite-only visibility."),
			cli.String("purpose", "").Help("Channel purpose. `resolve_interactions` requires at least one purpose-linked interaction."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("topic", "").Help("Updated topic or description."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateChannelJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("completion-behavior") {
				v := api.ChannelCompletionBehavior(ctx.String("completion-behavior"))
				body.CompletionBehavior = &v
			}
			if ctx.IsSet("display-name") {
				v := ctx.String("display-name")
				body.DisplayName = &v
			}
			if ctx.IsSet("private") {
				v := ctx.Bool("private")
				body.Private = &v
			}
			if ctx.IsSet("purpose") {
				v := api.UpdateChannelRequestPurpose(ctx.String("purpose"))
				body.Purpose = &v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("topic") {
				v := ctx.String("topic")
				body.Topic = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("completion-behavior") && !ctx.IsSet("display-name") && !ctx.IsSet("private") && !ctx.IsSet("purpose") && !ctx.IsSet("tag") && !ctx.IsSet("topic") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateChannelWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateChannel", resp.StatusCode(), resp.Body)
		})

}
