// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerAgentsCommands registers every generated subcommand in the "agents" group.
func registerAgentsCommands(app *cli.App) {
	agentsGrp := app.Group("agents").Description("Agents and agent sessions")
	agentsGrp.Alias("agent")
	agentsGrp.Command("create-session").
		Description("Register a new agent session").
		Args("id").
		Flags(
			cli.String("metadata", "").Help("Optional metadata such as hostname, SDK version, or region. Accepts JSON, @file, or @-."),
			cli.String("transport", "").Help("[required] Connection mechanism identifier (e.g. \"sse\", \"polling\")."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.CreateAgentSessionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("metadata") {
				if err := decodeFlagJSON(ctx, "metadata", ctx.String("metadata"), &body.Metadata); err != nil {
					return err
				}
			}
			if ctx.IsSet("transport") {
				body.Transport = ctx.String("transport")
			}
			if body.Transport == "" {
				return fmt.Errorf("--transport is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateAgentSessionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createAgentSession", resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("delete").
		Description("Delete an agent").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteAgentWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteAgent", resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("disconnect-session").
		Description("Mark an agent session as disconnected").
		Args("id", "session-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.DisconnectAgentSessionWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "disconnectAgentSession", resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("get").
		Description("Get an agent").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetAgentWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getAgent", resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("get-session").
		Description("Get an agent session").
		Args("id", "session-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.GetAgentSessionWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getAgentSession", resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("heartbeat-session").
		Description("Refresh an agent session heartbeat").
		Args("id", "session-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.HeartbeatAgentSessionWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "heartbeatAgentSession", resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("list").
		Description("List agents").
		Flags(
			cli.String("service-account-id", "").Help("Filter to agents backed by this service account."),
			cli.String("status", "").Help("Filter by administrative status (active/inactive), independent of presence."),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListAgentsParams{}
			if ctx.IsSet("service-account-id") {
				v := ctx.String("service-account-id")
				params.ServiceAccountId = &v
			}
			if ctx.IsSet("status") {
				v := api.AgentStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListAgentsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAgents", resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("list-sessions").
		Description("List sessions for an agent").
		Args("id").
		Flags(
			cli.String("status", "").Help("Filter by session status."),
			cli.String("transport", "").Help("Filter by transport type (e.g. \"sse\", \"polling\")."),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListAgentSessionsParams{}
			if ctx.IsSet("status") {
				v := api.AgentSessionStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("transport") {
				v := ctx.String("transport")
				params.Transport = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListAgentSessionsWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAgentSessions", resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("update").
		Description("Update an agent").
		Args("id").
		Flags(
			cli.String("capabilities", "").Help("Replacement capability map. Accepts JSON, @file, or @-."),
			cli.String("config", "").Help("Replacement configuration blob. Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Replacement description."),
			cli.String("kind", "").Help("Replacement freeform agent classification (e.g. `llm`, `rpa`)."),
			cli.String("name", "").Help("Free-form human-readable label, 1-63 characters; must be unique within the project."),
			cli.String("service-account-id", "").Help("Replacement service account. Must be active and belong to the same project."),
			cli.String("status", "").Help("Administrative status. Inactive agents cannot claim new jobs."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateAgentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("capabilities") {
				if err := decodeFlagJSON(ctx, "capabilities", ctx.String("capabilities"), &body.Capabilities); err != nil {
					return err
				}
			}
			if ctx.IsSet("config") {
				if err := decodeFlagJSON(ctx, "config", ctx.String("config"), &body.Config); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("kind") {
				v := ctx.String("kind")
				body.Kind = &v
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("service-account-id") {
				v := ctx.String("service-account-id")
				body.ServiceAccountId = &v
			}
			if ctx.IsSet("status") {
				v := api.AgentStatus(ctx.String("status"))
				body.Status = &v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("capabilities") && !ctx.IsSet("config") && !ctx.IsSet("description") && !ctx.IsSet("kind") && !ctx.IsSet("name") && !ctx.IsSet("service-account-id") && !ctx.IsSet("status") && !ctx.IsSet("tag") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateAgentWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateAgent", resp.StatusCode(), resp.Body)
		})

}
