// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerProjectsCommands registers every generated subcommand in the "projects" group.
func registerProjectsCommands(app *cli.App) {
	projectsGrp := app.Group("projects")
	projectsGrp.Alias("project")
	projectsGrp.Command("create").
		Description("Create a project").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			var body api.CreateProjectJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.CreateProjectWithResponse(ctx.Context(), body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("delete").
		Description("Delete a project").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.DeleteProjectWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("get").
		Description("Get a project by id").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.GetProjectWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("list").
		Description("List projects in the org").
		Flags(
			cli.String("search", "").Help("search"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			params := &api.ListProjectsParams{}
			if ctx.IsSet("search") {
				v := ctx.String("search")
				params.Search = &v
			}
			resp, err := client.ListProjectsWithResponse(ctx.Context(), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("update").
		Description("Update a project").
		Args("id").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			var body api.UpdateProjectJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.UpdateProjectWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
