// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerEnvironmentsCommands registers every generated subcommand in the "environments" group.
func registerEnvironmentsCommands(app *cli.App) {
	environmentsGrp := app.Group("environments")
	environmentsGrp.Alias("environment")
	environmentsGrp.Command("acquire-environment").
		Description("Acquire an environment lease").
		Flags(
			cli.String("environment-id", "").Help("environment-id"),
			cli.String("holder-id", "").Help("holder-id"),
			cli.String("holder-type", "").Help("holder-type"),
			cli.String("lease-ttl", "").Help("Go duration string, for example 30m or 2h."),
			cli.String("name", "").Help("name"),
			cli.String("owner-id", "").Help("owner-id"),
			cli.String("owner-type", "").Help("owner-type"),
			cli.String("provider", "").Help("provider"),
			cli.String("purpose", "").Help("purpose"),
			cli.String("spec", "").Help("spec Accepts JSON, @file, or @-."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("template-id", "").Help("V1 supports only coding-default."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.AcquireEnvironmentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("environment-id") {
				v := ctx.String("environment-id")
				body.EnvironmentId = &v
			}
			if ctx.IsSet("holder-id") {
				v := ctx.String("holder-id")
				body.HolderId = &v
			}
			if ctx.IsSet("holder-type") {
				v := api.EnvironmentOwnerType(ctx.String("holder-type"))
				body.HolderType = &v
			}
			if ctx.IsSet("lease-ttl") {
				v := ctx.String("lease-ttl")
				body.LeaseTtl = &v
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("owner-id") {
				v := ctx.String("owner-id")
				body.OwnerId = &v
			}
			if ctx.IsSet("owner-type") {
				v := api.EnvironmentOwnerType(ctx.String("owner-type"))
				body.OwnerType = &v
			}
			if ctx.IsSet("provider") {
				v := api.EnvironmentProvider(ctx.String("provider"))
				body.Provider = &v
			}
			if ctx.IsSet("purpose") {
				v := api.EnvironmentPurpose(ctx.String("purpose"))
				body.Purpose = &v
			}
			if ctx.IsSet("spec") {
				if err := decodeFlagJSON(ctx, "spec", ctx.String("spec"), &body.Spec); err != nil {
					return err
				}
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("template-id") {
				v := api.AcquireEnvironmentRequestTemplateId(ctx.String("template-id"))
				body.TemplateId = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("environment-id") && !ctx.IsSet("holder-id") && !ctx.IsSet("holder-type") && !ctx.IsSet("lease-ttl") && !ctx.IsSet("name") && !ctx.IsSet("owner-id") && !ctx.IsSet("owner-type") && !ctx.IsSet("provider") && !ctx.IsSet("purpose") && !ctx.IsSet("spec") && !ctx.IsSet("tag") && !ctx.IsSet("template-id") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.AcquireEnvironmentWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "acquireEnvironment", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("create").
		Description("Create an environment").
		Flags(
			cli.String("name", "").Help("name"),
			cli.String("owner-id", "").Help("owner-id"),
			cli.String("owner-type", "").Help("owner-type"),
			cli.String("provider", "").Help("provider"),
			cli.String("purpose", "").Help("purpose"),
			cli.String("retention-policy", "").Help("retention-policy"),
			cli.String("spec", "").Help("spec Accepts JSON, @file, or @-."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("template-id", "").Help("V1 supports only coding-default."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateEnvironmentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("owner-id") {
				v := ctx.String("owner-id")
				body.OwnerId = &v
			}
			if ctx.IsSet("owner-type") {
				v := api.EnvironmentOwnerType(ctx.String("owner-type"))
				body.OwnerType = &v
			}
			if ctx.IsSet("provider") {
				v := api.EnvironmentProvider(ctx.String("provider"))
				body.Provider = &v
			}
			if ctx.IsSet("purpose") {
				v := api.EnvironmentPurpose(ctx.String("purpose"))
				body.Purpose = &v
			}
			if ctx.IsSet("retention-policy") {
				v := api.EnvironmentRetentionPolicy(ctx.String("retention-policy"))
				body.RetentionPolicy = &v
			}
			if ctx.IsSet("spec") {
				if err := decodeFlagJSON(ctx, "spec", ctx.String("spec"), &body.Spec); err != nil {
					return err
				}
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("template-id") {
				v := api.CreateEnvironmentRequestTemplateId(ctx.String("template-id"))
				body.TemplateId = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("name") && !ctx.IsSet("owner-id") && !ctx.IsSet("owner-type") && !ctx.IsSet("provider") && !ctx.IsSet("purpose") && !ctx.IsSet("retention-policy") && !ctx.IsSet("spec") && !ctx.IsSet("tag") && !ctx.IsSet("template-id") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateEnvironmentWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createEnvironment", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("destroy-environment").
		Description("Destroy an environment").
		Args("environment-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DestroyEnvironmentWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "destroyEnvironment", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("exec-environment").
		Description("Execute a command inside an environment").
		Args("environment-id").
		Flags(
			cli.Strings("command", "").Help("[required] command"),
			cli.String("dir", "").Help("dir"),
			cli.Strings("env", "").Help("env"),
			cli.String("stdin", "").Help("stdin"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.ExecEnvironmentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("command") {
				body.Command = ctx.Strings("command")
			}
			if ctx.IsSet("dir") {
				v := ctx.String("dir")
				body.Dir = &v
			}
			if ctx.IsSet("env") {
				v := ctx.Strings("env")
				body.Env = &v
			}
			if ctx.IsSet("stdin") {
				v := ctx.String("stdin")
				body.Stdin = &v
			}
			if len(body.Command) == 0 {
				return fmt.Errorf("--command is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.ExecEnvironmentWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "execEnvironment", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("get").
		Description("Get an environment").
		Args("environment-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetEnvironmentWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getEnvironment", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("list").
		Description("List environments").
		Flags(
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
			cli.String("provider", "").Help("provider"),
			cli.String("status", "").Help("status"),
			cli.String("purpose", "").Help("purpose"),
			cli.String("owner-type", "").Help("owner-type"),
			cli.String("owner-id", "").Help("owner-id"),
			cli.Bool("include-destroyed", "").Help("Include destroyed environments in the result. By default destroyed rows are excluded; set this to t…"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListEnvironmentsParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			if ctx.IsSet("provider") {
				v := api.EnvironmentProvider(ctx.String("provider"))
				params.Provider = &v
			}
			if ctx.IsSet("status") {
				v := api.EnvironmentStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("purpose") {
				v := api.EnvironmentPurpose(ctx.String("purpose"))
				params.Purpose = &v
			}
			if ctx.IsSet("owner-type") {
				v := api.EnvironmentOwnerType(ctx.String("owner-type"))
				params.OwnerType = &v
			}
			if ctx.IsSet("owner-id") {
				v := ctx.String("owner-id")
				params.OwnerId = &v
			}
			if ctx.IsSet("include-destroyed") {
				v := ctx.Bool("include-destroyed")
				params.IncludeDestroyed = &v
			}
			resp, err := client.ListEnvironmentsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listEnvironments", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("reconcile-environment").
		Description("Reconcile environment provider state").
		Args("environment-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ReconcileEnvironmentWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "reconcileEnvironment", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("release-environment-lease").
		Description("Release an environment lease").
		Args("lease-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ReleaseEnvironmentLeaseWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "releaseEnvironmentLease", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("start-environment-worker").
		Description("Start a Mobius worker in an environment").
		Args("environment-id").
		Flags(
			cli.Strings("command", "").Help("command"),
			cli.String("dir", "").Help("dir"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.StartEnvironmentWorkerJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("command") {
				v := ctx.Strings("command")
				body.Command = &v
			}
			if ctx.IsSet("dir") {
				v := ctx.String("dir")
				body.Dir = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("command") && !ctx.IsSet("dir") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.StartEnvironmentWorkerWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "startEnvironmentWorker", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("update").
		Description("Update environment metadata").
		Args("environment-id").
		Flags(
			cli.String("owner-id", "").Help("owner-id"),
			cli.String("owner-type", "").Help("owner-type"),
			cli.String("purpose", "").Help("purpose"),
			cli.String("retention-policy", "").Help("retention-policy"),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateEnvironmentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("owner-id") {
				v := ctx.String("owner-id")
				body.OwnerId = &v
			}
			if ctx.IsSet("owner-type") {
				v := api.EnvironmentOwnerType(ctx.String("owner-type"))
				body.OwnerType = &v
			}
			if ctx.IsSet("purpose") {
				v := api.EnvironmentPurpose(ctx.String("purpose"))
				body.Purpose = &v
			}
			if ctx.IsSet("retention-policy") {
				v := api.EnvironmentRetentionPolicy(ctx.String("retention-policy"))
				body.RetentionPolicy = &v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("owner-id") && !ctx.IsSet("owner-type") && !ctx.IsSet("purpose") && !ctx.IsSet("retention-policy") && !ctx.IsSet("tag") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateEnvironmentWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateEnvironment", resp.StatusCode(), resp.Body)
		})

	environmentsGrp.Command("write-environment-file").
		Description("Write a file into an environment").
		Args("environment-id").
		Flags(
			cli.String("content", "").Help("[required] content"),
			cli.String("path", "").Help("[required] path"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.WriteEnvironmentFileJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("content") {
				body.Content = ctx.String("content")
			}
			if ctx.IsSet("path") {
				body.Path = ctx.String("path")
			}
			if body.Content == "" {
				return fmt.Errorf("--content is required (or supply it via --file)")
			}
			if body.Path == "" {
				return fmt.Errorf("--path is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.WriteEnvironmentFileWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "writeEnvironmentFile", resp.StatusCode(), resp.Body)
		})

}
