// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerInteractionsCommands registers every generated subcommand in the "interactions" group.
func registerInteractionsCommands(app *cli.App) {
	interactionsGrp := app.Group("interactions")
	interactionsGrp.Command("claim").
		Description("Claim a pending first-responder group interaction").
		Args("ns", "id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.ClaimInteractionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("create").
		Description("Create an interaction explicitly").
		Args("ns").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			var body api.CreateInteractionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.CreateInteractionWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("get").
		Description("Get an interaction").
		Args("ns", "id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.GetInteractionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("list").
		Description("List interactions").
		Args("ns").
		Flags(
			cli.String("status", "").Help("status"),
			cli.String("run-id", "").Help("run-id"),
			cli.String("target-actor-type", "").Help("target-actor-type"),
			cli.String("target-actor-id", "").Help("target-actor-id"),
			cli.Bool("inbox", "").Help("inbox"),
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			params := &api.ListInteractionsParams{}
			if ctx.IsSet("status") {
				v := api.ListInteractionsParamsStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("run-id") {
				v := ctx.String("run-id")
				params.RunId = &v
			}
			if ctx.IsSet("target-actor-type") {
				v := api.ListInteractionsParamsTargetActorType(ctx.String("target-actor-type"))
				params.TargetActorType = &v
			}
			if ctx.IsSet("target-actor-id") {
				v := ctx.String("target-actor-id")
				params.TargetActorId = &v
			}
			if ctx.IsSet("inbox") {
				v := ctx.Bool("inbox")
				params.Inbox = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListInteractionsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("release-interaction").
		Description("Release a claimed first-responder group interaction").
		Args("ns", "id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.ReleaseInteractionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("respond-to-interaction").
		Description("Submit a response to an interaction").
		Args("ns", "id").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			var body api.RespondToInteractionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.RespondToInteractionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
