// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerReferencesCommands registers every generated subcommand in the "references" group.
func registerReferencesCommands(app *cli.App) {
	referencesGrp := app.Group("references")
	referencesGrp.Alias("reference")
	referencesGrp.Command("lookup-references").
		Description("Look up reference candidates").
		Args("reference-type").
		Flags(
			cli.String("q", "").Help("Human search query."),
			cli.Int("limit", "").Help("Maximum number of candidates to return. Defaults to 20 and is capped at 100."),
			cli.String("cursor", "").Help("Opaque pagination cursor from a previous response."),
			cli.String("integration-id", "").Help("Optional provider integration instance selector for projects with multiple connections."),
			cli.String("depends-on", "").Help("Optional JSON object containing values from fields this lookup depends on."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.LookupReferencesParams{}
			if ctx.IsSet("q") {
				v := ctx.String("q")
				params.Q = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				params.Cursor = &v
			}
			if ctx.IsSet("integration-id") {
				v := ctx.String("integration-id")
				params.IntegrationId = &v
			}
			if ctx.IsSet("depends-on") {
				v := ctx.String("depends-on")
				params.DependsOn = &v
			}
			resp, err := client.LookupReferencesWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "lookupReferences", resp.StatusCode(), resp.Body)
		})

	referencesGrp.Command("resolve-references").
		Description("Resolve saved reference values").
		Args("reference-type").
		Flags(
			cli.String("depends-on", "").Help("depends-on Accepts JSON, @file, or @-."),
			cli.String("integration-id", "").Help("integration-id"),
			cli.Strings("values", "").Help("[required] values"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.ResolveReferencesJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("depends-on") {
				if err := decodeFlagJSON(ctx, "depends-on", ctx.String("depends-on"), &body.DependsOn); err != nil {
					return err
				}
			}
			if ctx.IsSet("integration-id") {
				v := ctx.String("integration-id")
				body.IntegrationId = &v
			}
			if ctx.IsSet("values") {
				body.Values = ctx.Strings("values")
			}
			if len(body.Values) == 0 {
				return fmt.Errorf("--values is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.ResolveReferencesWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "resolveReferences", resp.StatusCode(), resp.Body)
		})

}
