// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerUserStateCommands registers every generated subcommand in the "user-state" group.
func registerUserStateCommands(app *cli.App) {
	userStateGrp := app.Group("user-state").Description("Per-user project state and assignments")
	userStateGrp.Command("get").
		Description("Get user state").
		Args("user-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetUserStateWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getUserState", resp.StatusCode(), resp.Body)
		})

	userStateGrp.Command("list").
		Description("List user state").
		Flags(
			cli.String("user-kind", "").Help("user-kind"),
			cli.String("availability", "").Help("availability"),
			cli.String("visibility", "").Help("visibility"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListUserStatesParams{}
			if ctx.IsSet("user-kind") {
				v := api.UserKind(ctx.String("user-kind"))
				params.UserKind = &v
			}
			if ctx.IsSet("availability") {
				v := api.UserAvailability(ctx.String("availability"))
				params.Availability = &v
			}
			if ctx.IsSet("visibility") {
				v := api.UserStateVisibility(ctx.String("visibility"))
				params.Visibility = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListUserStatesWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listUserStates", resp.StatusCode(), resp.Body)
		})

	userStateGrp.Command("list-assignments").
		Description("List user assignments").
		Flags(
			cli.String("status", "").Help("status"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListUserAssignmentsParams{}
			if ctx.IsSet("status") {
				v := api.UserAssignmentStatus(ctx.String("status"))
				params.Status = &v
			}
			resp, err := client.ListUserAssignmentsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listUserAssignments", resp.StatusCode(), resp.Body)
		})

	userStateGrp.Command("upsert").
		Description("Upsert user state").
		Args("user-id").
		Flags(
			cli.String("assignments", "").Help("assignments Accepts JSON, @file, or @-."),
			cli.String("availability", "").Help("[required] availability"),
			cli.String("description", "").Help("description"),
			cli.String("expires-at", "").Help("expires-at Accepts JSON, @file, or @-."),
			cli.String("visibility", "").Help("visibility"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpsertUserStateJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("assignments") {
				if err := decodeFlagJSON(ctx, "assignments", ctx.String("assignments"), &body.Assignments); err != nil {
					return err
				}
			}
			if ctx.IsSet("availability") {
				body.Availability = api.UserAvailability(ctx.String("availability"))
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("expires-at") {
				if err := decodeFlagJSON(ctx, "expires-at", ctx.String("expires-at"), &body.ExpiresAt); err != nil {
					return err
				}
			}
			if ctx.IsSet("visibility") {
				v := api.UserStateVisibility(ctx.String("visibility"))
				body.Visibility = &v
			}
			if body.Availability == "" {
				return fmt.Errorf("--availability is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpsertUserStateWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "upsertUserState", resp.StatusCode(), resp.Body)
		})

}
