// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerAgentsCommands registers every generated subcommand in the "agents" group.
func registerAgentsCommands(app *cli.App) {
	agentsGrp := app.Group("agents")
	agentsGrp.Command("create").
		Description("Create an agent").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			var body api.CreateAgentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.CreateAgentWithResponse(ctx.Context(), body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("create-session").
		Description("Create an agent session").
		Args("id").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			var body api.CreateAgentSessionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.CreateAgentSessionWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("delete").
		Description("Delete an agent").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.DeleteAgentWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("disconnect-session").
		Description("Disconnect an agent session").
		Args("session-id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.DisconnectAgentSessionWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("get").
		Description("Get an agent").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.GetAgentWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("get-session").
		Description("Get an agent session").
		Args("session-id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.GetAgentSessionWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("heartbeat-agent-session").
		Description("Heartbeat an agent session").
		Args("session-id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.HeartbeatAgentSessionWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("list").
		Description("List agents").
		Flags(
			cli.String("service-account-id", "").Help("service-account-id"),
			cli.String("status", "").Help("status"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			params := &api.ListAgentsParams{}
			if ctx.IsSet("service-account-id") {
				v := ctx.String("service-account-id")
				params.ServiceAccountId = &v
			}
			if ctx.IsSet("status") {
				v := api.AgentStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListAgentsWithResponse(ctx.Context(), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("list-sessions").
		Description("List sessions for an agent").
		Args("id").
		Flags(
			cli.String("status", "").Help("status"),
			cli.String("transport", "").Help("transport"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			params := &api.ListAgentSessionsParams{}
			if ctx.IsSet("status") {
				v := api.AgentSessionStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("transport") {
				v := ctx.String("transport")
				params.Transport = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListAgentSessionsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	agentsGrp.Command("update").
		Description("Update an agent").
		Args("id").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			var body api.UpdateAgentJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.UpdateAgentWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
