// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/api"
)

// registerWebhooksCommands registers every generated subcommand in the "webhooks" group.
func registerWebhooksCommands(app *cli.App) {
	webhooksGrp := app.Group("webhooks")
	webhooksGrp.Command("create").
		Description("Create webhook").
		Args("ns").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			var body api.CreateWebhookJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.CreateWebhookWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("delete").
		Description("Delete webhook").
		Args("ns", "id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.DeleteWebhookWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("get").
		Description("Get webhook").
		Args("ns", "id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.GetWebhookWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("list").
		Description("List webhooks").
		Args("ns").
		Flags(
			cli.Bool("enabled", "").Help("enabled"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			params := &api.ListWebhooksParams{}
			if ctx.IsSet("enabled") {
				v := ctx.Bool("enabled")
				params.Enabled = &v
			}
			resp, err := client.ListWebhooksWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("list-events").
		Description("List webhook events").
		Args("ns", "id").
		Flags(
			cli.String("status", "").Help("status"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			params := &api.ListWebhookEventsParams{}
			if ctx.IsSet("status") {
				v := api.WebhookEventStatus(ctx.String("status"))
				params.Status = &v
			}
			resp, err := client.ListWebhookEventsWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	webhooksGrp.Command("update").
		Description("Update webhook").
		Args("ns", "id").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			var body api.UpdateWebhookJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.UpdateWebhookWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
