// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/api"
)

// registerTriggersCommands registers every generated subcommand in the "triggers" group.
func registerTriggersCommands(app *cli.App) {
	triggersGrp := app.Group("triggers")
	triggersGrp.Command("create").
		Description("Create a trigger").
		Args("ns").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			var body api.CreateTriggerJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.CreateTriggerWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	triggersGrp.Command("delete").
		Description("Delete a trigger").
		Args("ns", "id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.DeleteTriggerWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	triggersGrp.Command("get").
		Description("Get a trigger by id").
		Args("ns", "id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.GetTriggerWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	triggersGrp.Command("list").
		Description("List triggers in the namespace").
		Args("ns").
		Flags(
			cli.String("kind", "").Help("kind"),
			cli.Bool("enabled", "").Help("enabled"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			params := &api.ListTriggersParams{}
			if ctx.IsSet("kind") {
				v := api.TriggerKind(ctx.String("kind"))
				params.Kind = &v
			}
			if ctx.IsSet("enabled") {
				v := ctx.Bool("enabled")
				params.Enabled = &v
			}
			resp, err := client.ListTriggersWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	triggersGrp.Command("list-fires").
		Description("List fire history for a trigger").
		Args("ns", "id").
		Flags(
			cli.String("status", "").Help("status"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			params := &api.ListTriggerFiresParams{}
			if ctx.IsSet("status") {
				v := api.TriggerFireStatus(ctx.String("status"))
				params.Status = &v
			}
			resp, err := client.ListTriggerFiresWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	triggersGrp.Command("update").
		Description("Update a trigger").
		Args("ns", "id").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin)"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			client := clientFromContext(ctx).RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			var body api.UpdateTriggerJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			resp, err := client.UpdateTriggerWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
