// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerActionsCommands registers every generated subcommand in the "actions" group.
func registerActionsCommands(app *cli.App) {
	actionsGrp := app.Group("actions").Description("Actions available to loops and agents")
	actionsGrp.Alias("action")
	actionsGrp.Command("activate-organization-action-secret-version").
		Description("Activate an organization action secret version").
		Args("action-id", "secret-version").
		Flags(
			cli.Int("overlap-seconds", "").Help("Verification overlap for the previous active version. Omit for 24 hours."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			p1, err := parseInt64Arg(ctx.Arg(1), "secret-version")
			if err != nil {
				return err
			}
			var body api.ActivateOrganizationActionSecretVersionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("overlap-seconds") {
				v := ctx.Int("overlap-seconds")
				body.OverlapSeconds = &v
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.ActivateOrganizationActionSecretVersionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "activateOrganizationActionSecretVersion", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("create").
		Description("Create action").
		Flags(
			cli.String("annotations", "").Help("Request hints that describe the safe-use properties of the action. Used by the engine and tooling to decide retry behavior, dry-run… Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Markdown-safe description of what the action does."),
			cli.String("endpoint-kind", "").Help("Backing kind for the action. `http` actions POST to `endpoint_url` with a Mobius signature. `worker` actions are dispatched through jobs to…"),
			cli.String("endpoint-url", "").Help("Required when endpoint_kind is `http`; omitted for worker actions."),
			cli.String("input-schema", "").Help("JSON Schema describing the expected input parameters. Accepts JSON, @file, or @-."),
			cli.String("invocation-format", "").Help("Request-body contract for HTTP invocations. Omit to preserve the legacy body. `signed_context_v1` is valid only with `endpoint_kind: http`."),
			cli.String("name", "").Help("[required] Identifier used in loop step definitions. Lowercase alphanumeric + hyphens, e.g. \"send-email\". Must be unique within the project. Cannot…"),
			cli.String("output-schema", "").Help("JSON Schema describing the expected output shape. Accepts JSON, @file, or @-."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("title", "").Help("Human-readable display name shown in the UI and catalog."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateActionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("annotations") {
				if err := decodeFlagJSON(ctx, "annotations", ctx.String("annotations"), &body.Annotations); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("endpoint-kind") {
				v := api.ActionEndpointKind(ctx.String("endpoint-kind"))
				body.EndpointKind = &v
			}
			if ctx.IsSet("endpoint-url") {
				v := ctx.String("endpoint-url")
				body.EndpointUrl = &v
			}
			if ctx.IsSet("input-schema") {
				if err := decodeFlagJSON(ctx, "input-schema", ctx.String("input-schema"), &body.InputSchema); err != nil {
					return err
				}
			}
			if ctx.IsSet("invocation-format") {
				v := api.ActionInvocationFormat(ctx.String("invocation-format"))
				body.InvocationFormat = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("output-schema") {
				if err := decodeFlagJSON(ctx, "output-schema", ctx.String("output-schema"), &body.OutputSchema); err != nil {
					return err
				}
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("title") {
				v := ctx.String("title")
				body.Title = &v
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateActionWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createAction", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("create-action").
		Description("Create organization action").
		Flags(
			cli.String("annotations", "").Help("Request hints that describe the safe-use properties of the action. Used by the engine and tooling to decide retry behavior, dry-run… Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("description"),
			cli.Bool("enabled", "").Help("enabled"),
			cli.String("endpoint-url", "").Help("[required] endpoint-url"),
			cli.String("input-schema", "").Help("input-schema Accepts JSON, @file, or @-."),
			cli.String("invocation-format", "").Help("invocation-format"),
			cli.String("name", "").Help("[required] Canonical dotted name selected by project toolkits."),
			cli.String("output-schema", "").Help("output-schema Accepts JSON, @file, or @-."),
			cli.String("title", "").Help("title"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			var body api.CreateOrganizationActionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("annotations") {
				if err := decodeFlagJSON(ctx, "annotations", ctx.String("annotations"), &body.Annotations); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("enabled") {
				v := ctx.Bool("enabled")
				body.Enabled = &v
			}
			if ctx.IsSet("endpoint-url") {
				body.EndpointUrl = ctx.String("endpoint-url")
			}
			if ctx.IsSet("input-schema") {
				if err := decodeFlagJSON(ctx, "input-schema", ctx.String("input-schema"), &body.InputSchema); err != nil {
					return err
				}
			}
			if ctx.IsSet("invocation-format") {
				v := api.CreateOrganizationActionRequestInvocationFormat(ctx.String("invocation-format"))
				body.InvocationFormat = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("output-schema") {
				if err := decodeFlagJSON(ctx, "output-schema", ctx.String("output-schema"), &body.OutputSchema); err != nil {
					return err
				}
			}
			if ctx.IsSet("title") {
				v := ctx.String("title")
				body.Title = &v
			}
			if body.EndpointUrl == "" {
				return fmt.Errorf("--endpoint-url is required (or supply it via --file)")
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateOrganizationActionWithResponse(ctx.Context(), body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createOrganizationAction", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("delete").
		Description("Delete action").
		AddArg(&cli.Arg{Name: "action-name", Description: "Action name used in loop step definitions.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteActionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteAction", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("delete-action").
		Description("Delete organization action").
		AddArg(&cli.Arg{Name: "action-id", Description: "Organization action ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.DeleteOrganizationActionWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteOrganizationAction", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("get-action").
		Description("Get organization action").
		AddArg(&cli.Arg{Name: "action-id", Description: "Organization action ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.GetOrganizationActionWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getOrganizationAction", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("invoke").
		Description("Invoke action").
		AddArg(&cli.Arg{Name: "action-name", Description: "Action name used in loop step definitions.", Required: true}).
		Flags(
			cli.String("input", "").Help("Input values matching the action's input_schema. Accepts JSON, @file, or @-."),
			cli.Int("timeout-seconds", "").Help("How long (in seconds) to wait for synchronous completion. Default 30, max 120."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.InvokeActionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("input") {
				if err := decodeFlagJSON(ctx, "input", ctx.String("input"), &body.Input); err != nil {
					return err
				}
			}
			if ctx.IsSet("timeout-seconds") {
				v := ctx.Int("timeout-seconds")
				body.TimeoutSeconds = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("input") && !ctx.IsSet("timeout-seconds") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.InvokeActionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "invokeAction", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("list-actions").
		Description("List organization actions").
		Flags(
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
			cli.Int("limit", "").Help("Maximum number of items to return"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			params := &api.ListOrganizationActionsParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListOrganizationActionsWithResponse(ctx.Context(), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listOrganizationActions", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("list-invocations").
		Description("List invocations").
		Flags(
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
			cli.Int("limit", "").Help("Maximum number of items to return"),
			cli.String("run-id", "").Help("Filter to invocations from a specific loop run."),
			cli.String("job-id", "").Help("Filter to invocations from a specific job."),
			cli.String("environment-id", "").Help("Filter to invocations executed in a specific environment."),
			cli.String("action-name", "").Help("Filter to invocations of a specific action."),
			cli.String("action-id", "").Help("Filter to an immutable project or organization Action ID."),
			cli.String("definition-scope", "").Help("Filter by the scope that owned the selected definition."),
			cli.Int("secret-version", "").Help("Filter to deliveries signed with a specific secret version."),
			cli.String("delivery-id", "").Help("Filter to a signed delivery identity."),
			cli.String("correlation-id", "").Help("Filter to the request or dispatch correlation identity."),
			cli.String("status", "").Help("Filter by terminal status (e.g. \"success\", \"failed\")."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListActionInvocationsParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			if ctx.IsSet("run-id") {
				v := ctx.String("run-id")
				params.RunId = &v
			}
			if ctx.IsSet("job-id") {
				v := ctx.String("job-id")
				params.JobId = &v
			}
			if ctx.IsSet("environment-id") {
				v := ctx.String("environment-id")
				params.EnvironmentId = &v
			}
			if ctx.IsSet("action-name") {
				v := ctx.String("action-name")
				params.ActionName = &v
			}
			if ctx.IsSet("action-id") {
				v := ctx.String("action-id")
				params.ActionId = &v
			}
			if ctx.IsSet("definition-scope") {
				v := api.ListActionInvocationsParamsDefinitionScope(ctx.String("definition-scope"))
				params.DefinitionScope = &v
			}
			if ctx.IsSet("secret-version") {
				v := int64(ctx.Int("secret-version"))
				params.SecretVersion = &v
			}
			if ctx.IsSet("delivery-id") {
				v := ctx.String("delivery-id")
				params.DeliveryId = &v
			}
			if ctx.IsSet("correlation-id") {
				v := ctx.String("correlation-id")
				params.CorrelationId = &v
			}
			if ctx.IsSet("status") {
				v := ctx.String("status")
				params.Status = &v
			}
			resp, err := client.ListActionInvocationsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listActionInvocations", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("revoke-action-secret-version").
		Description("Revoke an organization action secret version").
		Args("action-id", "secret-version").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			p1, err := parseInt64Arg(ctx.Arg(1), "secret-version")
			if err != nil {
				return err
			}
			resp, err := client.RevokeOrganizationActionSecretVersionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "revokeOrganizationActionSecretVersion", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("rotate-action-secret").
		Description("Rotate an organization action secret").
		Args("action-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.RotateOrganizationActionSecretWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "rotateOrganizationActionSecret", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("rotate-secret").
		Description("Rotate signing secret").
		AddArg(&cli.Arg{Name: "action-name", Description: "Action name used in loop step definitions.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.RotateActionSecretWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "rotateActionSecret", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("update").
		Description("Update action").
		AddArg(&cli.Arg{Name: "action-name", Description: "Action name used in loop step definitions.", Required: true}).
		Flags(
			cli.String("annotations", "").Help("Pass null to clear all annotation flags. Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Replacement Markdown description."),
			cli.String("endpoint-url", "").Help("Replacement endpoint URL. Valid for HTTP actions only."),
			cli.String("input-schema", "").Help("Replacement JSON Schema for inputs. Replaces the existing schema. Accepts JSON, @file, or @-."),
			cli.String("invocation-format", "").Help("Replacement HTTP request-body contract. `signed_context_v1` is valid only for HTTP-backed actions."),
			cli.String("output-schema", "").Help("Replacement JSON Schema for outputs. Replaces the existing schema. Accepts JSON, @file, or @-."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("title", "").Help("Replacement display title."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateActionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("annotations") {
				if err := decodeFlagJSON(ctx, "annotations", ctx.String("annotations"), &body.Annotations); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("endpoint-url") {
				v := ctx.String("endpoint-url")
				body.EndpointUrl = &v
			}
			if ctx.IsSet("input-schema") {
				if err := decodeFlagJSON(ctx, "input-schema", ctx.String("input-schema"), &body.InputSchema); err != nil {
					return err
				}
			}
			if ctx.IsSet("invocation-format") {
				v := api.ActionInvocationFormat(ctx.String("invocation-format"))
				body.InvocationFormat = &v
			}
			if ctx.IsSet("output-schema") {
				if err := decodeFlagJSON(ctx, "output-schema", ctx.String("output-schema"), &body.OutputSchema); err != nil {
					return err
				}
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("title") {
				v := ctx.String("title")
				body.Title = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("annotations") && !ctx.IsSet("description") && !ctx.IsSet("endpoint-url") && !ctx.IsSet("input-schema") && !ctx.IsSet("invocation-format") && !ctx.IsSet("output-schema") && !ctx.IsSet("tag") && !ctx.IsSet("title") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateActionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateAction", resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("update-action").
		Description("Update organization action").
		AddArg(&cli.Arg{Name: "action-id", Description: "Organization action ID.", Required: true}).
		Flags(
			cli.String("annotations", "").Help("annotations Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("description"),
			cli.Bool("enabled", "").Help("enabled"),
			cli.String("endpoint-url", "").Help("endpoint-url"),
			cli.String("input-schema", "").Help("input-schema Accepts JSON, @file, or @-."),
			cli.String("name", "").Help("name"),
			cli.String("output-schema", "").Help("output-schema Accepts JSON, @file, or @-."),
			cli.String("title", "").Help("title"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			var body api.UpdateOrganizationActionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("annotations") {
				if err := decodeFlagJSON(ctx, "annotations", ctx.String("annotations"), &body.Annotations); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("enabled") {
				v := ctx.Bool("enabled")
				body.Enabled = &v
			}
			if ctx.IsSet("endpoint-url") {
				v := ctx.String("endpoint-url")
				body.EndpointUrl = &v
			}
			if ctx.IsSet("input-schema") {
				if err := decodeFlagJSON(ctx, "input-schema", ctx.String("input-schema"), &body.InputSchema); err != nil {
					return err
				}
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("output-schema") {
				if err := decodeFlagJSON(ctx, "output-schema", ctx.String("output-schema"), &body.OutputSchema); err != nil {
					return err
				}
			}
			if ctx.IsSet("title") {
				v := ctx.String("title")
				body.Title = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("annotations") && !ctx.IsSet("description") && !ctx.IsSet("enabled") && !ctx.IsSet("endpoint-url") && !ctx.IsSet("input-schema") && !ctx.IsSet("name") && !ctx.IsSet("output-schema") && !ctx.IsSet("title") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateOrganizationActionWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateOrganizationAction", resp.StatusCode(), resp.Body)
		})

}
