// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerInteractionsCommands registers every generated subcommand in the "interactions" group.
func registerInteractionsCommands(app *cli.App) {
	interactionsGrp := app.Group("interactions").Description("Approval, review, and input prompts")
	interactionsGrp.Alias("interaction")
	interactionsGrp.Command("claim").
		Description("Claim a pending first-responder group interaction").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ClaimInteractionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "claimInteraction", resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("create").
		Description("Create an interaction").
		Flags(
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateInteractionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.String("file") == "" {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateInteractionWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createInteraction", resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("get").
		Description("Get an interaction").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetInteractionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getInteraction", resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("list").
		Description("List interactions").
		Flags(
			cli.String("status", "").Help("Filter by status"),
			cli.String("run-id", "").Help("Filter by originating run ID"),
			cli.String("target-type", "").Help("Filter by target type"),
			cli.String("target-id", "").Help("Filter by target ID"),
			cli.Bool("inbox", "").Help("When true, returns only interactions visible to the authenticated user (direct + group membership)"),
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListInteractionsParams{}
			if ctx.IsSet("status") {
				v := api.ListInteractionsParamsStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("run-id") {
				v := ctx.String("run-id")
				params.RunId = &v
			}
			if ctx.IsSet("target-type") {
				v := api.ListInteractionsParamsTargetType(ctx.String("target-type"))
				params.TargetType = &v
			}
			if ctx.IsSet("target-id") {
				v := ctx.String("target-id")
				params.TargetId = &v
			}
			if ctx.IsSet("inbox") {
				v := ctx.Bool("inbox")
				params.Inbox = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListInteractionsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listInteractions", resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("release-interaction").
		Description("Release a claimed first-responder group interaction").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ReleaseInteractionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "releaseInteraction", resp.StatusCode(), resp.Body)
		})

	interactionsGrp.Command("respond-to-interaction").
		Description("Submit a response to an interaction").
		Args("id").
		Flags(
			cli.String("comment", "").Help("Optional free-text comment accompanying the response."),
			cli.String("value", "").Help("Free-form JSON payload supplied by the responder. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.RespondToInteractionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("comment") {
				v := ctx.String("comment")
				body.Comment = &v
			}
			if ctx.IsSet("value") {
				if err := decodeFlagJSON(ctx, "value", ctx.String("value"), &body.Value); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("comment") && !ctx.IsSet("value") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.RespondToInteractionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "respondToInteraction", resp.StatusCode(), resp.Body)
		})

}
