// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerChannelsCommands registers every generated subcommand in the "channels" group.
func registerChannelsCommands(app *cli.App) {
	channelsGrp := app.Group("channels").Description("Chat channels, members, and messages")
	channelsGrp.Alias("channel")
	channelsGrp.Command("add-member").
		Description("Add a member to a channel").
		Args("id").
		Flags(
			cli.String("role", "").Help("Role to assign the new member, either `member` or `admin`."),
			cli.String("user-id", "").Help("[required] User or agent ID to add to the channel."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.AddChannelMemberJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("role") {
				v := api.AddChannelMemberRequestRole(ctx.String("role"))
				body.Role = &v
			}
			if ctx.IsSet("user-id") {
				body.UserId = ctx.String("user-id")
			}
			if body.UserId == "" {
				return fmt.Errorf("--user-id is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.AddChannelMemberWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "addChannelMember", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("create").
		Description("Create a channel").
		Flags(
			cli.String("display-name", "").Help("[required] Human-facing display name shown in the UI."),
			cli.String("kind", "").Help("[required] Channel kind, either `dm` or `channel`. Cannot be changed after creation."),
			cli.Strings("member-ids", "").Help("Optional list of user or agent IDs to add as members at creation time. All receive the `member` rol…"),
			cli.String("name", "").Help("[required] URL-safe handle, unique within the project. Immutable after creation — choose carefully."),
			cli.Bool("private", "").Help("When true, the channel is invite-only."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("topic", "").Help("Optional channel topic or description."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateChannelJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("display-name") {
				body.DisplayName = ctx.String("display-name")
			}
			if ctx.IsSet("kind") {
				body.Kind = api.CreateChannelRequestKind(ctx.String("kind"))
			}
			if ctx.IsSet("member-ids") {
				v := ctx.Strings("member-ids")
				body.MemberIds = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("private") {
				v := ctx.Bool("private")
				body.Private = &v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("topic") {
				v := ctx.String("topic")
				body.Topic = &v
			}
			if body.DisplayName == "" {
				return fmt.Errorf("--display-name is required (or supply it via --file)")
			}
			if body.Kind == "" {
				return fmt.Errorf("--kind is required (or supply it via --file)")
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateChannelWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createChannel", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("delete").
		Description("Delete a channel").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteChannelWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteChannel", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("get").
		Description("Get a channel").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetChannelWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getChannel", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("get-message").
		Description("Get a channel message").
		Args("id", "message-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.GetChannelMessageWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getChannelMessage", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("list").
		Description("List channels").
		Flags(
			cli.String("kind", "").Help("Filter by channel kind."),
			cli.Bool("private", "").Help("Filter by private flag."),
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListChannelsParams{}
			if ctx.IsSet("kind") {
				v := api.ListChannelsParamsKind(ctx.String("kind"))
				params.Kind = &v
			}
			if ctx.IsSet("private") {
				v := ctx.Bool("private")
				params.Private = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListChannelsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listChannels", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("list-members").
		Description("List channel members").
		Args("id").
		Flags(
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListChannelMembersParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListChannelMembersWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listChannelMembers", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("list-messages").
		Description("List messages in a channel").
		Args("id").
		Flags(
			cli.String("sender-id", "").Help("Filter by sender user or agent ID."),
			cli.String("reply-to", "").Help("Return only replies to this message ID (thread view)."),
			cli.Bool("pinned", "").Help("Filter by pinned status."),
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListChannelMessagesParams{}
			if ctx.IsSet("sender-id") {
				v := ctx.String("sender-id")
				params.SenderId = &v
			}
			if ctx.IsSet("reply-to") {
				v := ctx.String("reply-to")
				params.ReplyTo = &v
			}
			if ctx.IsSet("pinned") {
				v := ctx.Bool("pinned")
				params.Pinned = &v
			}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListChannelMessagesWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listChannelMessages", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("remove-member").
		Description("Remove a member from a channel").
		Args("id", "member-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			resp, err := client.RemoveChannelMemberWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "removeChannelMember", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("send-message").
		Description("Send a message to a channel").
		Args("id").
		Flags(
			cli.String("content", "").Help("[required] Message body in Markdown."),
			cli.String("display", "").Help("Rendering hint for the UI: `message`, `notice`, or `card`."),
			cli.String("metadata", "").Help("Free-form JSON object for caller-defined metadata. Accepts JSON, @file, or @-."),
			cli.String("reply-to", "").Help("Parent message ID for threading (creates a reply)."),
			cli.String("sender-agent-id", "").Help("Durable agent identity to attribute the message to. When set, `sender_type` on the resulting messag…"),
			cli.String("sender-session-id", "").Help("Live agent session to associate with the message."),
			cli.String("type", "").Help("Dot-namespaced message type identifier."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.SendChannelMessageJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("content") {
				body.Content = ctx.String("content")
			}
			if ctx.IsSet("display") {
				v := api.SendChannelMessageRequestDisplay(ctx.String("display"))
				body.Display = &v
			}
			if ctx.IsSet("metadata") {
				if err := decodeFlagJSON(ctx, "metadata", ctx.String("metadata"), &body.Metadata); err != nil {
					return err
				}
			}
			if ctx.IsSet("reply-to") {
				v := ctx.String("reply-to")
				body.ReplyTo = &v
			}
			if ctx.IsSet("sender-agent-id") {
				v := ctx.String("sender-agent-id")
				body.SenderAgentId = &v
			}
			if ctx.IsSet("sender-session-id") {
				v := ctx.String("sender-session-id")
				body.SenderSessionId = &v
			}
			if ctx.IsSet("type") {
				v := ctx.String("type")
				body.Type = &v
			}
			if body.Content == "" {
				return fmt.Errorf("--content is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.SendChannelMessageWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "sendChannelMessage", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("update").
		Description("Update a channel").
		Args("id").
		Flags(
			cli.String("display-name", "").Help("Updated display name."),
			cli.Bool("private", "").Help("Toggle invite-only visibility."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("topic", "").Help("Updated topic or description."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateChannelJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("display-name") {
				v := ctx.String("display-name")
				body.DisplayName = &v
			}
			if ctx.IsSet("private") {
				v := ctx.Bool("private")
				body.Private = &v
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("topic") {
				v := ctx.String("topic")
				body.Topic = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("display-name") && !ctx.IsSet("private") && !ctx.IsSet("tag") && !ctx.IsSet("topic") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateChannelWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateChannel", resp.StatusCode(), resp.Body)
		})

	channelsGrp.Command("update-message").
		Description("Update a channel message").
		Args("id", "message-id").
		Flags(
			cli.String("content", "").Help("Updated Markdown content. Sets `edited_at` on the message."),
			cli.String("metadata", "").Help("Free-form JSON object for caller-defined metadata. Accepts JSON, @file, or @-."),
			cli.Bool("pinned", "").Help("Pin or unpin the message. Sets/clears `pinned_by`."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2 := ctx.Arg(1)
			var body api.UpdateChannelMessageJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("content") {
				v := ctx.String("content")
				body.Content = &v
			}
			if ctx.IsSet("metadata") {
				if err := decodeFlagJSON(ctx, "metadata", ctx.String("metadata"), &body.Metadata); err != nil {
					return err
				}
			}
			if ctx.IsSet("pinned") {
				v := ctx.Bool("pinned")
				body.Pinned = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("content") && !ctx.IsSet("metadata") && !ctx.IsSet("pinned") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateChannelMessageWithResponse(ctx.Context(), p0, p1, p2, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateChannelMessage", resp.StatusCode(), resp.Body)
		})

}
