// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerGenerateCommands registers every generated subcommand in the "generate" group.
func registerGenerateCommands(app *cli.App) {
	generateGrp := app.Group("generate")
	generateGrp.Command("create").
		Description("Create an Anthropic-compatible message").
		Flags(
			cli.Int("max-tokens", "").Help("max-tokens"),
			cli.String("messages", "").Help("[required] Conversation history in Anthropic Messages format. `content` may be a string or content-block array. Accepts JSON, @file, or @-."),
			cli.String("metadata", "").Help("Optional Anthropic metadata such as `user_id`. Accepts JSON, @file, or @-."),
			cli.String("model", "").Help("[required] Model identifier, for example `claude-sonnet-4-20250514`."),
			cli.String("provider", "").Help("Provider used to resolve project integration credentials. Omit for Anthropic. `xai` is accepted as …"),
			cli.Strings("stop-sequences", "").Help("stop-sequences"),
			cli.Bool("stream", "").Help("stream"),
			cli.String("system", "").Help("System prompt, either a string or Anthropic text blocks. Accepts JSON, @file, or @-."),
			cli.String("temperature", "").Help("temperature Accepts JSON, @file, or @-."),
			cli.String("tool-choice", "").Help("tool-choice Accepts JSON, @file, or @-."),
			cli.String("tools", "").Help("Anthropic tool definitions. Accepts JSON, @file, or @-."),
			cli.String("-", "").Help("[required] - Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			var body api.CreateMessageJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("max-tokens") {
				v := ctx.Int("max-tokens")
				body.MaxTokens = &v
			}
			if ctx.IsSet("messages") {
				if err := decodeFlagJSON(ctx, "messages", ctx.String("messages"), &body.Messages); err != nil {
					return err
				}
			}
			if ctx.IsSet("metadata") {
				if err := decodeFlagJSON(ctx, "metadata", ctx.String("metadata"), &body.Metadata); err != nil {
					return err
				}
			}
			if ctx.IsSet("model") {
				body.Model = ctx.String("model")
			}
			if ctx.IsSet("provider") {
				v := api.GenerateRequestProvider(ctx.String("provider"))
				body.Provider = &v
			}
			if ctx.IsSet("stop-sequences") {
				v := ctx.Strings("stop-sequences")
				body.StopSequences = &v
			}
			if ctx.IsSet("stream") {
				v := ctx.Bool("stream")
				body.Stream = &v
			}
			if ctx.IsSet("system") {
				if err := decodeFlagJSON(ctx, "system", ctx.String("system"), &body.System); err != nil {
					return err
				}
			}
			if ctx.IsSet("temperature") {
				if err := decodeFlagJSON(ctx, "temperature", ctx.String("temperature"), &body.Temperature); err != nil {
					return err
				}
			}
			if ctx.IsSet("tool-choice") {
				if err := decodeFlagJSON(ctx, "tool-choice", ctx.String("tool-choice"), &body.ToolChoice); err != nil {
					return err
				}
			}
			if ctx.IsSet("tools") {
				if err := decodeFlagJSON(ctx, "tools", ctx.String("tools"), &body.Tools); err != nil {
					return err
				}
			}
			if ctx.IsSet("-") {
				if err := decodeFlagJSON(ctx, "-", ctx.String("-"), &body.AdditionalProperties); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("messages") {
				return fmt.Errorf("--messages is required (or supply it via --file)")
			}
			if body.Model == "" {
				return fmt.Errorf("--model is required (or supply it via --file)")
			}
			if ctx.String("file") == "" && !ctx.IsSet("-") {
				return fmt.Errorf("--- is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateMessageWithResponse(ctx.Context(), body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createMessage", resp.StatusCode(), resp.Body)
		})

}
