// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerAutomationsCommands registers every generated subcommand in the "automations" group.
func registerAutomationsCommands(app *cli.App) {
	automationsGrp := app.Group("automations")
	automationsGrp.Alias("automation")
	automationsGrp.Command("cancel-run").
		Description("Cancel an in-flight run").
		Args("id").
		Flags(
			cli.String("reason", "").Help("Human-readable cancellation reason recorded on the run."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.CancelAutomationRunJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("reason") {
				v := ctx.String("reason")
				body.Reason = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("reason") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CancelAutomationRunWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "cancelAutomationRun", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("create").
		Description("Create an automation").
		Flags(
			cli.String("default-agent-id", "").Help("Agent used by `agent` steps that do not pin an agent explicitly."),
			cli.String("default-inputs", "").Help("Default values merged into `inputs` when a run is started without overrides. Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Markdown description of the automation's purpose."),
			cli.String("handle", "").Help("[required] Stable per-project automation handle. Immutable after creation."),
			cli.String("name", "").Help("[required] Human-readable display name."),
			cli.String("settings", "").Help("Free-form automation-level settings consumed by the engine. Accepts JSON, @file, or @-."),
			cli.String("tags", "").Help("Free-form label map used to organise automations in listings and search. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateAutomationJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("default-agent-id") {
				v := ctx.String("default-agent-id")
				body.DefaultAgentId = &v
			}
			if ctx.IsSet("default-inputs") {
				if err := decodeFlagJSON(ctx, "default-inputs", ctx.String("default-inputs"), &body.DefaultInputs); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("handle") {
				body.Handle = ctx.String("handle")
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("settings") {
				if err := decodeFlagJSON(ctx, "settings", ctx.String("settings"), &body.Settings); err != nil {
					return err
				}
			}
			if ctx.IsSet("tags") {
				if err := decodeFlagJSON(ctx, "tags", ctx.String("tags"), &body.Tags); err != nil {
					return err
				}
			}
			if body.Handle == "" {
				return fmt.Errorf("--handle is required (or supply it via --file)")
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateAutomationWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createAutomation", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("create-version").
		Description("Create a new draft version").
		Args("handle").
		Flags(
			cli.String("compiled-plan", "").Help("Optional precompiled execution plan. The engine will recompile from `spec` if omitted. Accepts JSON, @file, or @-."),
			cli.String("spec", "").Help("[required] Authoring representation of an automation. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.CreateAutomationVersionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("compiled-plan") {
				if err := decodeFlagJSON(ctx, "compiled-plan", ctx.String("compiled-plan"), &body.CompiledPlan); err != nil {
					return err
				}
			}
			if ctx.IsSet("spec") {
				if err := decodeFlagJSON(ctx, "spec", ctx.String("spec"), &body.Spec); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("spec") {
				return fmt.Errorf("--spec is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateAutomationVersionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createAutomationVersion", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("delete").
		Description("Archive an automation").
		Args("handle").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteAutomationWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteAutomation", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("deliver-webhook-trigger").
		Description("Deliver a webhook payload to a trigger").
		Args("webhook-handle").
		Flags(
			cli.String("idempotency-key", "").Help("Optional idempotency key (also accepted via X-Idempotency-Key header)."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			params := &api.DeliverWebhookTriggerParams{}
			if ctx.IsSet("idempotency-key") {
				v := ctx.String("idempotency-key")
				params.IdempotencyKey = &v
			}
			var body api.DeliverWebhookTriggerJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.String("file") == "" {
				return fmt.Errorf("--file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.DeliverWebhookTriggerWithResponse(ctx.Context(), p0, params, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deliverWebhookTrigger", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("get").
		Description("Get an automation").
		Args("handle").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetAutomationWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getAutomation", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("get-run").
		Description("Get an automation run").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetAutomationRunWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getAutomationRun", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("list").
		Description("List automations in a project").
		Flags(
			cli.String("status", "").Help("Filter by lifecycle status."),
			cli.String("cursor", "").Help("Opaque pagination cursor from a prior response."),
			cli.Int("limit", "").Help("Maximum number of items to return."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListAutomationsParams{}
			if ctx.IsSet("status") {
				v := api.AutomationStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			resp, err := client.ListAutomationsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAutomations", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("list-run-events").
		Description("List run events").
		Args("id").
		Flags(
			cli.Int("since-sequence", "").Help("Return events with sequence > since_sequence."),
			cli.Int("limit", "").Help("limit"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.ListAutomationRunEventsParams{}
			if ctx.IsSet("since-sequence") {
				v := int64(ctx.Int("since-sequence"))
				params.SinceSequence = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListAutomationRunEventsWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAutomationRunEvents", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("list-run-steps").
		Description("List the steps of an automation run").
		Args("id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ListAutomationRunStepsWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAutomationRunSteps", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("list-runs").
		Description("List automation runs").
		Flags(
			cli.String("status", "").Help("Filter to one status."),
			cli.String("automation-id", "").Help("Filter to one automation's runs."),
			cli.String("cursor", "").Help("Opaque pagination cursor from a prior response."),
			cli.Int("limit", "").Help("Maximum number of items to return."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListAutomationRunsParams{}
			if ctx.IsSet("status") {
				v := api.AutomationRunStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("automation-id") {
				v := ctx.String("automation-id")
				params.AutomationId = &v
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			resp, err := client.ListAutomationRunsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAutomationRuns", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("list-versions").
		Description("List versions for an automation").
		Args("handle").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.ListAutomationVersionsWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listAutomationVersions", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("publish-automation-version").
		Description("Publish a version").
		Args("handle", "version").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			p2, err := parseIntArg(ctx.Arg(1), "version")
			if err != nil {
				return err
			}
			resp, err := client.PublishAutomationVersionWithResponse(ctx.Context(), p0, p1, p2)
			if err != nil {
				return err
			}
			return printResponse(ctx, "publishAutomationVersion", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("signal-automation-run").
		Description("Deliver a signal to a suspended run").
		Args("id").
		Flags(
			cli.String("result", "").Help("Free-form payload saved as the resumed step's output. Accepts JSON, @file, or @-."),
			cli.String("step-key", "").Help("[required] Step key currently in `suspended` state that should resume. Must match a step declared in the run's…"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.SignalAutomationRunJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("result") {
				if err := decodeFlagJSON(ctx, "result", ctx.String("result"), &body.Result); err != nil {
					return err
				}
			}
			if ctx.IsSet("step-key") {
				body.StepKey = ctx.String("step-key")
			}
			if body.StepKey == "" {
				return fmt.Errorf("--step-key is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.SignalAutomationRunWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "signalAutomationRun", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("start-automation-run").
		Description("Start a new automation run").
		Args("handle").
		Flags(
			cli.String("external-id", "").Help("Caller-supplied idempotency key, scoped to (org, project). Repeat calls with the same `external_id`…"),
			cli.String("inputs", "").Help("Free-form input map passed to the run. Available to steps via `{{ inputs.<key> }}` templates. Accepts JSON, @file, or @-."),
			cli.String("source", "").Help("Optional attribution for the call that started this run. Triggers and webhooks populate `trigger_id… Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.StartAutomationRunJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("external-id") {
				v := ctx.String("external-id")
				body.ExternalId = &v
			}
			if ctx.IsSet("inputs") {
				if err := decodeFlagJSON(ctx, "inputs", ctx.String("inputs"), &body.Inputs); err != nil {
					return err
				}
			}
			if ctx.IsSet("source") {
				if err := decodeFlagJSON(ctx, "source", ctx.String("source"), &body.Source); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("external-id") && !ctx.IsSet("inputs") && !ctx.IsSet("source") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.StartAutomationRunWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "startAutomationRun", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("stream-automation-run-events").
		Description("Stream run events over Server-Sent Events").
		Args("id").
		Flags(
			cli.Int("since-sequence", "").Help("Stream events with sequence > since_sequence."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			params := &api.StreamAutomationRunEventsParams{}
			if ctx.IsSet("since-sequence") {
				v := int64(ctx.Int("since-sequence"))
				params.SinceSequence = &v
			}
			resp, err := client.StreamAutomationRunEventsWithResponse(ctx.Context(), p0, p1, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "streamAutomationRunEvents", resp.StatusCode(), resp.Body)
		})

	automationsGrp.Command("update").
		Description("Update an automation").
		Args("handle").
		Flags(
			cli.String("default-agent-id", "").Help("Agent used by `agent` steps that do not pin an agent explicitly."),
			cli.String("default-inputs", "").Help("Default values merged into `inputs` when a run is started without overrides. Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Markdown description of the automation's purpose."),
			cli.String("name", "").Help("Human-readable display name."),
			cli.String("settings", "").Help("Free-form automation-level settings consumed by the engine. Accepts JSON, @file, or @-."),
			cli.String("status", "").Help("Lifecycle status of an automation."),
			cli.String("tags", "").Help("Free-form label map used to organise automations in listings and search. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateAutomationJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("default-agent-id") {
				v := ctx.String("default-agent-id")
				body.DefaultAgentId = &v
			}
			if ctx.IsSet("default-inputs") {
				if err := decodeFlagJSON(ctx, "default-inputs", ctx.String("default-inputs"), &body.DefaultInputs); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("settings") {
				if err := decodeFlagJSON(ctx, "settings", ctx.String("settings"), &body.Settings); err != nil {
					return err
				}
			}
			if ctx.IsSet("status") {
				v := api.AutomationStatus(ctx.String("status"))
				body.Status = &v
			}
			if ctx.IsSet("tags") {
				if err := decodeFlagJSON(ctx, "tags", ctx.String("tags"), &body.Tags); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("default-agent-id") && !ctx.IsSet("default-inputs") && !ctx.IsSet("description") && !ctx.IsSet("name") && !ctx.IsSet("settings") && !ctx.IsSet("status") && !ctx.IsSet("tags") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateAutomationWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateAutomation", resp.StatusCode(), resp.Body)
		})

}
