// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"encoding/json"
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerProjectsCommands registers every generated subcommand in the "projects" group.
func registerProjectsCommands(app *cli.App) {
	projectsGrp := app.Group("projects").Description("Projects within the organization")
	projectsGrp.Alias("project")
	projectsGrp.Command("add-member").
		Description("Add a project member").
		Args("id").
		Flags(
			cli.String("user-id", "").Help("[required] User ID of the org member to add to this project."),
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			var body api.AddProjectMemberJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("user-id") {
				body.UserId = ctx.String("user-id")
			}
			if body.UserId == "" {
				return fmt.Errorf("--user-id is required (or supply it via --file)")
			}
			resp, err := client.AddProjectMemberWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("archive").
		Description("Archive a project").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.ArchiveProjectWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("create").
		Description("Create a project").
		Flags(
			cli.String("access-mode", "").Help("`org_open`: every org member can see and use the project, subject to role assignments. `restricted`: only listed project members (and org owners/admins) can see or use the project."),
			cli.String("description", "").Help("Optional human-readable description."),
			cli.String("handle", "").Help("URL-safe slug for API routes. Auto-derived from name if omitted. Must be unique within the org. Cannot be changed after creation."),
			cli.String("name", "").Help("[required] Human-readable project name."),
			cli.String("tags", "").Help("Key/value tag map. Keys 1–128 chars, values 0–256 chars. Keys with the `mobius:` prefix are system-managed and cannot be set by callers. Maximum 8 tags per resource. Use tags to organize resources by environment, team, cost-center, or any other dimension meaningful to your organization; tags can be filtered on most list endpoints. (JSON)"),
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			var body api.CreateProjectJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("access-mode") {
				v := api.ProjectAccessMode(ctx.String("access-mode"))
				body.AccessMode = &v
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("handle") {
				v := ctx.String("handle")
				body.Handle = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("tags") {
				if err := json.Unmarshal([]byte(ctx.String("tags")), &body.Tags); err != nil {
					return fmt.Errorf("--tags: invalid JSON: %w", err)
				}
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			resp, err := client.CreateProjectWithResponse(ctx.Context(), body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("delete").
		Description("Delete a project").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.DeleteProjectWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("delete-config").
		Description("Clear project config").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.DeleteProjectConfigWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("get").
		Description("Get a project").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.GetProjectWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("get-config").
		Description("Get project config").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.GetProjectConfigWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("list").
		Description("List projects").
		Flags(
			cli.String("search", "").Help("Prefix-match filter applied to project name and handle."),
			cli.String("status", "").Help("Lifecycle filter. `active` (default) returns non-archived projects; `archived` returns archived projects only; `all` returns both."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			params := &api.ListProjectsParams{}
			if ctx.IsSet("search") {
				v := ctx.String("search")
				params.Search = &v
			}
			if ctx.IsSet("status") {
				v := api.ListProjectsParamsStatus(ctx.String("status"))
				params.Status = &v
			}
			resp, err := client.ListProjectsWithResponse(ctx.Context(), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("list-members").
		Description("List project members").
		Args("id").
		Flags(
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			params := &api.ListProjectMembersParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListProjectMembersWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("remove-member").
		Description("Remove a project member").
		Args("id", "user-id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.RemoveProjectMemberWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("restore").
		Description("Restore an archived project").
		Args("id").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			resp, err := client.RestoreProjectWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("update").
		Description("Update a project").
		Args("id").
		Flags(
			cli.String("access-mode", "").Help("`org_open`: every org member can see and use the project, subject to role assignments. `restricted`: only listed project members (and org owners/admins) can see or use the project."),
			cli.String("description", "").Help("Replacement description."),
			cli.String("name", "").Help("Replacement human-readable name."),
			cli.Bool("seed-existing-members", "").Help("When transitioning from `org_open` to `restricted`, set true to insert all current org members as project members so nobody loses visibility on the flip. Ignored on other transitions."),
			cli.String("tags", "").Help("Key/value tag map. Keys 1–128 chars, values 0–256 chars. Keys with the `mobius:` prefix are system-managed and cannot be set by callers. Maximum 8 tags per resource. Use tags to organize resources by environment, team, cost-center, or any other dimension meaningful to your organization; tags can be filtered on most list endpoints. (JSON)"),
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			var body api.UpdateProjectJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("access-mode") {
				v := api.ProjectAccessMode(ctx.String("access-mode"))
				body.AccessMode = &v
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("seed-existing-members") {
				v := ctx.Bool("seed-existing-members")
				body.SeedExistingMembers = &v
			}
			if ctx.IsSet("tags") {
				if err := json.Unmarshal([]byte(ctx.String("tags")), &body.Tags); err != nil {
					return fmt.Errorf("--tags: invalid JSON: %w", err)
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("access-mode") && !ctx.IsSet("description") && !ctx.IsSet("name") && !ctx.IsSet("seed-existing-members") && !ctx.IsSet("tags") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			resp, err := client.UpdateProjectWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	projectsGrp.Command("update-config").
		Description("Replace project config").
		Args("id").
		Flags(
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			var body api.UpdateProjectConfigJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.String("file") == "" {
				return fmt.Errorf("at least one flag or --file is required")
			}
			resp, err := client.UpdateProjectConfigWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
