// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// internal/cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerTablesCommands registers every generated subcommand in the "tables" group.
func registerTablesCommands(app *cli.App) {
	tablesGrp := app.Group("tables").Description("Org-scoped tables and rows")
	tablesGrp.Alias("table")
	tablesGrp.Command("bulk-create-rows").
		Description("Bulk create rows").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Flags(
			cli.String("rows", "").Help("[required] Row data objects to validate and insert. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			var body api.BulkCreateTableRowsJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("rows") {
				if err := decodeFlagJSON(ctx, "rows", ctx.String("rows"), &body.Rows); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("rows") {
				return fmt.Errorf("--rows is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "rows")
			}
			resp, err := client.BulkCreateTableRowsWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "bulkCreateTableRows", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("create").
		Description("Create table").
		Flags(
			cli.String("description", "").Help("Optional human-readable description of the table."),
			cli.String("instructions", "").Help("Optional author guidance for how this table should be used (e.g. surfaced to agents). Accepts text, @file, or @-. Use @@ to escape a literal leading @."),
			cli.String("name", "").Help("[required] Table name (lowercase, snake_case); unique within the org."),
			cli.String("owner", "").Help("The human or team responsible for this resource. Accepts JSON, @file, or @-."),
			cli.String("schema", "").Help("[required] Column definition for a virtual table. Each table has exactly one required string identity column and may nominate one optional string… Accepts JSON, @file, or @-."),
			cli.String("visibility", "").Help("Who the custodian chose to share the resource with."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			var body api.CreateTableJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("instructions") {
				v, err := decodeFlagText(ctx, "instructions", ctx.String("instructions"))
				if err != nil {
					return err
				}
				body.Instructions = &v
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("owner") {
				if err := decodeFlagJSON(ctx, "owner", ctx.String("owner"), &body.Owner); err != nil {
					return err
				}
			}
			if ctx.IsSet("schema") {
				if err := decodeFlagJSON(ctx, "schema", ctx.String("schema"), &body.Schema); err != nil {
					return err
				}
			}
			if ctx.IsSet("visibility") {
				v := api.ResourceVisibility(ctx.String("visibility"))
				body.Visibility = &v
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.String("file") == "" && !ctx.IsSet("schema") {
				return fmt.Errorf("--schema is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "owner", "schema")
			}
			resp, err := client.CreateTableWithResponse(ctx.Context(), body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createTable", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("create-row").
		Description("Create row").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Flags(
			cli.String("data", "").Help("[required] JSON object keyed by table column name. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			var body api.CreateTableRowJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("data") {
				if err := decodeFlagJSON(ctx, "data", ctx.String("data"), &body.Data); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("data") {
				return fmt.Errorf("--data is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "data")
			}
			resp, err := client.CreateTableRowWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createTableRow", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("delete").
		Description("Delete table and all its rows").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			resp, err := client.DeleteTableWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteTable", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("delete-row").
		Description("Delete row").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		AddArg(&cli.Arg{Name: "row-id", Description: "Table row ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			p1 := ctx.Arg(1)
			resp, err := client.DeleteTableRowWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteTableRow", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("get").
		Description("Get table").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			resp, err := client.GetTableWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getTable", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("get-row").
		Description("Get row by ID").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		AddArg(&cli.Arg{Name: "row-id", Description: "Table row ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			p1 := ctx.Arg(1)
			resp, err := client.GetTableRowWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getTableRow", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("get-stats").
		Description("Get table storage stats").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			resp, err := client.GetTableStatsWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getTableStats", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("list").
		Description("List tables").
		Flags(
			cli.String("cursor", "").Help("Cursor for pagination (opaque string from previous response)"),
			cli.Int("limit", "").Help("Maximum number of items to return"),
			cli.String("name", "").Help("Filter tables by name. Table names are unique within an org; use this as a discovery filter and use the returned table `id` for follow-up…"),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			params := &api.ListTablesParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			if ctx.IsSet("name") {
				v := api.TableNameQueryParam(ctx.String("name"))
				params.Name = &v
			}
			resp, err := client.ListTablesWithResponse(ctx.Context(), params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listTables", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("query-rows").
		Description("Query rows").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Flags(
			cli.String("cursor", "").Help("Opaque cursor from a prior response."),
			cli.String("filter", "").Help("Column equality or operator filter Accepts JSON, @file, or @-."),
			cli.Int("limit", "").Help("Maximum number of rows to return (1–100, default 20)."),
			cli.String("sort", "").Help("Sort clauses applied after filtering. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			var body api.QueryTableRowsJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				body.Cursor = &v
			}
			if ctx.IsSet("filter") {
				if err := decodeFlagJSON(ctx, "filter", ctx.String("filter"), &body.Filter); err != nil {
					return err
				}
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				body.Limit = &v
			}
			if ctx.IsSet("sort") {
				if err := decodeFlagJSON(ctx, "sort", ctx.String("sort"), &body.Sort); err != nil {
					return err
				}
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "filter", "sort")
			}
			resp, err := client.QueryTableRowsWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "queryTableRows", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("search-rows").
		Description("Search rows").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Flags(
			cli.String("cursor", "").Help("Opaque cursor from a prior search response."),
			cli.String("filter", "").Help("Optional column equality or operator filter applied before search. Accepts JSON, @file, or @-."),
			cli.Int("limit", "").Help("Maximum number of rows to return (1–100, default 20)."),
			cli.String("mode", "").Help("Search mode. `keyword` uses token-prefix matching, `semantic` uses similarity over indexed row text, and `hybrid` combines both."),
			cli.String("query", "").Help("[required] Search query. Hyphens and other punctuation split terms for keyword matching."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			var body api.SearchTableRowsJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				body.Cursor = &v
			}
			if ctx.IsSet("filter") {
				if err := decodeFlagJSON(ctx, "filter", ctx.String("filter"), &body.Filter); err != nil {
					return err
				}
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				body.Limit = &v
			}
			if ctx.IsSet("mode") {
				v := api.SearchRowsRequestMode(ctx.String("mode"))
				body.Mode = &v
			}
			if ctx.IsSet("query") {
				body.Query = ctx.String("query")
			}
			if body.Query == "" {
				return fmt.Errorf("--query is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "filter")
			}
			resp, err := client.SearchTableRowsWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "searchTableRows", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("update").
		Description("Update table").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Flags(
			cli.String("description", "").Help("Optional human-readable description of the table."),
			cli.String("instructions", "").Help("Optional author guidance for how this table should be used (e.g. surfaced to agents). Accepts text, @file, or @-. Use @@ to escape a literal leading @."),
			cli.String("name", "").Help("Table name (lowercase, snake_case); unique within the org."),
			cli.String("schema", "").Help("Column definition for a virtual table. Each table has exactly one required string identity column and may nominate one optional string… Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			var body api.UpdateTableJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("instructions") {
				v, err := decodeFlagText(ctx, "instructions", ctx.String("instructions"))
				if err != nil {
					return err
				}
				body.Instructions = &v
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("schema") {
				if err := decodeFlagJSON(ctx, "schema", ctx.String("schema"), &body.Schema); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("description") && !ctx.IsSet("instructions") && !ctx.IsSet("name") && !ctx.IsSet("schema") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "schema")
			}
			resp, err := client.UpdateTableWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateTable", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("update-row").
		Description("Update row").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		AddArg(&cli.Arg{Name: "row-id", Description: "Table row ID.", Required: true}).
		Flags(
			cli.String("data", "").Help("[required] Fields to merge into the existing row, keyed by table column name. Accepts JSON, @file, or @-."),
			cli.Int("version", "").Help("Expected version for optimistic locking. Omit or 0 to skip the check."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			p1 := ctx.Arg(1)
			var body api.UpdateTableRowJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("data") {
				if err := decodeFlagJSON(ctx, "data", ctx.String("data"), &body.Data); err != nil {
					return err
				}
			}
			if ctx.IsSet("version") {
				v := ctx.Int("version")
				body.Version = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("data") {
				return fmt.Errorf("--data is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "data")
			}
			resp, err := client.UpdateTableRowWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateTableRow", resp.StatusCode(), resp.Body)
		})

	tablesGrp.Command("upsert-row").
		Description("Upsert row").
		AddArg(&cli.Arg{Name: "table-id", Description: "Table ID.", Required: true}).
		Flags(
			cli.String("data", "").Help("[required] Fields to create or merge into the row. Must include the table's identity column. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := api.TableIDParam(ctx.Arg(0))
			var body api.UpsertTableRowJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("data") {
				if err := decodeFlagJSON(ctx, "data", ctx.String("data"), &body.Data); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("data") {
				return fmt.Errorf("--data is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body, "data")
			}
			resp, err := client.UpsertTableRowWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "upsertTableRow", resp.StatusCode(), resp.Body)
		})

}
