// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerLoopsCommands registers every generated subcommand in the "loops" group.
func registerLoopsCommands(app *cli.App) {
	loopsGrp := app.Group("loops").Description("Loop definitions, versions, and runs")
	loopsGrp.Alias("loop")
	loopsGrp.Command("create").
		Description("Create loop").
		Flags(
			cli.String("agent-id", "").Help("Agent associated with this loop. Agent steps use it when they do not pin `config.agent_id`."),
			cli.String("cleanup", "").Help("Cleanup steps or policies evaluated after normal step execution. Accepts JSON, @file, or @-."),
			cli.String("concurrency", "").Help("Concurrency behavior: `allow`, `queue`, `skip`, or `replace`."),
			cli.String("config", "").Help("Declared run config fields for this loop. Accepts JSON, @file, or @-."),
			cli.String("default-config", "").Help("Default config values used when a run is started without overrides. Accepts JSON, @file, or @-."),
			cli.String("defaults", "").Help("Run-level defaults inside the loop spec. Lives at `spec.defaults` in the JSON the engine compiles. The run wall-clock limit moved to… Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Markdown description of the loop's purpose."),
			cli.String("event", "").Help("Declared event fields for this loop. Accepts JSON, @file, or @-."),
			cli.String("limits", "").Help("Run guardrails. Lives at `spec.limits` in the JSON the engine compiles. Every limit is optional; absent or zero means unbounded (plan-level… Accepts JSON, @file, or @-."),
			cli.String("name", "").Help("[required] Human-readable display name."),
			cli.String("repositories", "").Help("Source repositories the loop targets. Accepts JSON, @file, or @-."),
			cli.String("run-name", "").Help("Templates for assigning an operator-facing title and optional description to each run. The object form leaves room for additional naming… Accepts JSON, @file, or @-."),
			cli.String("schema-version", "").Help("Loop authoring schema version. Only schema version 1 is accepted."),
			cli.String("settings", "").Help("Free-form loop-level settings consumed by the engine. Accepts JSON, @file, or @-."),
			cli.String("steps", "").Help("Steps use kind agent, action, sleep, wait_for_event, interaction, loop, or check; action inputs use config.parameters; if is a predicate. Accepts JSON, @file, or @-."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("triggers", "").Help("Authored trigger declarations for this loop. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			var body api.CreateLoopJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("agent-id") {
				v := ctx.String("agent-id")
				body.AgentId = &v
			}
			if ctx.IsSet("cleanup") {
				if err := decodeFlagJSON(ctx, "cleanup", ctx.String("cleanup"), &body.Cleanup); err != nil {
					return err
				}
			}
			if ctx.IsSet("concurrency") {
				v := api.CreateLoopRequestConcurrency(ctx.String("concurrency"))
				body.Concurrency = &v
			}
			if ctx.IsSet("config") {
				if err := decodeFlagJSON(ctx, "config", ctx.String("config"), &body.Config); err != nil {
					return err
				}
			}
			if ctx.IsSet("default-config") {
				if err := decodeFlagJSON(ctx, "default-config", ctx.String("default-config"), &body.DefaultConfig); err != nil {
					return err
				}
			}
			if ctx.IsSet("defaults") {
				if err := decodeFlagJSON(ctx, "defaults", ctx.String("defaults"), &body.Defaults); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("event") {
				if err := decodeFlagJSON(ctx, "event", ctx.String("event"), &body.Event); err != nil {
					return err
				}
			}
			if ctx.IsSet("limits") {
				if err := decodeFlagJSON(ctx, "limits", ctx.String("limits"), &body.Limits); err != nil {
					return err
				}
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("repositories") {
				if err := decodeFlagJSON(ctx, "repositories", ctx.String("repositories"), &body.Repositories); err != nil {
					return err
				}
			}
			if ctx.IsSet("run-name") {
				if err := decodeFlagJSON(ctx, "run-name", ctx.String("run-name"), &body.RunName); err != nil {
					return err
				}
			}
			if ctx.IsSet("schema-version") {
				v := api.CreateLoopRequestSchemaVersion(ctx.String("schema-version"))
				body.SchemaVersion = &v
			}
			if ctx.IsSet("settings") {
				if err := decodeFlagJSON(ctx, "settings", ctx.String("settings"), &body.Settings); err != nil {
					return err
				}
			}
			if ctx.IsSet("steps") {
				if err := decodeFlagJSON(ctx, "steps", ctx.String("steps"), &body.Steps); err != nil {
					return err
				}
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("triggers") {
				if err := decodeFlagJSON(ctx, "triggers", ctx.String("triggers"), &body.Triggers); err != nil {
					return err
				}
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.CreateLoopWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "createLoop", resp.StatusCode(), resp.Body)
		})

	loopsGrp.Command("delete").
		Description("Delete loop").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.DeleteLoopWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deleteLoop", resp.StatusCode(), resp.Body)
		})

	loopsGrp.Command("deliver-http-trigger").
		Description("Deliver trigger").
		AddArg(&cli.Arg{Name: "http-handle", Description: "Globally unique identifier for the trigger. The endpoint carries no project context, so the handle is resolved on its own; it defaults to…", Required: true}).
		Flags(
			cli.String("idempotency-key", "").Help("Optional idempotency key (also accepted via the X-Idempotency-Key header)."),
			cli.String("x-idempotency-key", "").Help("Alternative to the `idempotency_key` query parameter. When both are present the query parameter wins. Repeats with the same key return the…"),
			cli.String("x-mobius-signature", "").Help("HMAC-SHA256 signature of the raw request body under the trigger's signing secret, formatted as `sha256=<hex>`. Required only when the HTTP…"),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			params := &api.DeliverHTTPTriggerParams{}
			if ctx.IsSet("idempotency-key") {
				v := ctx.String("idempotency-key")
				params.IdempotencyKey = &v
			}
			if ctx.IsSet("x-idempotency-key") {
				v := ctx.String("x-idempotency-key")
				params.XIdempotencyKey = &v
			}
			if ctx.IsSet("x-mobius-signature") {
				v := ctx.String("x-mobius-signature")
				params.XMobiusSignature = &v
			}
			var body api.DeliverHTTPTriggerJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.DeliverHTTPTriggerWithResponse(ctx.Context(), p0, params, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "deliverHTTPTrigger", resp.StatusCode(), resp.Body)
		})

	loopsGrp.Command("get").
		Description("Get loop").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			resp, err := client.GetLoopWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getLoop", resp.StatusCode(), resp.Body)
		})

	loopsGrp.Command("list").
		Description("List loops").
		Flags(
			cli.String("status", "").Help("Filter by lifecycle status. Omit to return the normal loop list, or pass a visible status to filter to it exactly."),
			cli.String("agent-id", "").Help("Return only loops associated with this agent."),
			cli.String("cursor", "").Help("Opaque pagination cursor from a prior response."),
			cli.Int("limit", "").Help("Maximum number of items to return."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			params := &api.ListLoopsParams{}
			if ctx.IsSet("status") {
				v := api.ListLoopsParamsStatus(ctx.String("status"))
				params.Status = &v
			}
			if ctx.IsSet("agent-id") {
				v := ctx.String("agent-id")
				params.AgentId = &v
			}
			if ctx.IsSet("cursor") {
				v := ctx.String("cursor")
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := ctx.Int("limit")
				params.Limit = &v
			}
			resp, err := client.ListLoopsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, "listLoops", resp.StatusCode(), resp.Body)
		})

	loopsGrp.Command("update").
		Description("Update loop").
		AddArg(&cli.Arg{Name: "resource-id", Description: "Resource ID.", Required: true}).
		Flags(
			cli.String("agent-id", "").Help("Agent associated with this loop. Agent steps use it when they do not pin `config.agent_id`."),
			cli.String("cleanup", "").Help("Replacement cleanup steps or policies. Accepts JSON, @file, or @-."),
			cli.String("concurrency", "").Help("Concurrency behavior: `allow`, `queue`, `skip`, or `replace`."),
			cli.String("config", "").Help("Declared run config fields for this loop. Accepts JSON, @file, or @-."),
			cli.String("default-config", "").Help("Default config values used when a run is started without overrides. Accepts JSON, @file, or @-."),
			cli.String("defaults", "").Help("Run-level defaults inside the loop spec. Lives at `spec.defaults` in the JSON the engine compiles. The run wall-clock limit moved to… Accepts JSON, @file, or @-."),
			cli.String("description", "").Help("Markdown description of the loop's purpose."),
			cli.String("event", "").Help("Declared event fields for this loop. Accepts JSON, @file, or @-."),
			cli.String("limits", "").Help("Run guardrails. Lives at `spec.limits` in the JSON the engine compiles. Every limit is optional; absent or zero means unbounded (plan-level… Accepts JSON, @file, or @-."),
			cli.String("name", "").Help("Human-readable display name."),
			cli.String("repositories", "").Help("Replacement source repositories the loop targets. Accepts JSON, @file, or @-."),
			cli.String("run-name", "").Help("Templates for assigning an operator-facing title and optional description to each run. The object form leaves room for additional naming… Accepts JSON, @file, or @-."),
			cli.String("schema-version", "").Help("Loop authoring schema version. Only schema version 1 is accepted."),
			cli.String("settings", "").Help("Free-form loop-level settings consumed by the engine. Accepts JSON, @file, or @-."),
			cli.String("status", "").Help("Loop lifecycle status: `draft`, `active`, `paused`, or `deleted`."),
			cli.String("steps", "").Help("Steps use kind agent, action, sleep, wait_for_event, interaction, loop, or check; action inputs use config.parameters; if is a predicate. Accepts JSON, @file, or @-."),
			cli.Strings("tag", "").Help("Tag in KEY=VALUE form. Repeatable."),
			cli.String("triggers", "").Help("Replacement authored trigger declarations. Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := authFor(ctx).Project
			p1 := ctx.Arg(0)
			var body api.UpdateLoopJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("agent-id") {
				v := ctx.String("agent-id")
				body.AgentId = &v
			}
			if ctx.IsSet("cleanup") {
				if err := decodeFlagJSON(ctx, "cleanup", ctx.String("cleanup"), &body.Cleanup); err != nil {
					return err
				}
			}
			if ctx.IsSet("concurrency") {
				v := api.UpdateLoopRequestConcurrency(ctx.String("concurrency"))
				body.Concurrency = &v
			}
			if ctx.IsSet("config") {
				if err := decodeFlagJSON(ctx, "config", ctx.String("config"), &body.Config); err != nil {
					return err
				}
			}
			if ctx.IsSet("default-config") {
				if err := decodeFlagJSON(ctx, "default-config", ctx.String("default-config"), &body.DefaultConfig); err != nil {
					return err
				}
			}
			if ctx.IsSet("defaults") {
				if err := decodeFlagJSON(ctx, "defaults", ctx.String("defaults"), &body.Defaults); err != nil {
					return err
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("event") {
				if err := decodeFlagJSON(ctx, "event", ctx.String("event"), &body.Event); err != nil {
					return err
				}
			}
			if ctx.IsSet("limits") {
				if err := decodeFlagJSON(ctx, "limits", ctx.String("limits"), &body.Limits); err != nil {
					return err
				}
			}
			if ctx.IsSet("name") {
				v := ctx.String("name")
				body.Name = &v
			}
			if ctx.IsSet("repositories") {
				if err := decodeFlagJSON(ctx, "repositories", ctx.String("repositories"), &body.Repositories); err != nil {
					return err
				}
			}
			if ctx.IsSet("run-name") {
				if err := decodeFlagJSON(ctx, "run-name", ctx.String("run-name"), &body.RunName); err != nil {
					return err
				}
			}
			if ctx.IsSet("schema-version") {
				v := api.UpdateLoopRequestSchemaVersion(ctx.String("schema-version"))
				body.SchemaVersion = &v
			}
			if ctx.IsSet("settings") {
				if err := decodeFlagJSON(ctx, "settings", ctx.String("settings"), &body.Settings); err != nil {
					return err
				}
			}
			if ctx.IsSet("status") {
				v := api.LoopStatus(ctx.String("status"))
				body.Status = &v
			}
			if ctx.IsSet("steps") {
				if err := decodeFlagJSON(ctx, "steps", ctx.String("steps"), &body.Steps); err != nil {
					return err
				}
			}
			if tags, err := parseTagFlags(ctx); err != nil {
				return err
			} else if tags != nil {
				v := api.TagMap(tags)
				body.Tags = &v
			}
			if ctx.IsSet("triggers") {
				if err := decodeFlagJSON(ctx, "triggers", ctx.String("triggers"), &body.Triggers); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("agent-id") && !ctx.IsSet("cleanup") && !ctx.IsSet("concurrency") && !ctx.IsSet("config") && !ctx.IsSet("default-config") && !ctx.IsSet("defaults") && !ctx.IsSet("description") && !ctx.IsSet("event") && !ctx.IsSet("limits") && !ctx.IsSet("name") && !ctx.IsSet("repositories") && !ctx.IsSet("run-name") && !ctx.IsSet("schema-version") && !ctx.IsSet("settings") && !ctx.IsSet("status") && !ctx.IsSet("steps") && !ctx.IsSet("tag") && !ctx.IsSet("triggers") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateLoopWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateLoop", resp.StatusCode(), resp.Body)
		})

}
