// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerNotificationPreferencesCommands registers every generated subcommand in the "notification-preferences" group.
func registerNotificationPreferencesCommands(app *cli.App) {
	notificationPreferencesGrp := app.Group("notification-preferences")
	notificationPreferencesGrp.Alias("notification-preference")
	notificationPreferencesGrp.Command("get-preferences").
		Description("Get notification preferences for an actor").
		Args("actor-type", "actor-id").
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			resp, err := client.GetNotificationPreferencesWithResponse(ctx.Context(), api.GetNotificationPreferencesParamsActorType(p0), p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, "getNotificationPreferences", resp.StatusCode(), resp.Body)
		})

	notificationPreferencesGrp.Command("update-preferences").
		Description("Update notification preferences for an actor").
		Args("actor-type", "actor-id").
		Flags(
			cli.String("channels", "").Help("[required] channels Accepts JSON, @file, or @-."),
			cli.String("file", "f").Help("Request body from a file (JSON or YAML, '-' for stdin). Flags override file contents."),
			cli.Bool("dry-run", "").Help("Print the assembled request body and exit without sending it."),
		).
		Use(requireAuth()).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.Arg(0)
			p1 := ctx.Arg(1)
			var body api.UpdateNotificationPreferencesJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("channels") {
				if err := decodeFlagJSON(ctx, "channels", ctx.String("channels"), &body.Channels); err != nil {
					return err
				}
			}
			if ctx.String("file") == "" && !ctx.IsSet("channels") {
				return fmt.Errorf("--channels is required (or supply it via --file)")
			}
			if ctx.Bool("dry-run") {
				return printDryRun(ctx, body)
			}
			resp, err := client.UpdateNotificationPreferencesWithResponse(ctx.Context(), api.UpdateNotificationPreferencesParamsActorType(p0), p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, "updateNotificationPreferences", resp.StatusCode(), resp.Body)
		})

}
