// Code generated by mobius-cligen. DO NOT EDIT.
//
// Regenerate with:  make generate-go-cli
//
// To suppress or override a command, edit
// cmd/mobius-cligen/overrides.go — never hand-edit this file.

package main

import (
	"encoding/json"
	"fmt"

	"github.com/deepnoodle-ai/wonton/cli"

	"github.com/deepnoodle-ai/mobius/mobius/api"
)

// registerActionsCommands registers every generated subcommand in the "actions" group.
func registerActionsCommands(app *cli.App) {
	actionsGrp := app.Group("actions").Description("Custom HTTP actions called by workflow steps")
	actionsGrp.Alias("action")
	actionsGrp.Command("create").
		Description("Create an action").
		Flags(
			cli.String("annotations", "").Help("Request hints that describe the safe-use properties of the action. Used by the engine and tooling to decide retry behavior, dry-run eligibility, etc. Unknown request properties are rejected. (JSON)"),
			cli.String("description", "").Help("Markdown-safe description of what the action does."),
			cli.String("endpoint-url", "").Help("[required] HTTP/HTTPS URL Mobius will POST to when invoking the action."),
			cli.String("input-schema", "").Help("JSON Schema describing the expected input parameters. (JSON)"),
			cli.String("name", "").Help("[required] Project-scoped identifier used in workflow step definitions. Lowercase alphanumeric + hyphens, e.g. \"send-email\". Must be unique within the project. Cannot start with \"mobius.\" (reserved prefix)."),
			cli.String("output-schema", "").Help("JSON Schema describing the expected output shape. (JSON)"),
			cli.String("title", "").Help("Human-readable display name shown in the UI and catalog."),
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			var body api.CreateActionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("annotations") {
				if err := json.Unmarshal([]byte(ctx.String("annotations")), &body.Annotations); err != nil {
					return fmt.Errorf("--annotations: invalid JSON: %w", err)
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("endpoint-url") {
				body.EndpointUrl = ctx.String("endpoint-url")
			}
			if ctx.IsSet("input-schema") {
				if err := json.Unmarshal([]byte(ctx.String("input-schema")), &body.InputSchema); err != nil {
					return fmt.Errorf("--input-schema: invalid JSON: %w", err)
				}
			}
			if ctx.IsSet("name") {
				body.Name = ctx.String("name")
			}
			if ctx.IsSet("output-schema") {
				if err := json.Unmarshal([]byte(ctx.String("output-schema")), &body.OutputSchema); err != nil {
					return fmt.Errorf("--output-schema: invalid JSON: %w", err)
				}
			}
			if ctx.IsSet("title") {
				v := ctx.String("title")
				body.Title = &v
			}
			if body.EndpointUrl == "" {
				return fmt.Errorf("--endpoint-url is required (or supply it via --file)")
			}
			if body.Name == "" {
				return fmt.Errorf("--name is required (or supply it via --file)")
			}
			resp, err := client.CreateActionWithResponse(ctx.Context(), p0, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("delete").
		Description("Delete an action").
		Args("action-name").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			resp, err := client.DeleteActionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("get").
		Description("Get an action by name").
		Args("action-name").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			resp, err := client.GetActionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("get-action").
		Description("Get one catalog action by name").
		Args("action-name").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			resp, err := client.GetCatalogActionWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("list").
		Description("List actions").
		Flags(
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			params := &api.ListActionsParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			resp, err := client.ListActionsWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("list-actions").
		Description("List the action catalog").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			resp, err := client.ListCatalogActionsWithResponse(ctx.Context(), p0)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("list-audit-log").
		Description("List action invocation audit records").
		Flags(
			cli.String("cursor", "").Help("cursor"),
			cli.Int("limit", "").Help("limit"),
			cli.String("run-id", "").Help("Filter to invocations from a specific workflow run."),
			cli.String("action-name", "").Help("Filter to invocations of a specific action."),
			cli.String("status", "").Help("Filter by terminal status (e.g. \"success\", \"failed\")."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			params := &api.ListActionAuditLogParams{}
			if ctx.IsSet("cursor") {
				v := api.CursorParam(ctx.String("cursor"))
				params.Cursor = &v
			}
			if ctx.IsSet("limit") {
				v := api.LimitParam(ctx.Int("limit"))
				params.Limit = &v
			}
			if ctx.IsSet("run-id") {
				v := ctx.String("run-id")
				params.RunId = &v
			}
			if ctx.IsSet("action-name") {
				v := ctx.String("action-name")
				params.ActionName = &v
			}
			if ctx.IsSet("status") {
				v := ctx.String("status")
				params.Status = &v
			}
			resp, err := client.ListActionAuditLogWithResponse(ctx.Context(), p0, params)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("rotate-secret").
		Description("Rotate an action signing secret").
		Args("action-name").
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			resp, err := client.RotateActionSecretWithResponse(ctx.Context(), p0, p1)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

	actionsGrp.Command("update").
		Description("Update an action").
		Args("action-name").
		Flags(
			cli.String("annotations", "").Help("Request hints that describe the safe-use properties of the action. Used by the engine and tooling to decide retry behavior, dry-run eligibility, etc. Unknown request properties are rejected. (JSON)"),
			cli.String("description", "").Help("Replacement Markdown description."),
			cli.String("endpoint-url", "").Help("Replacement endpoint URL."),
			cli.String("input-schema", "").Help("Replacement JSON Schema for inputs. Replaces the existing schema. (JSON)"),
			cli.String("output-schema", "").Help("Replacement JSON Schema for outputs. Replaces the existing schema. (JSON)"),
			cli.String("title", "").Help("Replacement display title."),
			cli.String("file", "f").Help("Request body as JSON (path to file, or '-' for stdin). Flags override file contents."),
		).
		Use(cli.RequireFlags("api-key")).
		Run(func(ctx *cli.Context) error {
			mc, err := clientFromContext(ctx)
			if err != nil {
				return err
			}
			client := mc.RawClient()
			p0 := ctx.String("project")
			p1 := ctx.Arg(0)
			var body api.UpdateActionJSONRequestBody
			if err := readJSONBody(ctx, &body); err != nil {
				return err
			}
			if ctx.IsSet("annotations") {
				if err := json.Unmarshal([]byte(ctx.String("annotations")), &body.Annotations); err != nil {
					return fmt.Errorf("--annotations: invalid JSON: %w", err)
				}
			}
			if ctx.IsSet("description") {
				v := ctx.String("description")
				body.Description = &v
			}
			if ctx.IsSet("endpoint-url") {
				v := ctx.String("endpoint-url")
				body.EndpointUrl = &v
			}
			if ctx.IsSet("input-schema") {
				if err := json.Unmarshal([]byte(ctx.String("input-schema")), &body.InputSchema); err != nil {
					return fmt.Errorf("--input-schema: invalid JSON: %w", err)
				}
			}
			if ctx.IsSet("output-schema") {
				if err := json.Unmarshal([]byte(ctx.String("output-schema")), &body.OutputSchema); err != nil {
					return fmt.Errorf("--output-schema: invalid JSON: %w", err)
				}
			}
			if ctx.IsSet("title") {
				v := ctx.String("title")
				body.Title = &v
			}
			if ctx.String("file") == "" && !ctx.IsSet("annotations") && !ctx.IsSet("description") && !ctx.IsSet("endpoint-url") && !ctx.IsSet("input-schema") && !ctx.IsSet("output-schema") && !ctx.IsSet("title") {
				return fmt.Errorf("at least one flag or --file is required")
			}
			resp, err := client.UpdateActionWithResponse(ctx.Context(), p0, p1, body)
			if err != nil {
				return err
			}
			return printResponse(ctx, resp.StatusCode(), resp.Body)
		})

}
